import BeeHoney from './BeeHoney';
import BimboLiqueur from './BimboLiqueur';
import BlackCatBeer from './BlackCatBeer';
import BlackSpellbook from './BlackSpellbook';
import BroBrew from './BroBrew';
import CaninePepper, { CaninePepperType } from './CaninePepper';
import CeruleanPotion from './CeruleanPotion';
import Coal from './Coal';
import Consumable from './Consumable';
import DeBimbo from './DeBimbo';
import DragonEgg from './DragonEgg';
import Ectoplasm from './Ectoplasm';
import Eggs, { EggType } from './Eggs';
import Equinum from './Equinum';
import FerretFruit from './FerretFruit';
import FishFillet from './FishFillet';
import FoxBerry from './FoxBerry';
import FoxJewel from './FoxJewel';
import GiantChocolateCupcake from './GiantChocolateCupcake';
import GoblinAle from './GoblinAle';
import GodsMead from './GodsMead';
import GoldenSeed from './GoldenSeed';
import GroPlus from './GroPlus';
import HairDye, { HairDyeType } from './HairDye';
import HairExtensionSerum from './HairExtensionSerum';
import HerbalContraceptive from './HerbalContraceptive';
import Hummus from './Hummus';
import ImpFood from './ImpFood';
import IncubusDraft from './IncubusDraft';
import IsabellaMilk from './IsabellaMilk';
import KangaFruit from './KangaFruit';
import KitsuneGift from './KitsuneGift';
import LaBova from './LaBova';
import Lactaid from './Lactaid';
import LustDraft from './LustDraft';
import LustStick from './LustStick';
import MarbleMilk from './MarbleMilk';
import MinotaurBlood from './MinotaurBlood';
import MinotaurCum from './MinotaurCum';
import MouseCocoa from './MouseCocoa';
import NeonPinkEgg from './NeonPinkEgg';
import NumbRock from './NumbRock';
import OvipositionElixir from './OvipositionElixir';
import PeppermintWhite from './PeppermintWhite';
import PhoukaWhiskey from './PhoukaWhiskey';
import PrincessPucker from './PrincessPucker';
import PurePearl from './PurePearl';
import PurityPeach from './PurityPeach';
import PurpleFruit from './PurpleFruit';
import Reducto from './Reducto';
import Reptilum from './Reptilum';
import RingtailFig from './RingtailFig';
import RizzaRoot from './RizzaRoot';
import ScholarsTea from './ScholarsTea';
import SensitivityDraft from './SensitivityDraft';
import SharkTooth from './SharkTooth';
import SheepMilk from './SheepMilk';
import ShriveledTentacle from './ShriveledTentacle';
import SnakeOil from './SnakeOil';
import SuccubiMilk from './SuccubiMilk';
import SuccubisDelight from './SuccubisDelight';
import SuccubisDream from './SuccubisDream';
import SweetGossamer from './SweetGossamer';
import TatteredScroll from './TatteredScroll';
import TrapOil from './TrapOil';
import VitalityTincture from './VitalityTincture';
import WetCloth from './WetCloth';
import WhiskerFruit from './WhiskerFruit';
import WhiteSpellbook from './WhiteSpellbook';
import WingStick from './WingStick';
import Library from '../../Utilities/Library';
import Utils from '../../Utilities/Utils';

export default class ConsumableLib extends Library<Consumable> {
    public constructor() {
        super();
        this.add(new BeeHoney(false, false));
        this.add(new BeeHoney(true, false));
        this.add(new BeeHoney(false, true));
        this.add(new BimboLiqueur());
        this.add(new BlackCatBeer());
        this.add(new BlackSpellbook());
        this.add(new BroBrew());
        this.add(new CaninePepper(CaninePepperType.Normal));
        this.add(new CaninePepper(CaninePepperType.Oversized));
        this.add(new CaninePepper(CaninePepperType.Double));
        this.add(new CaninePepper(CaninePepperType.Black));
        this.add(new CaninePepper(CaninePepperType.Knotty));
        this.add(new CaninePepper(CaninePepperType.Bulbous));
        this.add(new CeruleanPotion());
        this.add(new Coal());
        this.add(new DeBimbo());
        this.add(new DragonEgg());
        this.add(new Ectoplasm());
        this.add(new Eggs(EggType.Black, false));
        this.add(new Eggs(EggType.Blue, false));
        this.add(new Eggs(EggType.Brown, false));
        this.add(new Eggs(EggType.Pink, false));
        this.add(new Eggs(EggType.Purple, false));
        this.add(new Eggs(EggType.White, false));
        this.add(new Eggs(EggType.Black, true));
        this.add(new Eggs(EggType.Blue, true));
        this.add(new Eggs(EggType.Brown, true));
        this.add(new Eggs(EggType.Pink, true));
        this.add(new Eggs(EggType.Purple, true));
        this.add(new Eggs(EggType.White, true));
        this.add(new Equinum());
        this.add(new FerretFruit());
        this.add(new FishFillet());
        this.add(new FoxBerry(false));
        this.add(new FoxBerry(true));
        this.add(new FoxJewel(false));
        this.add(new FoxJewel(true));
        this.add(new GiantChocolateCupcake());
        this.add(new GoblinAle());
        this.add(new GodsMead());
        this.add(new GoldenSeed(false));
        this.add(new GoldenSeed(true));
        this.add(new GroPlus());
        this.add(new HairDye(HairDyeType.Auburn));
        this.add(new HairDye(HairDyeType.Black));
        this.add(new HairDye(HairDyeType.Blonde));
        this.add(new HairDye(HairDyeType.DarkBlue));
        this.add(new HairDye(HairDyeType.Brown));
        this.add(new HairDye(HairDyeType.Gray));
        this.add(new HairDye(HairDyeType.Green));
        this.add(new HairDye(HairDyeType.BrightOrange));
        this.add(new HairDye(HairDyeType.NeonPink));
        this.add(new HairDye(HairDyeType.Purple));
        this.add(new HairDye(HairDyeType.Red));
        this.add(new HairDye(HairDyeType.White));
        this.add(new HairExtensionSerum());
        this.add(new HerbalContraceptive());
        this.add(new Hummus());
        this.add(new ImpFood());
        this.add(new IncubusDraft(false));
        this.add(new IncubusDraft(true));
        this.add(new IsabellaMilk());
        this.add(new KangaFruit(false));
        this.add(new KangaFruit(true));
        this.add(new KitsuneGift());
        this.add(new LaBova(false, false));
        this.add(new LaBova(true, false));
        this.add(new LaBova(false, true));
        this.add(new Lactaid());
        this.add(new LustDraft(false));
        this.add(new LustDraft(true));
        this.add(new LustStick());
        this.add(new MarbleMilk());
        this.add(new MinotaurBlood());
        this.add(new MinotaurCum());
        this.add(new MouseCocoa());
        this.add(new NeonPinkEgg(false));
        this.add(new NeonPinkEgg(true));
        this.add(new NumbRock());
        this.add(new OvipositionElixir());
        this.add(new PeppermintWhite());
        this.add(new PhoukaWhiskey());
        this.add(new PrincessPucker());
        this.add(new PurePearl());
        this.add(new PurityPeach());
        this.add(new PurpleFruit());
        this.add(new Reducto());
        this.add(new Reptilum());
        this.add(new RingtailFig());
        this.add(new RizzaRoot());
        this.add(new ScholarsTea());
        this.add(new SensitivityDraft());
        this.add(new SharkTooth(false));
        this.add(new SharkTooth(true));
        this.add(new SheepMilk());
        this.add(new ShriveledTentacle());
        this.add(new SnakeOil());
        this.add(new SuccubiMilk(false));
        this.add(new SuccubiMilk(true));
        this.add(new SuccubisDelight(false));
        this.add(new SuccubisDelight(true));
        this.add(new SuccubisDream());
        this.add(new SweetGossamer(false));
        this.add(new SweetGossamer(true));
        this.add(new TatteredScroll());
        this.add(new TrapOil());
        this.add(new VitalityTincture());
        this.add(new WetCloth());
        this.add(new WhiskerFruit());
        this.add(new WhiteSpellbook());
        this.add(new WingStick());
    }
}
