import Consumable from './Consumable';
import ConstantLibrary from '../../Utilities/ConstantLibrary';
import Utils from '../../Utilities/Utils';
import Consumables, { CaninePepperType, EggType, HairDyeType } from '.';

export default class ConsumableLib extends ConstantLibrary<Consumable> {
    public constructor() {
        super();
        this.add(new Consumables.BeeHoney(false, false));
        this.add(new Consumables.BeeHoney(true, false));
        this.add(new Consumables.BeeHoney(false, true));
        this.add(new Consumables.BimboLiqueur());
        this.add(new Consumables.BlackCatBeer());
        this.add(new Consumables.BlackSpellbook());
        this.add(new Consumables.BroBrew());
        this.add(new Consumables.CaninePepper(CaninePepperType.Normal));
        this.add(new Consumables.CaninePepper(CaninePepperType.Oversized));
        this.add(new Consumables.CaninePepper(CaninePepperType.Double));
        this.add(new Consumables.CaninePepper(CaninePepperType.Black));
        this.add(new Consumables.CaninePepper(CaninePepperType.Knotty));
        this.add(new Consumables.CaninePepper(CaninePepperType.Bulbous));
        this.add(new Consumables.CeruleanPotion());
        this.add(new Consumables.Coal());
        this.add(new Consumables.DeBimbo());
        this.add(new Consumables.DragonEgg());
        this.add(new Consumables.Ectoplasm());
        this.add(new Consumables.Eggs(EggType.Black, false));
        this.add(new Consumables.Eggs(EggType.Blue, false));
        this.add(new Consumables.Eggs(EggType.Brown, false));
        this.add(new Consumables.Eggs(EggType.Pink, false));
        this.add(new Consumables.Eggs(EggType.Purple, false));
        this.add(new Consumables.Eggs(EggType.White, false));
        this.add(new Consumables.Eggs(EggType.Black, true));
        this.add(new Consumables.Eggs(EggType.Blue, true));
        this.add(new Consumables.Eggs(EggType.Brown, true));
        this.add(new Consumables.Eggs(EggType.Pink, true));
        this.add(new Consumables.Eggs(EggType.Purple, true));
        this.add(new Consumables.Eggs(EggType.White, true));
        this.add(new Consumables.Equinum());
        this.add(new Consumables.FerretFruit());
        this.add(new Consumables.FishFillet());
        this.add(new Consumables.FoxBerry(false));
        this.add(new Consumables.FoxBerry(true));
        this.add(new Consumables.FoxJewel(false));
        this.add(new Consumables.FoxJewel(true));
        this.add(new Consumables.GiantChocolateCupcake());
        this.add(new Consumables.GoblinAle());
        this.add(new Consumables.GodsMead());
        this.add(new Consumables.GoldenSeed(false));
        this.add(new Consumables.GoldenSeed(true));
        this.add(new Consumables.GroPlus());
        this.add(new Consumables.HairDye(HairDyeType.Auburn));
        this.add(new Consumables.HairDye(HairDyeType.Black));
        this.add(new Consumables.HairDye(HairDyeType.Blonde));
        this.add(new Consumables.HairDye(HairDyeType.DarkBlue));
        this.add(new Consumables.HairDye(HairDyeType.Brown));
        this.add(new Consumables.HairDye(HairDyeType.Gray));
        this.add(new Consumables.HairDye(HairDyeType.Green));
        this.add(new Consumables.HairDye(HairDyeType.BrightOrange));
        this.add(new Consumables.HairDye(HairDyeType.NeonPink));
        this.add(new Consumables.HairDye(HairDyeType.Purple));
        this.add(new Consumables.HairDye(HairDyeType.Red));
        this.add(new Consumables.HairDye(HairDyeType.White));
        this.add(new Consumables.HairExtensionSerum());
        this.add(new Consumables.HerbalContraceptive());
        this.add(new Consumables.Hummus());
        this.add(new Consumables.ImpFood());
        this.add(new Consumables.IncubusDraft(false));
        this.add(new Consumables.IncubusDraft(true));
        this.add(new Consumables.IsabellaMilk());
        this.add(new Consumables.KangaFruit(false));
        this.add(new Consumables.KangaFruit(true));
        this.add(new Consumables.KitsuneGift());
        this.add(new Consumables.LaBova(false, false));
        this.add(new Consumables.LaBova(true, false));
        this.add(new Consumables.LaBova(false, true));
        this.add(new Consumables.Lactaid());
        this.add(new Consumables.LustDraft(false));
        this.add(new Consumables.LustDraft(true));
        this.add(new Consumables.LustStick());
        this.add(new Consumables.MarbleMilk());
        this.add(new Consumables.MinotaurBlood());
        this.add(new Consumables.MinotaurCum());
        this.add(new Consumables.MouseCocoa());
        this.add(new Consumables.NeonPinkEgg(false));
        this.add(new Consumables.NeonPinkEgg(true));
        this.add(new Consumables.NumbRock());
        this.add(new Consumables.OvipositionElixir());
        this.add(new Consumables.PeppermintWhite());
        this.add(new Consumables.PhoukaWhiskey());
        this.add(new Consumables.PrincessPucker());
        this.add(new Consumables.PurePearl());
        this.add(new Consumables.PurityPeach());
        this.add(new Consumables.PurpleFruit());
        this.add(new Consumables.Reducto());
        this.add(new Consumables.Reptilum());
        this.add(new Consumables.RingtailFig());
        this.add(new Consumables.RizzaRoot());
        this.add(new Consumables.ScholarsTea());
        this.add(new Consumables.SensitivityDraft());
        this.add(new Consumables.SharkTooth(false));
        this.add(new Consumables.SharkTooth(true));
        this.add(new Consumables.SheepMilk());
        this.add(new Consumables.ShriveledTentacle());
        this.add(new Consumables.SnakeOil());
        this.add(new Consumables.SuccubiMilk(false));
        this.add(new Consumables.SuccubiMilk(true));
        this.add(new Consumables.SuccubisDelight(false));
        this.add(new Consumables.SuccubisDelight(true));
        this.add(new Consumables.SuccubisDream());
        this.add(new Consumables.SweetGossamer(false));
        this.add(new Consumables.SweetGossamer(true));
        this.add(new Consumables.TatteredScroll());
        this.add(new Consumables.TrapOil());
        this.add(new Consumables.VitalityTincture());
        this.add(new Consumables.WetCloth());
        this.add(new Consumables.WhiskerFruit());
        this.add(new Consumables.WhiteSpellbook());
        this.add(new Consumables.WingStick());
    }
}
