import Consumable from './Consumable';
import ConsumableName from './ConsumableName';
import Dictionary from '../../Utilities/Dictionary';
import { Utils } from '../../Utilities/Utils';
import Consumables, { CaninePepperType, EggType, HairDyeType } from '.';

export default class ConsumableLib extends Dictionary<Consumable> {
    public constructor() {
        super();
        this.set(ConsumableName.BeeHoney, new Consumables.BeeHoney(false, false));
        this.set(ConsumableName.BeeHoneyPure, new Consumables.BeeHoney(true, false));
        this.set(ConsumableName.BeeHoneySpecial, new Consumables.BeeHoney(false, true));
        this.set(ConsumableName.BimboLiqueur, new Consumables.BimboLiqueur());
        this.set(ConsumableName.BlackCatBeer, new Consumables.BlackCatBeer());
        this.set(ConsumableName.BlackSpellbook, new Consumables.BlackSpellbook());
        this.set(ConsumableName.BroBrew, new Consumables.BroBrew());
        this.set(ConsumableName.CaninePepper, new Consumables.CaninePepper(CaninePepperType.Normal));
        this.set(ConsumableName.CaninePepperLarge, new Consumables.CaninePepper(CaninePepperType.Oversized));
        this.set(ConsumableName.CaninePepperDouble, new Consumables.CaninePepper(CaninePepperType.Double));
        this.set(ConsumableName.CaninePepperBlack, new Consumables.CaninePepper(CaninePepperType.Black));
        this.set(ConsumableName.CaninePepperKnotty, new Consumables.CaninePepper(CaninePepperType.Knotty));
        this.set(ConsumableName.CaninePepperBulbous, new Consumables.CaninePepper(CaninePepperType.Bulbous));
        this.set(ConsumableName.CeruleanPotion, new Consumables.CeruleanPotion());
        this.set(ConsumableName.Coal, new Consumables.Coal());
        this.set(ConsumableName.DeBimbo, new Consumables.DeBimbo());
        this.set(ConsumableName.DragonEgg, new Consumables.DragonEgg());
        this.set(ConsumableName.Ectoplasm, new Consumables.Ectoplasm());
        this.set(ConsumableName.EggBlack, new Consumables.Eggs(EggType.Black, false));
        this.set(ConsumableName.EggBlue, new Consumables.Eggs(EggType.Blue, false));
        this.set(ConsumableName.EggBrown, new Consumables.Eggs(EggType.Brown, false));
        this.set(ConsumableName.EggPink, new Consumables.Eggs(EggType.Pink, false));
        this.set(ConsumableName.EggPurple, new Consumables.Eggs(EggType.Purple, false));
        this.set(ConsumableName.EggWhite, new Consumables.Eggs(EggType.White, false));
        this.set(ConsumableName.LargeEggBlack, new Consumables.Eggs(EggType.Black, true));
        this.set(ConsumableName.LargeEggBlue, new Consumables.Eggs(EggType.Blue, true));
        this.set(ConsumableName.LargeEggBrown, new Consumables.Eggs(EggType.Brown, true));
        this.set(ConsumableName.LargeEggPink, new Consumables.Eggs(EggType.Pink, true));
        this.set(ConsumableName.LargeEggPurple, new Consumables.Eggs(EggType.Purple, true));
        this.set(ConsumableName.LargeEggWhite, new Consumables.Eggs(EggType.White, true));
        this.set(ConsumableName.Equinum, new Consumables.Equinum());
        this.set(ConsumableName.FerretFruit, new Consumables.FerretFruit());
        this.set(ConsumableName.FishFillet, new Consumables.FishFillet());
        this.set(ConsumableName.FoxBerry, new Consumables.FoxBerry(false));
        this.set(ConsumableName.FoxBerryEnhanced, new Consumables.FoxBerry(true));
        this.set(ConsumableName.FoxJewel, new Consumables.FoxJewel(false));
        this.set(ConsumableName.FoxJewelEnhanced, new Consumables.FoxJewel(true));
        this.set(ConsumableName.GiantChocolateCupcake, new Consumables.GiantChocolateCupcake());
        this.set(ConsumableName.GoblinAle, new Consumables.GoblinAle());
        this.set(ConsumableName.GodsMead, new Consumables.GodsMead());
        this.set(ConsumableName.GoldenSeed, new Consumables.GoldenSeed(false));
        this.set(ConsumableName.GoldenSeedEnhanced, new Consumables.GoldenSeed(true));
        this.set(ConsumableName.GroPlus, new Consumables.GroPlus());
        this.set(ConsumableName.HairDyeAuburn, new Consumables.HairDye(HairDyeType.Auburn));
        this.set(ConsumableName.HairDyeBlack, new Consumables.HairDye(HairDyeType.Black));
        this.set(ConsumableName.HairDyeBlonde, new Consumables.HairDye(HairDyeType.Blonde));
        this.set(ConsumableName.HairDyeBrightOrange, new Consumables.HairDye(HairDyeType.BrightOrange));
        this.set(ConsumableName.HairDyeBrown, new Consumables.HairDye(HairDyeType.Brown));
        this.set(ConsumableName.HairDyeDarkBlue, new Consumables.HairDye(HairDyeType.DarkBlue));
        this.set(ConsumableName.HairDyeGray, new Consumables.HairDye(HairDyeType.Gray));
        this.set(ConsumableName.HairDyeGreen, new Consumables.HairDye(HairDyeType.Green));
        this.set(ConsumableName.HairDyeNeonPink, new Consumables.HairDye(HairDyeType.NeonPink));
        this.set(ConsumableName.HairDyePurple, new Consumables.HairDye(HairDyeType.Purple));
        this.set(ConsumableName.HairDyeRed, new Consumables.HairDye(HairDyeType.Red));
        this.set(ConsumableName.HairDyeWhite, new Consumables.HairDye(HairDyeType.White));
        this.set(ConsumableName.HairExtensionSerum, new Consumables.HairExtensionSerum());
        this.set(ConsumableName.HerbalContraceptive, new Consumables.HerbalContraceptive());
        this.set(ConsumableName.Hummus, new Consumables.Hummus());
        this.set(ConsumableName.ImpFood, new Consumables.ImpFood());
        this.set(ConsumableName.IncubusDraftPure, new Consumables.IncubusDraft(false));
        this.set(ConsumableName.IncubusDraft, new Consumables.IncubusDraft(true));
        this.set(ConsumableName.IsabellaMilk, new Consumables.IsabellaMilk());
        this.set(ConsumableName.KangaFruit, new Consumables.KangaFruit(false));
        this.set(ConsumableName.KangaFruitEnhanced, new Consumables.KangaFruit(true));
        this.set(ConsumableName.KitsuneGift, new Consumables.KitsuneGift());
        this.set(ConsumableName.LaBovaPure, new Consumables.LaBova(false, false));
        this.set(ConsumableName.LaBovaEnhanced, new Consumables.LaBova(true, false));
        this.set(ConsumableName.LaBova, new Consumables.LaBova(false, true));
        this.set(ConsumableName.Lactaid, new Consumables.Lactaid());
        this.set(ConsumableName.LustDraft, new Consumables.LustDraft(false));
        this.set(ConsumableName.LustDraftEnhanced, new Consumables.LustDraft(true));
        this.set(ConsumableName.LustStick, new Consumables.LustStick());
        this.set(ConsumableName.MarbleMilk, new Consumables.MarbleMilk());
        this.set(ConsumableName.MinotaurBlood, new Consumables.MinotaurBlood());
        this.set(ConsumableName.MinotaurCum, new Consumables.MinotaurCum());
        this.set(ConsumableName.MouseCocoa, new Consumables.MouseCocoa());
        this.set(ConsumableName.NeonPinkEgg, new Consumables.NeonPinkEgg(false));
        this.set(ConsumableName.NeonPinkEggPreg, new Consumables.NeonPinkEgg(true));
        this.set(ConsumableName.NumbRock, new Consumables.NumbRock());
        this.set(ConsumableName.OvipositionElixir, new Consumables.OvipositionElixir());
        this.set(ConsumableName.PeppermintWhite, new Consumables.PeppermintWhite());
        this.set(ConsumableName.PhoukaWhiskey, new Consumables.PhoukaWhiskey());
        this.set(ConsumableName.PrincessPucker, new Consumables.PrincessPucker());
        this.set(ConsumableName.PurePearl, new Consumables.PurePearl());
        this.set(ConsumableName.PurityPeach, new Consumables.PurityPeach());
        this.set(ConsumableName.PurpleFruit, new Consumables.PurpleFruit());
        this.set(ConsumableName.Reducto, new Consumables.Reducto());
        this.set(ConsumableName.Reptilum, new Consumables.Reptilum());
        this.set(ConsumableName.RingtailFig, new Consumables.RingtailFig());
        this.set(ConsumableName.RizzaRoot, new Consumables.RizzaRoot());
        this.set(ConsumableName.ScholarsTea, new Consumables.ScholarsTea());
        this.set(ConsumableName.SensitivityDraft, new Consumables.SensitivityDraft());
        this.set(ConsumableName.SharkTooth, new Consumables.SharkTooth(false));
        this.set(ConsumableName.SharkToothEnhanced, new Consumables.SharkTooth(true));
        this.set(ConsumableName.SheepMilk, new Consumables.SheepMilk());
        this.set(ConsumableName.ShriveledTentacle, new Consumables.ShriveledTentacle());
        this.set(ConsumableName.SnakeOil, new Consumables.SnakeOil());
        this.set(ConsumableName.SuccubiMilkPure, new Consumables.SuccubiMilk(false));
        this.set(ConsumableName.SuccubiMilk, new Consumables.SuccubiMilk(true));
        this.set(ConsumableName.SuccubisDelightPure, new Consumables.SuccubisDelight(false));
        this.set(ConsumableName.SuccubisDelight, new Consumables.SuccubisDelight(true));
        this.set(ConsumableName.SuccubisDream, new Consumables.SuccubisDream());
        this.set(ConsumableName.BlackGossamer, new Consumables.SweetGossamer(false));
        this.set(ConsumableName.SweetGossamer, new Consumables.SweetGossamer(true));
        this.set(ConsumableName.TatteredScroll, new Consumables.TatteredScroll());
        this.set(ConsumableName.TrapOil, new Consumables.TrapOil());
        this.set(ConsumableName.VitalityTincture, new Consumables.VitalityTincture());
        this.set(ConsumableName.WetCloth, new Consumables.WetCloth());
        this.set(ConsumableName.WhiskerFruit, new Consumables.WhiskerFruit());
        this.set(ConsumableName.WhiteSpellbook, new Consumables.WhiteSpellbook());
        this.set(ConsumableName.WingStick, new Consumables.WingStick());
    }
}
