import StatusAffectDesc from './StatusAffectDesc';
import { StatusAffectType } from './StatusAffectType';
import Library from '../Utilities/Library';

export default class StatusAffectDescLib extends Library<StatusAffectDesc> {
    public constructor() {
        super();
        this.add(StatusAffectFactory.createDesc(StatusAffectType.AllNaturalOnaholeUsed, "AllNaturalOnaholeUsed", "all-natural onahole used", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.AteEgg, "AteEgg", "ateEgg", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.AnemoneArousal, "AnemoneArousal", "Anemone Arousal", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BimboChampagne, "BimboChampagne", "Bimbo Champagne", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Birthed, "Birthed", "Birthed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BirthedImps, "BirthedImps", "Birthed Imps", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BlackCatBeer, "BlackCatBeer", "Black Cat Beer", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BlackNipples, "BlackNipples", "Black Nipples", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BlowjobOn, "BlowjobOn", "BlowjobOn", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BoatDiscovery, "BoatDiscovery", "Boat Discovery", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BonusACapacity, "BonusACapacity", "Bonus aCapacity", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BonusVCapacity, "BonusVCapacity", "Bonus vCapacity", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BottledMilk, "BottledMilk", "Bottled Milk", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BreastsMilked, "BreastsMilked", "Breasts Milked", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BSwordBroken, "BSwordBroken", "BSwordBroken", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BuiltMilker, "BuiltMilker", "BUILT: Milker", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BurpChanged, "BurpChanged", "Burp Changed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ButtStretched, "ButtStretched", "ButtStretched", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.CampAnemoneTrigger, "CampAnemoneTrigger", "Camp Anemone Trigger", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.CampMarble, "CampMarble", "Camp Marble", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.CampRathazul, "CampRathazul", "Camp Rathazul", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ClaraCombatRounds, "ClaraCombatRounds", "Clara Combat Rounds", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ClaraFoughtInCamp, "ClaraFoughtInCamp", "Clara Fought In Camp", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.CockPumped, "CockPumped", "Cock Pumped", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Contraceptives, "Contraceptives", "Contraceptives", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.CuntStretched, "CuntStretched", "CuntStretched", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DefenseCanopy, "DefenseCanopy", "Defense: Canopy", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DeluxeOnaholeUsed, "DeluxeOnaholeUsed", "deluxe onahole used", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DogWarning, "DogWarning", "dog warning", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DragonBreathBoost, "DragonBreathBoost", "Dragon Breath Boost", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DragonBreathCooldown, "DragonBreathCooldown", "Dragon Breath Cooldown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DungeonShutDown, "DungeonShutDown", "DungeonShutDown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Dysfunction, "Dysfunction", "dysfunction", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Edryn, "Edryn", "Edryn", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Eggchest, "Eggchest", "eggchest", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Eggs, "Eggs", "eggs", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.EmberFuckCooldown, "EmberFuckCooldown", "ember fuck cooldown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.EmberNapping, "EmberNapping", "Ember Napping", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.EverRapedJojo, "EverRapedJojo", "Ever Raped Jojo", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Exgartuan, "Exgartuan", "Exgartuan", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ExploredDeepwoods, "ExploredDeepwoods", "exploredDeepwoods", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FactoryOmnibusDefeated, "FactoryOmnibusDefeated", "FactoryOmnibusDefeated", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FactoryOverload, "FactoryOverload", "FactoryOverload", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FactoryIncubusDefeated, "FactoryIncubusDefeated", "FactoryIncubusDefeated", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FactorySuccubusDefeated, "FactorySuccubusDefeated", "FactorySuccubusDefeated", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FaerieFemFuck, "FaerieFemFuck", "Faerie Fem Fuck", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FaerieFucked, "FaerieFucked", "Faerie Fucked", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FappedGenderless, "FappedGenderless", "fapped genderless", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Feeder, "Feeder", "Feeder", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Fertilized, "Fertilized", "Fertilized", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FetishOn, "FetishOn", "fetishON", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FoundFactory, "FoundFactory", "Found Factory", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FuckedMarble, "FuckedMarble", "FuckedMarble", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Goojob, "Goojob", "GOOJOB", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.GooStuffed, "GooStuffed", "gooStuffed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Groundpound, "Groundpound", "Groundpound", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.HairdresserMeeting, "HairdresserMeeting", "hairdresser meeting", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Hangover, "Hangover", "Hangover", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Heat, "Heat", "heat", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.HorseWarning, "HorseWarning", "horse warning", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ImmolationSpell, "ImmolationSpell", "Immolation Spell", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ImpGangBang, "ImpGangBang", "Imp GangBang", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.IncubusBribed, "IncubusBribed", "IncubusBribed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Infested, "Infested", "infested", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.IzmaBlowing, "IzmaBlowing", "IzmaBlowing", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.IzumisPipeSmoke, "IzumisPipeSmoke", "Izumis Pipe Smoke", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.JerkingIzma, "JerkingIzma", "JerkingIzma", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Jizzpants, "Jizzpants", "Jizzpants", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.JojoMeditationCount, "JojoMeditationCount", "Jojo Meditation Count", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.JojoNightWatch, "JojoNightWatch", "JojoNightWatch", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.JojoTFOffer, "JojoTFOffer", "JojoTFOffer", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Kelt, "Kelt", "Kelt", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KeltBJ, "KeltBJ", "KeltBJ", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KeltBadEndWarning, "KeltBadEndWarning", "Kelt Bad End Warning", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KeltOff, "KeltOff", "KeltOff", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KnowsArouse, "KnowsArouse", "Knows Arouse", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KnowsBlind, "KnowsBlind", "Knows Blind", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KnowsCharge, "KnowsCharge", "Knows Charge", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KnowsHeal, "KnowsHeal", "Knows Heal", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KnowsMight, "KnowsMight", "Knows Might", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KnowsWhitefire, "KnowsWhitefire", "Knows Whitefire", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LactationEndurance, "LactationEndurance", "Lactation Endurance", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LactationReduction, "LactationReduction", "Lactation Reduction", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LactationReduc0, "LactationReduc0", "Lactation Reduc0", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LactationReduc1, "LactationReduc1", "Lactation Reduc1", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LactationReduc2, "LactationReduc2", "Lactation Reduc2", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LactationReduc3, "LactationReduc3", "Lactation Reduc3", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LootEgg, "LootEgg", "lootEgg", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LostVillagerSpecial, "LostVillagerSpecial", "lostVillagerSpecial", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LustStick, "Luststick", "Luststick", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LustStickApplied, "LustStickApplied", "Lust Stick Applied", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LustyTongue, "LustyTongue", "LustyTongue", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MalonVisitedPostAddiction, "MalonVisitedPostAddiction", "Malon Visited Post Addiction", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MaraeComplete, "MaraeComplete", "Marae Complete", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MaraesLethicite, "MaraesLethicite", "Marae's Lethicite", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MaraesQuestStart, "MaraesQuestStart", "Marae's Quest Start", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Marble, "Marble", "Marble", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MarbleHasItem, "MarbleHasItem", "MarbleHasItem", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MarbleItemCooldown, "MarbleItemCooldown", "MarbleItemCooldown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MarbleRapeAttempted, "MarbleRapeAttempted", "Marble Rape Attempted", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MarblesMilk, "MarblesMilk", "Marbles Milk", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MarbleSpecials, "MarbleSpecials", "MarbleSpecials", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MarbleWithdrawl, "MarbleWithdrawl", "MarbleWithdrawl", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Meditated, "Meditated", "Meditated", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MeanToNaga, "MeanToNaga", "MeanToNaga", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MeetWanderer, "MeetWanderer", "meet wanderer", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MetCorruptMarae, "MetCorruptMarae", "Met Corrupt Marae", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MetMarae, "MetMarae", "Met Marae", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MetRathazul, "MetRathazul", "metRathazul", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MetWorms, "MetWorms", "metWorms", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MetWhitney, "MetWhitney", "Met Whitney", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Milked, "Milked", "Milked", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MinoPlusCowgirl, "MinoPlusCowgirl", "Mino + Cowgirl", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Naga, "Naga", "Naga", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.NakedOn, "NakedOn", "NakedOn", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.NoJojo, "NoJojo", "noJojo", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.NoMoreMarble, "NoMoreMarble", "No More Marble", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Oswald, "Oswald", "Oswald", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PlainOnaholeUsed, "PlainOnaholeUsed", "plain onahole used", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PhoukaWhiskeyAffect, "PhoukaWhiskeyAffect", "PhoukaWhiskeyAffect", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PostAkbalSubmission, "PostAkbalSubmission", "Post Akbal Submission", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PostAnemoneBeatdown, "PostAnemoneBeatdown", "Post Anemone Beatdown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PureCampJojo, "PureCampJojo", "PureCampJojo", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.RathazulArmor, "RathazulArmor", "RathazulArmor", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.RepeatSuccubi, "RepeatSuccubi", "repeatSuccubi", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Rut, "Rut", "rut", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.SharkGirl, "SharkGirl", "Shark-Girl", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ShieldingSpell, "ShieldingSpell", "Shielding Spell", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.SlimeCraving, "SlimeCraving", "Slime Craving", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.SlimeCravingFeed, "SlimeCravingFeed", "Slime Craving Feed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.SlimeCravingOutput, "SlimeCravingOutput", "Slime Craving Output", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.SuccubiFirst, "SuccubiFirst", "SuccubiFirst", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.SuccubiNight, "SuccubiNight", "succubiNight", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TakenGroPlus, "TakenGroPlus", "TakenGro+", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TakenLactaid, "TakenLactaid", "TakenLactaid", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Tamani, "Tamani", "Tamani", ""));									//Used only for compatibility with old save files, otherwise no longer in use
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TamaniFemaleEncounter, "TamaniFemaleEncounter", "Tamani Female Encounter", ""));	//Used only for compatibility with old save files, otherwise no longer in use
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TelAdre, "TelAdre", "Tel'Adre", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TentacleBadEndCounter, "TentacleBadEndCounter", "TentacleBadEndCounter", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TentacleJojo, "TentacleJojo", "Tentacle Jojo", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TensionReleased, "TensionReleased", "TensionReleased", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TF2, "TF2", "TF2", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TookBlessedSword, "TookBlessedSword", "Took Blessed Sword", ""));
        /**
            * v1 = bonus index
            * v2 = bonus value
            * v3 = remaining time
            */
        this.add(StatusAffectFactory.createDesc(StatusAffectType.UmasMassage, "UmasMassage", "Uma's Massage", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Uniball, "Uniball", "Uniball", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.UsedNaturalSelfStim, "UsedNaturalSelfStim", "used natural self-stim", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.used_self_dash_stim, "used_self_dash_stim", "used self-stim", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Victoria, "Victoria", "Victoria", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.VoluntaryDemonpack, "VoluntaryDemonpack", "Voluntary Demonpack", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WormOffer, "WormOffer", "WormOffer", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WormPlugged, "WormPlugged", "worm plugged", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WormsHalf, "WormsHalf", "wormsHalf", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WormsOff, "WormsOff", "wormsOff", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WormsOn, "WormsOn", "wormsOn", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WandererDemon, "WandererDemon", "wanderer demon", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WandererHuman, "WandererHuman", "wanderer human", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Yara, "Yara", "Yara", ""));

        // monster
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Attacks, "Attacks", "attacks", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BimboBrawl, "BimboBrawl", "bimboBrawl", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BowCooldown, "BowCooldown", "Bow Cooldown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BowDisabled, "BowDisabled", "Bow Disabled", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Charged, "Charged", "Charged", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Climbed, "Climbed", "Climbed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Concentration, "Concentration", "Concentration", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Constricted, "Constricted", "Constricted", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.CoonWhip, "CoonWhip", "Coon Whip", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Counter, "Counter", "Counter", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DomFight, "DomFight", "domfight", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DrankMinoCum, "DrankMinoCum", "drank mino cum", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DrankMinoCum2, "DrankMinoCum2", "drank mino cum2", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Earthshield, "Earthshield", "Earthshield", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Fear, "Fear", "Fear", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.GenericRunDisabled, "GenericRunDisabled", "Generic Run Disabled", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Gigafire, "Gigafire", "Gigafire", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.GottaOpenGift, "GottaOpenGift", "Gotta Open Gift", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.HolliBurning, "HolliBurning", "Holli Burning", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Illusion, "Illusion", "Illusion", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ImpSkip, "ImpSkip", "ImpSkip", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ImpUber, "ImpUber", "ImpUber", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.JojoIsAssisting, "JojoIsAssisting", "Jojo Is Assisting", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.JojoPyre, "JojoPyre", "Jojo Pyre", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Keen, "Keen", "keen", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Level, "Level", "level", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KitsuneFight, "KitsuneFight", "Kitsune Fight", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LustAura, "LustAura", "Lust Aura", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LustStick, "LustStick", "LustStick", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Milk, "Milk", "milk", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MilkyUrta, "MilkyUrta", "Milky Urta", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MinoMilk, "MinoMilk", "Mino Milk", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MinotaurEntangled, "MinotaurEntangled", "Minotaur Entangled", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MissFirstRound, "MissFirstRound", "miss first round", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.NoLoot, "NoLoot", "No Loot", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PCTailTangle, "PCTailTangle", "PCTailTangle", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PeachLootLoss, "PeachLootLoss", "Peach Loot Loss", ""));
        // @aimozg i don't know and do not fucking care if these two should be merged
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PhyllaFight, "PhyllaFight", "PhyllaFight", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.phyllafight, "phyllafight", "phyllafight", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Platoon, "Platoon", "platoon", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.QueenBind, "QueenBind", "QueenBind", ""));
        // @aimozg HA HA HA
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Round, "Round", "Round", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.round, "round", "round", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.RunDisabled, "RunDisabled", "Run Disabled", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Shell, "Shell", "Shell", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.SirenSong, "SirenSong", "Siren Song", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Spar, "Spar", "spar", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Sparring, "Sparring", "sparring", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.spiderfight, "spiderfight", "spiderfight", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.StunCooldown, "StunCooldown", "Stun Cooldown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TentacleCoolDown, "TentacleCoolDown", "TentacleCoolDown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Timer, "Timer", "Timer", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Uber, "Uber", "Uber", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.UrtaSecondWinded, "UrtaSecondWinded", "Urta Second Winded", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.UsedTitsmother, "UsedTitsmother", "UsedTitsmother", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Vala, "Vala", "vala", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Vapula, "Vapula", "Vapula", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WhipReady, "WhipReady", "Whip Ready", ""));

        // combat
        this.add(StatusAffectFactory.createDesc(StatusAffectType.AcidSlap, "AcidSlap", "Acid Slap", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.AkbalSpeed, "AkbalSpeed", "Akbal Speed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.AmilyVenom, "AmilyVenom", "Amily Venom", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.AnemoneVenom, "AnemoneVenom", "Anemone Venom", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.AttackDisabled, "AttackDisabled", "Attack Disabled", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BasiliskCompulsion, "BasiliskCompulsion", "Basilisk Compulsion", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.BasiliskSlow, "BasiliskSlow", "BasiliskSlow", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Berzerking, "Berzerking", "Berzerking", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Blind, "Blind", "Blind", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Bound, "Bound", "Bound", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.CalledShot, "CalledShot", "Called Shot", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ChargeWeapon, "ChargeWeapon", "Charge Weapon", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Chokeslam, "Chokeslam", "Chokeslam", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Confusion, "Confusion", "Confusion", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DemonSeed, "DemonSeed", "DemonSeed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Disarmed, "Disarmed", "Disarmed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.DriderKiss, "DriderKiss", "Drider Kiss", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.FirstAttack, "FirstAttack", "FirstAttack", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.GnollSpear, "GnollSpear", "Gnoll Spear", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.GooArmorBind, "GooArmorBind", "GooArmorBind", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.GooArmorSilence, "GooArmorSilence", "GooArmorSilence", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.GooBind, "GooBind", "GooBind", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.HarpyBind, "HarpyBind", "HarpyBind", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.HolliConstrict, "HolliConstrict", "Holli Constrict", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.InfestAttempted, "InfestAttempted", "infestAttempted", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.IsabellaStunned, "IsabellaStunned", "Isabella Stunned", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.IzmaBleed, "IzmaBleed", "Izma Bleed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KissOfDeath, "KissOfDeath", "Kiss of Death", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.LustStones, "LustStones", "lust stones", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.lustvenom, "lustvenom", "lust venom", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Might, "Might", "Might", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.NagaBind, "NagaBind", "Naga Bind", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.NagaVenom, "NagaVenom", "Naga Venom", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.NoFlee, "NoFlee", "NoFlee", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ParalyzeVenom, "ParalyzeVenom", "paralyze venom", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.PhysicalDisabled, "PhysicalDisabled", "Physical Disabled", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Poison, "Poison", "Poison", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Sandstorm, "Sandstorm", "sandstorm", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Sealed, "Sealed", "Sealed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.SheilaOil, "SheilaOil", "Sheila Oil", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Shielding, "Shielding", "Sheilding", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.StoneLust, "StoneLust", "Stone Lust", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Stunned, "Stunned", "Stunned", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TailWhip, "TailWhip", "Tail Whip", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TemporaryHeat, "TemporaryHeat", "Temporary Heat", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TentacleBind, "TentacleBind", "TentacleBind", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ThroatPunch, "ThroatPunch", "Throat Punch", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Titsmother, "Titsmother", "Titsmother", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TwuWuv, "TwuWuv", "Twu Wuv", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.UBERWEB, "UBERWEB", "UBERWEB", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Web, "Web", "Web", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.WebSilence, "WebSilence", "Web-Silence", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Whispered, "Whispered", "Whispered", ""));

        this.add(StatusAffectFactory.createDesc(StatusAffectType.RemovedArmor, "RemovedArmor", "Removed Armor", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.JCLustLevel, "JCLustLevel", "JC Lust Level", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.MirroredAttack, "MirroredAttack", "Mirrored Attack", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.KnockedBack, "KnockedBack", "Knocked Back", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.Tentagrappled, "Tentagrappled", "Tentagrappled", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.TentagrappleCooldown, "TentagrappleCooldown", "Tentagrapple Cooldown", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.ShowerDotEffect, "ShowerDotEffect", "Shower Dot Effect", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.GardenerSapSpeed, "GardenerSapSpeed", "Sap Speed", ""));
        this.add(StatusAffectFactory.createDesc(StatusAffectType.VineHealUsed, "VineHealUsed", "Vine Heal Used", ""));
    }
}

