import StatusAffectDesc from './StatusAffectDesc';
import { StatusAffectType } from './StatusAffectType';
import Dictionary from '../Utilities/Dictionary';

export default class StatusAffectDescLib extends Dictionary<StatusAffectDesc> {
    public constructor() {
        super();
        this.set(StatusAffectType.AllNaturalOnaholeUsed, new StatusAffectDesc(StatusAffectType.AllNaturalOnaholeUsed, "AllNaturalOnaholeUsed", "all-natural onahole used", ""));
        this.set(StatusAffectType.AteEgg, new StatusAffectDesc(StatusAffectType.AteEgg, "AteEgg", "ateEgg", ""));
        this.set(StatusAffectType.AnemoneArousal, new StatusAffectDesc(StatusAffectType.AnemoneArousal, "AnemoneArousal", "Anemone Arousal", ""));
        this.set(StatusAffectType.BimboChampagne, new StatusAffectDesc(StatusAffectType.BimboChampagne, "BimboChampagne", "Bimbo Champagne", ""));
        this.set(StatusAffectType.Birthed, new StatusAffectDesc(StatusAffectType.Birthed, "Birthed", "Birthed", ""));
        this.set(StatusAffectType.BirthedImps, new StatusAffectDesc(StatusAffectType.BirthedImps, "BirthedImps", "Birthed Imps", ""));
        this.set(StatusAffectType.BlackCatBeer, new StatusAffectDesc(StatusAffectType.BlackCatBeer, "BlackCatBeer", "Black Cat Beer", ""));
        this.set(StatusAffectType.BlackNipples, new StatusAffectDesc(StatusAffectType.BlackNipples, "BlackNipples", "Black Nipples", ""));
        this.set(StatusAffectType.BlowjobOn, new StatusAffectDesc(StatusAffectType.BlowjobOn, "BlowjobOn", "BlowjobOn", ""));
        this.set(StatusAffectType.BoatDiscovery, new StatusAffectDesc(StatusAffectType.BoatDiscovery, "BoatDiscovery", "Boat Discovery", ""));
        this.set(StatusAffectType.BonusACapacity, new StatusAffectDesc(StatusAffectType.BonusACapacity, "BonusACapacity", "Bonus aCapacity", ""));
        this.set(StatusAffectType.BonusVCapacity, new StatusAffectDesc(StatusAffectType.BonusVCapacity, "BonusVCapacity", "Bonus vCapacity", ""));
        this.set(StatusAffectType.BottledMilk, new StatusAffectDesc(StatusAffectType.BottledMilk, "BottledMilk", "Bottled Milk", ""));
        this.set(StatusAffectType.BreastsMilked, new StatusAffectDesc(StatusAffectType.BreastsMilked, "BreastsMilked", "Breasts Milked", ""));
        this.set(StatusAffectType.BSwordBroken, new StatusAffectDesc(StatusAffectType.BSwordBroken, "BSwordBroken", "BSwordBroken", ""));
        this.set(StatusAffectType.BuiltMilker, new StatusAffectDesc(StatusAffectType.BuiltMilker, "BuiltMilker", "BUILT: Milker", ""));
        this.set(StatusAffectType.BurpChanged, new StatusAffectDesc(StatusAffectType.BurpChanged, "BurpChanged", "Burp Changed", ""));
        this.set(StatusAffectType.ButtStretched, new StatusAffectDesc(StatusAffectType.ButtStretched, "ButtStretched", "ButtStretched", ""));
        this.set(StatusAffectType.CampAnemoneTrigger, new StatusAffectDesc(StatusAffectType.CampAnemoneTrigger, "CampAnemoneTrigger", "Camp Anemone Trigger", ""));
        this.set(StatusAffectType.CampMarble, new StatusAffectDesc(StatusAffectType.CampMarble, "CampMarble", "Camp Marble", ""));
        this.set(StatusAffectType.CampRathazul, new StatusAffectDesc(StatusAffectType.CampRathazul, "CampRathazul", "Camp Rathazul", ""));
        this.set(StatusAffectType.ClaraCombatRounds, new StatusAffectDesc(StatusAffectType.ClaraCombatRounds, "ClaraCombatRounds", "Clara Combat Rounds", ""));
        this.set(StatusAffectType.ClaraFoughtInCamp, new StatusAffectDesc(StatusAffectType.ClaraFoughtInCamp, "ClaraFoughtInCamp", "Clara Fought In Camp", ""));
        this.set(StatusAffectType.CockPumped, new StatusAffectDesc(StatusAffectType.CockPumped, "CockPumped", "Cock Pumped", ""));
        this.set(StatusAffectType.Contraceptives, new StatusAffectDesc(StatusAffectType.Contraceptives, "Contraceptives", "Contraceptives", ""));
        this.set(StatusAffectType.CuntStretched, new StatusAffectDesc(StatusAffectType.CuntStretched, "CuntStretched", "CuntStretched", ""));
        this.set(StatusAffectType.DefenseCanopy, new StatusAffectDesc(StatusAffectType.DefenseCanopy, "DefenseCanopy", "Defense: Canopy", ""));
        this.set(StatusAffectType.DeluxeOnaholeUsed, new StatusAffectDesc(StatusAffectType.DeluxeOnaholeUsed, "DeluxeOnaholeUsed", "deluxe onahole used", ""));
        this.set(StatusAffectType.DogWarning, new StatusAffectDesc(StatusAffectType.DogWarning, "DogWarning", "dog warning", ""));
        this.set(StatusAffectType.DragonBreathBoost, new StatusAffectDesc(StatusAffectType.DragonBreathBoost, "DragonBreathBoost", "Dragon Breath Boost", ""));
        this.set(StatusAffectType.DragonBreathCooldown, new StatusAffectDesc(StatusAffectType.DragonBreathCooldown, "DragonBreathCooldown", "Dragon Breath Cooldown", ""));
        this.set(StatusAffectType.DungeonShutDown, new StatusAffectDesc(StatusAffectType.DungeonShutDown, "DungeonShutDown", "DungeonShutDown", ""));
        this.set(StatusAffectType.Dysfunction, new StatusAffectDesc(StatusAffectType.Dysfunction, "Dysfunction", "dysfunction", ""));
        this.set(StatusAffectType.Edryn, new StatusAffectDesc(StatusAffectType.Edryn, "Edryn", "Edryn", ""));
        this.set(StatusAffectType.Eggchest, new StatusAffectDesc(StatusAffectType.Eggchest, "Eggchest", "eggchest", ""));
        this.set(StatusAffectType.Eggs, new StatusAffectDesc(StatusAffectType.Eggs, "Eggs", "eggs", ""));
        this.set(StatusAffectType.EmberFuckCooldown, new StatusAffectDesc(StatusAffectType.EmberFuckCooldown, "EmberFuckCooldown", "ember fuck cooldown", ""));
        this.set(StatusAffectType.EmberNapping, new StatusAffectDesc(StatusAffectType.EmberNapping, "EmberNapping", "Ember Napping", ""));
        this.set(StatusAffectType.EverRapedJojo, new StatusAffectDesc(StatusAffectType.EverRapedJojo, "EverRapedJojo", "Ever Raped Jojo", ""));
        this.set(StatusAffectType.Exgartuan, new StatusAffectDesc(StatusAffectType.Exgartuan, "Exgartuan", "Exgartuan", ""));
        this.set(StatusAffectType.ExploredDeepwoods, new StatusAffectDesc(StatusAffectType.ExploredDeepwoods, "ExploredDeepwoods", "exploredDeepwoods", ""));
        this.set(StatusAffectType.FactoryOmnibusDefeated, new StatusAffectDesc(StatusAffectType.FactoryOmnibusDefeated, "FactoryOmnibusDefeated", "FactoryOmnibusDefeated", ""));
        this.set(StatusAffectType.FactoryOverload, new StatusAffectDesc(StatusAffectType.FactoryOverload, "FactoryOverload", "FactoryOverload", ""));
        this.set(StatusAffectType.FactoryIncubusDefeated, new StatusAffectDesc(StatusAffectType.FactoryIncubusDefeated, "FactoryIncubusDefeated", "FactoryIncubusDefeated", ""));
        this.set(StatusAffectType.FactorySuccubusDefeated, new StatusAffectDesc(StatusAffectType.FactorySuccubusDefeated, "FactorySuccubusDefeated", "FactorySuccubusDefeated", ""));
        this.set(StatusAffectType.FaerieFemFuck, new StatusAffectDesc(StatusAffectType.FaerieFemFuck, "FaerieFemFuck", "Faerie Fem Fuck", ""));
        this.set(StatusAffectType.FaerieFucked, new StatusAffectDesc(StatusAffectType.FaerieFucked, "FaerieFucked", "Faerie Fucked", ""));
        this.set(StatusAffectType.FappedGenderless, new StatusAffectDesc(StatusAffectType.FappedGenderless, "FappedGenderless", "fapped genderless", ""));
        this.set(StatusAffectType.Feeder, new StatusAffectDesc(StatusAffectType.Feeder, "Feeder", "Feeder", ""));
        this.set(StatusAffectType.Fertilized, new StatusAffectDesc(StatusAffectType.Fertilized, "Fertilized", "Fertilized", ""));
        this.set(StatusAffectType.FetishOn, new StatusAffectDesc(StatusAffectType.FetishOn, "FetishOn", "fetishON", ""));
        this.set(StatusAffectType.FoundFactory, new StatusAffectDesc(StatusAffectType.FoundFactory, "FoundFactory", "Found Factory", ""));
        this.set(StatusAffectType.FuckedMarble, new StatusAffectDesc(StatusAffectType.FuckedMarble, "FuckedMarble", "FuckedMarble", ""));
        this.set(StatusAffectType.Goojob, new StatusAffectDesc(StatusAffectType.Goojob, "Goojob", "GOOJOB", ""));
        this.set(StatusAffectType.GooStuffed, new StatusAffectDesc(StatusAffectType.GooStuffed, "GooStuffed", "gooStuffed", ""));
        this.set(StatusAffectType.Groundpound, new StatusAffectDesc(StatusAffectType.Groundpound, "Groundpound", "Groundpound", ""));
        this.set(StatusAffectType.HairdresserMeeting, new StatusAffectDesc(StatusAffectType.HairdresserMeeting, "HairdresserMeeting", "hairdresser meeting", ""));
        this.set(StatusAffectType.Hangover, new StatusAffectDesc(StatusAffectType.Hangover, "Hangover", "Hangover", ""));
        this.set(StatusAffectType.Heat, new StatusAffectDesc(StatusAffectType.Heat, "Heat", "heat", ""));
        this.set(StatusAffectType.HorseWarning, new StatusAffectDesc(StatusAffectType.HorseWarning, "HorseWarning", "horse warning", ""));
        this.set(StatusAffectType.ImmolationSpell, new StatusAffectDesc(StatusAffectType.ImmolationSpell, "ImmolationSpell", "Immolation Spell", ""));
        this.set(StatusAffectType.ImpGangBang, new StatusAffectDesc(StatusAffectType.ImpGangBang, "ImpGangBang", "Imp GangBang", ""));
        this.set(StatusAffectType.IncubusBribed, new StatusAffectDesc(StatusAffectType.IncubusBribed, "IncubusBribed", "IncubusBribed", ""));
        this.set(StatusAffectType.Infested, new StatusAffectDesc(StatusAffectType.Infested, "Infested", "infested", ""));
        this.set(StatusAffectType.IzmaBlowing, new StatusAffectDesc(StatusAffectType.IzmaBlowing, "IzmaBlowing", "IzmaBlowing", ""));
        this.set(StatusAffectType.IzumisPipeSmoke, new StatusAffectDesc(StatusAffectType.IzumisPipeSmoke, "IzumisPipeSmoke", "Izumis Pipe Smoke", ""));
        this.set(StatusAffectType.JerkingIzma, new StatusAffectDesc(StatusAffectType.JerkingIzma, "JerkingIzma", "JerkingIzma", ""));
        this.set(StatusAffectType.Jizzpants, new StatusAffectDesc(StatusAffectType.Jizzpants, "Jizzpants", "Jizzpants", ""));
        this.set(StatusAffectType.JojoMeditationCount, new StatusAffectDesc(StatusAffectType.JojoMeditationCount, "JojoMeditationCount", "Jojo Meditation Count", ""));
        this.set(StatusAffectType.JojoNightWatch, new StatusAffectDesc(StatusAffectType.JojoNightWatch, "JojoNightWatch", "JojoNightWatch", ""));
        this.set(StatusAffectType.JojoTFOffer, new StatusAffectDesc(StatusAffectType.JojoTFOffer, "JojoTFOffer", "JojoTFOffer", ""));
        this.set(StatusAffectType.Kelt, new StatusAffectDesc(StatusAffectType.Kelt, "Kelt", "Kelt", ""));
        this.set(StatusAffectType.KeltBJ, new StatusAffectDesc(StatusAffectType.KeltBJ, "KeltBJ", "KeltBJ", ""));
        this.set(StatusAffectType.KeltBadEndWarning, new StatusAffectDesc(StatusAffectType.KeltBadEndWarning, "KeltBadEndWarning", "Kelt Bad End Warning", ""));
        this.set(StatusAffectType.KeltOff, new StatusAffectDesc(StatusAffectType.KeltOff, "KeltOff", "KeltOff", ""));
        this.set(StatusAffectType.KnowsArouse, new StatusAffectDesc(StatusAffectType.KnowsArouse, "KnowsArouse", "Knows Arouse", ""));
        this.set(StatusAffectType.KnowsBlind, new StatusAffectDesc(StatusAffectType.KnowsBlind, "KnowsBlind", "Knows Blind", ""));
        this.set(StatusAffectType.KnowsCharge, new StatusAffectDesc(StatusAffectType.KnowsCharge, "KnowsCharge", "Knows Charge", ""));
        this.set(StatusAffectType.KnowsHeal, new StatusAffectDesc(StatusAffectType.KnowsHeal, "KnowsHeal", "Knows Heal", ""));
        this.set(StatusAffectType.KnowsMight, new StatusAffectDesc(StatusAffectType.KnowsMight, "KnowsMight", "Knows Might", ""));
        this.set(StatusAffectType.KnowsWhitefire, new StatusAffectDesc(StatusAffectType.KnowsWhitefire, "KnowsWhitefire", "Knows Whitefire", ""));
        this.set(StatusAffectType.LactationEndurance, new StatusAffectDesc(StatusAffectType.LactationEndurance, "LactationEndurance", "Lactation Endurance", ""));
        this.set(StatusAffectType.LactationReduction, new StatusAffectDesc(StatusAffectType.LactationReduction, "LactationReduction", "Lactation Reduction", ""));
        this.set(StatusAffectType.LactationReduc0, new StatusAffectDesc(StatusAffectType.LactationReduc0, "LactationReduc0", "Lactation Reduc0", ""));
        this.set(StatusAffectType.LactationReduc1, new StatusAffectDesc(StatusAffectType.LactationReduc1, "LactationReduc1", "Lactation Reduc1", ""));
        this.set(StatusAffectType.LactationReduc2, new StatusAffectDesc(StatusAffectType.LactationReduc2, "LactationReduc2", "Lactation Reduc2", ""));
        this.set(StatusAffectType.LactationReduc3, new StatusAffectDesc(StatusAffectType.LactationReduc3, "LactationReduc3", "Lactation Reduc3", ""));
        this.set(StatusAffectType.LootEgg, new StatusAffectDesc(StatusAffectType.LootEgg, "LootEgg", "lootEgg", ""));
        this.set(StatusAffectType.LostVillagerSpecial, new StatusAffectDesc(StatusAffectType.LostVillagerSpecial, "LostVillagerSpecial", "lostVillagerSpecial", ""));
        this.set(StatusAffectType.LustStick, new StatusAffectDesc(StatusAffectType.LustStick, "Luststick", "Luststick", ""));
        this.set(StatusAffectType.LustStickApplied, new StatusAffectDesc(StatusAffectType.LustStickApplied, "LustStickApplied", "Lust Stick Applied", ""));
        this.set(StatusAffectType.LustyTongue, new StatusAffectDesc(StatusAffectType.LustyTongue, "LustyTongue", "LustyTongue", ""));
        this.set(StatusAffectType.MalonVisitedPostAddiction, new StatusAffectDesc(StatusAffectType.MalonVisitedPostAddiction, "MalonVisitedPostAddiction", "Malon Visited Post Addiction", ""));
        this.set(StatusAffectType.MaraeComplete, new StatusAffectDesc(StatusAffectType.MaraeComplete, "MaraeComplete", "Marae Complete", ""));
        this.set(StatusAffectType.MaraesLethicite, new StatusAffectDesc(StatusAffectType.MaraesLethicite, "MaraesLethicite", "Marae's Lethicite", ""));
        this.set(StatusAffectType.MaraesQuestStart, new StatusAffectDesc(StatusAffectType.MaraesQuestStart, "MaraesQuestStart", "Marae's Quest Start", ""));
        this.set(StatusAffectType.Marble, new StatusAffectDesc(StatusAffectType.Marble, "Marble", "Marble", ""));
        this.set(StatusAffectType.MarbleHasItem, new StatusAffectDesc(StatusAffectType.MarbleHasItem, "MarbleHasItem", "MarbleHasItem", ""));
        this.set(StatusAffectType.MarbleItemCooldown, new StatusAffectDesc(StatusAffectType.MarbleItemCooldown, "MarbleItemCooldown", "MarbleItemCooldown", ""));
        this.set(StatusAffectType.MarbleRapeAttempted, new StatusAffectDesc(StatusAffectType.MarbleRapeAttempted, "MarbleRapeAttempted", "Marble Rape Attempted", ""));
        this.set(StatusAffectType.MarblesMilk, new StatusAffectDesc(StatusAffectType.MarblesMilk, "MarblesMilk", "Marbles Milk", ""));
        this.set(StatusAffectType.MarbleSpecials, new StatusAffectDesc(StatusAffectType.MarbleSpecials, "MarbleSpecials", "MarbleSpecials", ""));
        this.set(StatusAffectType.MarbleWithdrawl, new StatusAffectDesc(StatusAffectType.MarbleWithdrawl, "MarbleWithdrawl", "MarbleWithdrawl", ""));
        this.set(StatusAffectType.Meditated, new StatusAffectDesc(StatusAffectType.Meditated, "Meditated", "Meditated", ""));
        this.set(StatusAffectType.MeanToNaga, new StatusAffectDesc(StatusAffectType.MeanToNaga, "MeanToNaga", "MeanToNaga", ""));
        this.set(StatusAffectType.MeetWanderer, new StatusAffectDesc(StatusAffectType.MeetWanderer, "MeetWanderer", "meet wanderer", ""));
        this.set(StatusAffectType.MetCorruptMarae, new StatusAffectDesc(StatusAffectType.MetCorruptMarae, "MetCorruptMarae", "Met Corrupt Marae", ""));
        this.set(StatusAffectType.MetMarae, new StatusAffectDesc(StatusAffectType.MetMarae, "MetMarae", "Met Marae", ""));
        this.set(StatusAffectType.MetRathazul, new StatusAffectDesc(StatusAffectType.MetRathazul, "MetRathazul", "metRathazul", ""));
        this.set(StatusAffectType.MetWorms, new StatusAffectDesc(StatusAffectType.MetWorms, "MetWorms", "metWorms", ""));
        this.set(StatusAffectType.MetWhitney, new StatusAffectDesc(StatusAffectType.MetWhitney, "MetWhitney", "Met Whitney", ""));
        this.set(StatusAffectType.Milked, new StatusAffectDesc(StatusAffectType.Milked, "Milked", "Milked", ""));
        this.set(StatusAffectType.MinoPlusCowgirl, new StatusAffectDesc(StatusAffectType.MinoPlusCowgirl, "MinoPlusCowgirl", "Mino + Cowgirl", ""));
        this.set(StatusAffectType.Naga, new StatusAffectDesc(StatusAffectType.Naga, "Naga", "Naga", ""));
        this.set(StatusAffectType.NakedOn, new StatusAffectDesc(StatusAffectType.NakedOn, "NakedOn", "NakedOn", ""));
        this.set(StatusAffectType.NoJojo, new StatusAffectDesc(StatusAffectType.NoJojo, "NoJojo", "noJojo", ""));
        this.set(StatusAffectType.NoMoreMarble, new StatusAffectDesc(StatusAffectType.NoMoreMarble, "NoMoreMarble", "No More Marble", ""));
        this.set(StatusAffectType.Oswald, new StatusAffectDesc(StatusAffectType.Oswald, "Oswald", "Oswald", ""));
        this.set(StatusAffectType.PlainOnaholeUsed, new StatusAffectDesc(StatusAffectType.PlainOnaholeUsed, "PlainOnaholeUsed", "plain onahole used", ""));
        this.set(StatusAffectType.PhoukaWhiskeyAffect, new StatusAffectDesc(StatusAffectType.PhoukaWhiskeyAffect, "PhoukaWhiskeyAffect", "PhoukaWhiskeyAffect", ""));
        this.set(StatusAffectType.PostAkbalSubmission, new StatusAffectDesc(StatusAffectType.PostAkbalSubmission, "PostAkbalSubmission", "Post Akbal Submission", ""));
        this.set(StatusAffectType.PostAnemoneBeatdown, new StatusAffectDesc(StatusAffectType.PostAnemoneBeatdown, "PostAnemoneBeatdown", "Post Anemone Beatdown", ""));
        this.set(StatusAffectType.PureCampJojo, new StatusAffectDesc(StatusAffectType.PureCampJojo, "PureCampJojo", "PureCampJojo", ""));
        this.set(StatusAffectType.RathazulArmor, new StatusAffectDesc(StatusAffectType.RathazulArmor, "RathazulArmor", "RathazulArmor", ""));
        this.set(StatusAffectType.RepeatSuccubi, new StatusAffectDesc(StatusAffectType.RepeatSuccubi, "RepeatSuccubi", "repeatSuccubi", ""));
        this.set(StatusAffectType.Rut, new StatusAffectDesc(StatusAffectType.Rut, "Rut", "rut", ""));
        this.set(StatusAffectType.SharkGirl, new StatusAffectDesc(StatusAffectType.SharkGirl, "SharkGirl", "Shark-Girl", ""));
        this.set(StatusAffectType.ShieldingSpell, new StatusAffectDesc(StatusAffectType.ShieldingSpell, "ShieldingSpell", "Shielding Spell", ""));
        this.set(StatusAffectType.SlimeCraving, new StatusAffectDesc(StatusAffectType.SlimeCraving, "SlimeCraving", "Slime Craving", ""));
        this.set(StatusAffectType.SlimeCravingFeed, new StatusAffectDesc(StatusAffectType.SlimeCravingFeed, "SlimeCravingFeed", "Slime Craving Feed", ""));
        this.set(StatusAffectType.SlimeCravingOutput, new StatusAffectDesc(StatusAffectType.SlimeCravingOutput, "SlimeCravingOutput", "Slime Craving Output", ""));
        this.set(StatusAffectType.SuccubiFirst, new StatusAffectDesc(StatusAffectType.SuccubiFirst, "SuccubiFirst", "SuccubiFirst", ""));
        this.set(StatusAffectType.SuccubiNight, new StatusAffectDesc(StatusAffectType.SuccubiNight, "SuccubiNight", "succubiNight", ""));
        this.set(StatusAffectType.TakenGroPlus, new StatusAffectDesc(StatusAffectType.TakenGroPlus, "TakenGroPlus", "TakenGro+", ""));
        this.set(StatusAffectType.TakenLactaid, new StatusAffectDesc(StatusAffectType.TakenLactaid, "TakenLactaid", "TakenLactaid", ""));
        // Used only for compatibility with old save files, otherwise no longer in use
        this.set(StatusAffectType.Tamani, new StatusAffectDesc(StatusAffectType.Tamani, "Tamani", "Tamani", ""));
        // Used only for compatibility with old save files, otherwise no longer in use
        this.set(StatusAffectType.TamaniFemaleEncounter, new StatusAffectDesc(StatusAffectType.TamaniFemaleEncounter, "TamaniFemaleEncounter", "Tamani Female Encounter", ""));
        this.set(StatusAffectType.TelAdre, new StatusAffectDesc(StatusAffectType.TelAdre, "TelAdre", "Tel'Adre", ""));
        this.set(StatusAffectType.TentacleBadEndCounter, new StatusAffectDesc(StatusAffectType.TentacleBadEndCounter, "TentacleBadEndCounter", "TentacleBadEndCounter", ""));
        this.set(StatusAffectType.TentacleJojo, new StatusAffectDesc(StatusAffectType.TentacleJojo, "TentacleJojo", "Tentacle Jojo", ""));
        this.set(StatusAffectType.TensionReleased, new StatusAffectDesc(StatusAffectType.TensionReleased, "TensionReleased", "TensionReleased", ""));
        this.set(StatusAffectType.TF2, new StatusAffectDesc(StatusAffectType.TF2, "TF2", "TF2", ""));
        this.set(StatusAffectType.TookBlessedSword, new StatusAffectDesc(StatusAffectType.TookBlessedSword, "TookBlessedSword", "Took Blessed Sword", ""));
        /**
         * v1 = bonus index
         * v2 = bonus value
         * v3 = remaining time
         */
        this.set(StatusAffectType.UmasMassage, new StatusAffectDesc(StatusAffectType.UmasMassage, "UmasMassage", "Uma's Massage", ""));
        this.set(StatusAffectType.Uniball, new StatusAffectDesc(StatusAffectType.Uniball, "Uniball", "Uniball", ""));
        this.set(StatusAffectType.UsedNaturalSelfStim, new StatusAffectDesc(StatusAffectType.UsedNaturalSelfStim, "UsedNaturalSelfStim", "used natural self-stim", ""));
        this.set(StatusAffectType.used_self_dash_stim, new StatusAffectDesc(StatusAffectType.used_self_dash_stim, "used_self_dash_stim", "used self-stim", ""));
        this.set(StatusAffectType.Victoria, new StatusAffectDesc(StatusAffectType.Victoria, "Victoria", "Victoria", ""));
        this.set(StatusAffectType.VoluntaryDemonpack, new StatusAffectDesc(StatusAffectType.VoluntaryDemonpack, "VoluntaryDemonpack", "Voluntary Demonpack", ""));
        this.set(StatusAffectType.WormOffer, new StatusAffectDesc(StatusAffectType.WormOffer, "WormOffer", "WormOffer", ""));
        this.set(StatusAffectType.WormPlugged, new StatusAffectDesc(StatusAffectType.WormPlugged, "WormPlugged", "worm plugged", ""));
        this.set(StatusAffectType.WormsHalf, new StatusAffectDesc(StatusAffectType.WormsHalf, "WormsHalf", "wormsHalf", ""));
        this.set(StatusAffectType.WormsOff, new StatusAffectDesc(StatusAffectType.WormsOff, "WormsOff", "wormsOff", ""));
        this.set(StatusAffectType.WormsOn, new StatusAffectDesc(StatusAffectType.WormsOn, "WormsOn", "wormsOn", ""));
        this.set(StatusAffectType.WandererDemon, new StatusAffectDesc(StatusAffectType.WandererDemon, "WandererDemon", "wanderer demon", ""));
        this.set(StatusAffectType.WandererHuman, new StatusAffectDesc(StatusAffectType.WandererHuman, "WandererHuman", "wanderer human", ""));
        this.set(StatusAffectType.Yara, new StatusAffectDesc(StatusAffectType.Yara, "Yara", "Yara", ""));

        // monster
        this.set(StatusAffectType.Attacks, new StatusAffectDesc(StatusAffectType.Attacks, "Attacks", "attacks", ""));
        this.set(StatusAffectType.BimboBrawl, new StatusAffectDesc(StatusAffectType.BimboBrawl, "BimboBrawl", "bimboBrawl", ""));
        this.set(StatusAffectType.BowCooldown, new StatusAffectDesc(StatusAffectType.BowCooldown, "BowCooldown", "Bow Cooldown", ""));
        this.set(StatusAffectType.BowDisabled, new StatusAffectDesc(StatusAffectType.BowDisabled, "BowDisabled", "Bow Disabled", ""));
        this.set(StatusAffectType.Charged, new StatusAffectDesc(StatusAffectType.Charged, "Charged", "Charged", ""));
        this.set(StatusAffectType.Climbed, new StatusAffectDesc(StatusAffectType.Climbed, "Climbed", "Climbed", ""));
        this.set(StatusAffectType.Concentration, new StatusAffectDesc(StatusAffectType.Concentration, "Concentration", "Concentration", ""));
        this.set(StatusAffectType.Constricted, new StatusAffectDesc(StatusAffectType.Constricted, "Constricted", "Constricted", ""));
        this.set(StatusAffectType.CoonWhip, new StatusAffectDesc(StatusAffectType.CoonWhip, "CoonWhip", "Coon Whip", ""));
        this.set(StatusAffectType.Counter, new StatusAffectDesc(StatusAffectType.Counter, "Counter", "Counter", ""));
        this.set(StatusAffectType.DomFight, new StatusAffectDesc(StatusAffectType.DomFight, "DomFight", "domfight", ""));
        this.set(StatusAffectType.DrankMinoCum, new StatusAffectDesc(StatusAffectType.DrankMinoCum, "DrankMinoCum", "drank mino cum", ""));
        this.set(StatusAffectType.DrankMinoCum2, new StatusAffectDesc(StatusAffectType.DrankMinoCum2, "DrankMinoCum2", "drank mino cum2", ""));
        this.set(StatusAffectType.Earthshield, new StatusAffectDesc(StatusAffectType.Earthshield, "Earthshield", "Earthshield", ""));
        this.set(StatusAffectType.Fear, new StatusAffectDesc(StatusAffectType.Fear, "Fear", "Fear", ""));
        this.set(StatusAffectType.GenericRunDisabled, new StatusAffectDesc(StatusAffectType.GenericRunDisabled, "GenericRunDisabled", "Generic Run Disabled", ""));
        this.set(StatusAffectType.Gigafire, new StatusAffectDesc(StatusAffectType.Gigafire, "Gigafire", "Gigafire", ""));
        this.set(StatusAffectType.GottaOpenGift, new StatusAffectDesc(StatusAffectType.GottaOpenGift, "GottaOpenGift", "Gotta Open Gift", ""));
        this.set(StatusAffectType.HolliBurning, new StatusAffectDesc(StatusAffectType.HolliBurning, "HolliBurning", "Holli Burning", ""));
        this.set(StatusAffectType.Illusion, new StatusAffectDesc(StatusAffectType.Illusion, "Illusion", "Illusion", ""));
        this.set(StatusAffectType.ImpSkip, new StatusAffectDesc(StatusAffectType.ImpSkip, "ImpSkip", "ImpSkip", ""));
        this.set(StatusAffectType.ImpUber, new StatusAffectDesc(StatusAffectType.ImpUber, "ImpUber", "ImpUber", ""));
        this.set(StatusAffectType.JojoIsAssisting, new StatusAffectDesc(StatusAffectType.JojoIsAssisting, "JojoIsAssisting", "Jojo Is Assisting", ""));
        this.set(StatusAffectType.JojoPyre, new StatusAffectDesc(StatusAffectType.JojoPyre, "JojoPyre", "Jojo Pyre", ""));
        this.set(StatusAffectType.Keen, new StatusAffectDesc(StatusAffectType.Keen, "Keen", "keen", ""));
        this.set(StatusAffectType.Level, new StatusAffectDesc(StatusAffectType.Level, "Level", "level", ""));
        this.set(StatusAffectType.KitsuneFight, new StatusAffectDesc(StatusAffectType.KitsuneFight, "KitsuneFight", "Kitsune Fight", ""));
        this.set(StatusAffectType.LustAura, new StatusAffectDesc(StatusAffectType.LustAura, "LustAura", "Lust Aura", ""));
        this.set(StatusAffectType.LustStick, new StatusAffectDesc(StatusAffectType.LustStick, "LustStick", "LustStick", ""));
        this.set(StatusAffectType.Milk, new StatusAffectDesc(StatusAffectType.Milk, "Milk", "milk", ""));
        this.set(StatusAffectType.MilkyUrta, new StatusAffectDesc(StatusAffectType.MilkyUrta, "MilkyUrta", "Milky Urta", ""));
        this.set(StatusAffectType.MinoMilk, new StatusAffectDesc(StatusAffectType.MinoMilk, "MinoMilk", "Mino Milk", ""));
        this.set(StatusAffectType.MinotaurEntangled, new StatusAffectDesc(StatusAffectType.MinotaurEntangled, "MinotaurEntangled", "Minotaur Entangled", ""));
        this.set(StatusAffectType.MissFirstRound, new StatusAffectDesc(StatusAffectType.MissFirstRound, "MissFirstRound", "miss first round", ""));
        this.set(StatusAffectType.NoLoot, new StatusAffectDesc(StatusAffectType.NoLoot, "NoLoot", "No Loot", ""));
        this.set(StatusAffectType.PCTailTangle, new StatusAffectDesc(StatusAffectType.PCTailTangle, "PCTailTangle", "PCTailTangle", ""));
        this.set(StatusAffectType.PeachLootLoss, new StatusAffectDesc(StatusAffectType.PeachLootLoss, "PeachLootLoss", "Peach Loot Loss", ""));
        // @aimozg i don't know and do not fucking care if these two should be merged
        this.set(StatusAffectType.PhyllaFight, new StatusAffectDesc(StatusAffectType.PhyllaFight, "PhyllaFight", "PhyllaFight", ""));
        this.set(StatusAffectType.Platoon, new StatusAffectDesc(StatusAffectType.Platoon, "Platoon", "platoon", ""));
        this.set(StatusAffectType.QueenBind, new StatusAffectDesc(StatusAffectType.QueenBind, "QueenBind", "QueenBind", ""));
        // @aimozg HA HA HA
        this.set(StatusAffectType.Round, new StatusAffectDesc(StatusAffectType.Round, "Round", "Round", ""));
        this.set(StatusAffectType.RunDisabled, new StatusAffectDesc(StatusAffectType.RunDisabled, "RunDisabled", "Run Disabled", ""));
        this.set(StatusAffectType.Shell, new StatusAffectDesc(StatusAffectType.Shell, "Shell", "Shell", ""));
        this.set(StatusAffectType.SirenSong, new StatusAffectDesc(StatusAffectType.SirenSong, "SirenSong", "Siren Song", ""));
        this.set(StatusAffectType.Spar, new StatusAffectDesc(StatusAffectType.Spar, "Spar", "spar", ""));
        this.set(StatusAffectType.Sparring, new StatusAffectDesc(StatusAffectType.Sparring, "Sparring", "sparring", ""));
        this.set(StatusAffectType.spiderfight, new StatusAffectDesc(StatusAffectType.spiderfight, "spiderfight", "spiderfight", ""));
        this.set(StatusAffectType.StunCooldown, new StatusAffectDesc(StatusAffectType.StunCooldown, "StunCooldown", "Stun Cooldown", ""));
        this.set(StatusAffectType.TentacleCoolDown, new StatusAffectDesc(StatusAffectType.TentacleCoolDown, "TentacleCoolDown", "TentacleCoolDown", ""));
        this.set(StatusAffectType.Timer, new StatusAffectDesc(StatusAffectType.Timer, "Timer", "Timer", ""));
        this.set(StatusAffectType.Uber, new StatusAffectDesc(StatusAffectType.Uber, "Uber", "Uber", ""));
        this.set(StatusAffectType.UrtaSecondWinded, new StatusAffectDesc(StatusAffectType.UrtaSecondWinded, "UrtaSecondWinded", "Urta Second Winded", ""));
        this.set(StatusAffectType.UsedTitsmother, new StatusAffectDesc(StatusAffectType.UsedTitsmother, "UsedTitsmother", "UsedTitsmother", ""));
        this.set(StatusAffectType.Vala, new StatusAffectDesc(StatusAffectType.Vala, "Vala", "vala", ""));
        this.set(StatusAffectType.Vapula, new StatusAffectDesc(StatusAffectType.Vapula, "Vapula", "Vapula", ""));
        this.set(StatusAffectType.WhipReady, new StatusAffectDesc(StatusAffectType.WhipReady, "WhipReady", "Whip Ready", ""));

        // combat
        this.set(StatusAffectType.AcidSlap, new StatusAffectDesc(StatusAffectType.AcidSlap, "AcidSlap", "Acid Slap", ""));
        this.set(StatusAffectType.AkbalSpeed, new StatusAffectDesc(StatusAffectType.AkbalSpeed, "AkbalSpeed", "Akbal Speed", ""));
        this.set(StatusAffectType.AmilyVenom, new StatusAffectDesc(StatusAffectType.AmilyVenom, "AmilyVenom", "Amily Venom", ""));
        this.set(StatusAffectType.AnemoneVenom, new StatusAffectDesc(StatusAffectType.AnemoneVenom, "AnemoneVenom", "Anemone Venom", ""));
        this.set(StatusAffectType.AttackDisabled, new StatusAffectDesc(StatusAffectType.AttackDisabled, "AttackDisabled", "Attack Disabled", ""));
        this.set(StatusAffectType.BasiliskCompulsion, new StatusAffectDesc(StatusAffectType.BasiliskCompulsion, "BasiliskCompulsion", "Basilisk Compulsion", ""));
        this.set(StatusAffectType.BasiliskSlow, new StatusAffectDesc(StatusAffectType.BasiliskSlow, "BasiliskSlow", "BasiliskSlow", ""));
        this.set(StatusAffectType.Berzerking, new StatusAffectDesc(StatusAffectType.Berzerking, "Berzerking", "Berzerking", ""));
        this.set(StatusAffectType.Blind, new StatusAffectDesc(StatusAffectType.Blind, "Blind", "Blind", ""));
        this.set(StatusAffectType.Bound, new StatusAffectDesc(StatusAffectType.Bound, "Bound", "Bound", ""));
        this.set(StatusAffectType.CalledShot, new StatusAffectDesc(StatusAffectType.CalledShot, "CalledShot", "Called Shot", ""));
        this.set(StatusAffectType.ChargeWeapon, new StatusAffectDesc(StatusAffectType.ChargeWeapon, "ChargeWeapon", "Charge Weapon", ""));
        this.set(StatusAffectType.Chokeslam, new StatusAffectDesc(StatusAffectType.Chokeslam, "Chokeslam", "Chokeslam", ""));
        this.set(StatusAffectType.Confusion, new StatusAffectDesc(StatusAffectType.Confusion, "Confusion", "Confusion", ""));
        this.set(StatusAffectType.DemonSeed, new StatusAffectDesc(StatusAffectType.DemonSeed, "DemonSeed", "DemonSeed", ""));
        this.set(StatusAffectType.Disarmed, new StatusAffectDesc(StatusAffectType.Disarmed, "Disarmed", "Disarmed", ""));
        this.set(StatusAffectType.DriderKiss, new StatusAffectDesc(StatusAffectType.DriderKiss, "DriderKiss", "Drider Kiss", ""));
        this.set(StatusAffectType.FirstAttack, new StatusAffectDesc(StatusAffectType.FirstAttack, "FirstAttack", "FirstAttack", ""));
        this.set(StatusAffectType.GnollSpear, new StatusAffectDesc(StatusAffectType.GnollSpear, "GnollSpear", "Gnoll Spear", ""));
        this.set(StatusAffectType.GooArmorBind, new StatusAffectDesc(StatusAffectType.GooArmorBind, "GooArmorBind", "GooArmorBind", ""));
        this.set(StatusAffectType.GooArmorSilence, new StatusAffectDesc(StatusAffectType.GooArmorSilence, "GooArmorSilence", "GooArmorSilence", ""));
        this.set(StatusAffectType.GooBind, new StatusAffectDesc(StatusAffectType.GooBind, "GooBind", "GooBind", ""));
        this.set(StatusAffectType.HarpyBind, new StatusAffectDesc(StatusAffectType.HarpyBind, "HarpyBind", "HarpyBind", ""));
        this.set(StatusAffectType.HolliConstrict, new StatusAffectDesc(StatusAffectType.HolliConstrict, "HolliConstrict", "Holli Constrict", ""));
        this.set(StatusAffectType.InfestAttempted, new StatusAffectDesc(StatusAffectType.InfestAttempted, "InfestAttempted", "infestAttempted", ""));
        this.set(StatusAffectType.IsabellaStunned, new StatusAffectDesc(StatusAffectType.IsabellaStunned, "IsabellaStunned", "Isabella Stunned", ""));
        this.set(StatusAffectType.IzmaBleed, new StatusAffectDesc(StatusAffectType.IzmaBleed, "IzmaBleed", "Izma Bleed", ""));
        this.set(StatusAffectType.KissOfDeath, new StatusAffectDesc(StatusAffectType.KissOfDeath, "KissOfDeath", "Kiss of Death", ""));
        this.set(StatusAffectType.LustStones, new StatusAffectDesc(StatusAffectType.LustStones, "LustStones", "lust stones", ""));
        this.set(StatusAffectType.lustvenom, new StatusAffectDesc(StatusAffectType.lustvenom, "lustvenom", "lust venom", ""));
        this.set(StatusAffectType.Might, new StatusAffectDesc(StatusAffectType.Might, "Might", "Might", ""));
        this.set(StatusAffectType.NagaBind, new StatusAffectDesc(StatusAffectType.NagaBind, "NagaBind", "Naga Bind", ""));
        this.set(StatusAffectType.NagaVenom, new StatusAffectDesc(StatusAffectType.NagaVenom, "NagaVenom", "Naga Venom", ""));
        this.set(StatusAffectType.NoFlee, new StatusAffectDesc(StatusAffectType.NoFlee, "NoFlee", "NoFlee", ""));
        this.set(StatusAffectType.ParalyzeVenom, new StatusAffectDesc(StatusAffectType.ParalyzeVenom, "ParalyzeVenom", "paralyze venom", ""));
        this.set(StatusAffectType.PhysicalDisabled, new StatusAffectDesc(StatusAffectType.PhysicalDisabled, "PhysicalDisabled", "Physical Disabled", ""));
        this.set(StatusAffectType.Poison, new StatusAffectDesc(StatusAffectType.Poison, "Poison", "Poison", ""));
        this.set(StatusAffectType.Sandstorm, new StatusAffectDesc(StatusAffectType.Sandstorm, "Sandstorm", "sandstorm", ""));
        this.set(StatusAffectType.Sealed, new StatusAffectDesc(StatusAffectType.Sealed, "Sealed", "Sealed", ""));
        this.set(StatusAffectType.SheilaOil, new StatusAffectDesc(StatusAffectType.SheilaOil, "SheilaOil", "Sheila Oil", ""));
        this.set(StatusAffectType.Shielding, new StatusAffectDesc(StatusAffectType.Shielding, "Shielding", "Sheilding", ""));
        this.set(StatusAffectType.StoneLust, new StatusAffectDesc(StatusAffectType.StoneLust, "StoneLust", "Stone Lust", ""));
        this.set(StatusAffectType.Stunned, new StatusAffectDesc(StatusAffectType.Stunned, "Stunned", "Stunned", ""));
        this.set(StatusAffectType.TailWhip, new StatusAffectDesc(StatusAffectType.TailWhip, "TailWhip", "Tail Whip", ""));
        this.set(StatusAffectType.TemporaryHeat, new StatusAffectDesc(StatusAffectType.TemporaryHeat, "TemporaryHeat", "Temporary Heat", ""));
        this.set(StatusAffectType.TentacleBind, new StatusAffectDesc(StatusAffectType.TentacleBind, "TentacleBind", "TentacleBind", ""));
        this.set(StatusAffectType.ThroatPunch, new StatusAffectDesc(StatusAffectType.ThroatPunch, "ThroatPunch", "Throat Punch", ""));
        this.set(StatusAffectType.Titsmother, new StatusAffectDesc(StatusAffectType.Titsmother, "Titsmother", "Titsmother", ""));
        this.set(StatusAffectType.TwuWuv, new StatusAffectDesc(StatusAffectType.TwuWuv, "TwuWuv", "Twu Wuv", ""));
        this.set(StatusAffectType.UBERWEB, new StatusAffectDesc(StatusAffectType.UBERWEB, "UBERWEB", "UBERWEB", ""));
        this.set(StatusAffectType.Web, new StatusAffectDesc(StatusAffectType.Web, "Web", "Web", ""));
        this.set(StatusAffectType.WebSilence, new StatusAffectDesc(StatusAffectType.WebSilence, "WebSilence", "Web-Silence", ""));
        this.set(StatusAffectType.Whispered, new StatusAffectDesc(StatusAffectType.Whispered, "Whispered", "Whispered", ""));

        this.set(StatusAffectType.RemovedArmor, new StatusAffectDesc(StatusAffectType.RemovedArmor, "RemovedArmor", "Removed Armor", ""));
        this.set(StatusAffectType.JCLustLevel, new StatusAffectDesc(StatusAffectType.JCLustLevel, "JCLustLevel", "JC Lust Level", ""));
        this.set(StatusAffectType.MirroredAttack, new StatusAffectDesc(StatusAffectType.MirroredAttack, "MirroredAttack", "Mirrored Attack", ""));
        this.set(StatusAffectType.KnockedBack, new StatusAffectDesc(StatusAffectType.KnockedBack, "KnockedBack", "Knocked Back", ""));
        this.set(StatusAffectType.Tentagrappled, new StatusAffectDesc(StatusAffectType.Tentagrappled, "Tentagrappled", "Tentagrappled", ""));
        this.set(StatusAffectType.TentagrappleCooldown, new StatusAffectDesc(StatusAffectType.TentagrappleCooldown, "TentagrappleCooldown", "Tentagrapple Cooldown", ""));
        this.set(StatusAffectType.ShowerDotEffect, new StatusAffectDesc(StatusAffectType.ShowerDotEffect, "ShowerDotEffect", "Shower Dot Effect", ""));
        this.set(StatusAffectType.GardenerSapSpeed, new StatusAffectDesc(StatusAffectType.GardenerSapSpeed, "GardenerSapSpeed", "Sap Speed", ""));
        this.set(StatusAffectType.VineHealUsed, new StatusAffectDesc(StatusAffectType.VineHealUsed, "VineHealUsed", "Vine Heal Used", ""));
    }
}
