import { NextScreenChoices } from '../ScreenDisplay';
import { mainMenu } from './MainMenu';
import { CView } from '../../Engine/Display/ContentView';

export function creditsMenu(): NextScreenChoices {
    CView.clear();
    CView.text("<b>Coding and Main Events:</b>\n");
    CView.text("<ul>");
    CView.text("<li> Fenoxo</li>\n");
    CView.text("</ul>");
    CView.text("<b>Typo Reporting</b>\n");
    CView.text("<ul>");
    CView.text("<li> SoS</li>");
    CView.text("<li> Prisoner416</li>");
    CView.text("<li> Chibodee</li>");
    CView.text("</ul>");
    CView.text("");
    CView.text("<b>Graphical Prettiness:</b>");
    CView.text("<ul>");
    CView.text("<li> Dasutin (Background Images)</li>");
    CView.text("<li> Invader (Button Graphics, Font, and Other Hawtness)</li>");
    CView.text("</ul>");
    CView.text("<b>Supplementary Events:</b>");
    CView.text("<ul>");
    CView.text("<li> Dxasmodeus (Tentacles, Worms, Giacomo)</li>");
    CView.text("<li> Kirbster (Christmas Bunny Trap)</li>");
    CView.text("<li> nRage (Kami the Christmas Roo)</li>");
    CView.text("<li> Abraxas (Alternate Naga Scenes w/Various Monsters, Tamani Anal, Female Shouldra Tongue Licking, Chameleon Girl, Christmas Harpy)</li>");
    CView.text("<li> Astronomy (Fetish Cultist Centaur Footjob Scene)</li>");
    CView.text("<li> Adjatha (Scylla the Cum Addicted Nun, Vala, Goo-girls, Bimbo Sophie Eggs, Ceraph Urta Roleplay, Gnoll with Balls Scene, Kiha futa scene, Goblin Web Fuck Scene, and 69 Bunny Scene)</li>");
    CView.text("<li> ComfyCushion (Muff Wrangler)</li>");
    CView.text("<li> B (Brooke)</li>");
    CView.text("<li> Quiet Browser (Half of Niamh, Ember, Amily The Mouse-girl Breeder, Katherine, Part of Katherine Employment Expansion, Urta's in-bar Dialogue Trees, some of Izma, Loppe)</li>");
    CView.text("<li> Indirect (Alternate Non-Scylla Katherine Recruitment, Part of Katherine Employment Expansion, Phouka, Coding of Bee Girl Expansion)</li>");
    CView.text("<li> Schpadoinkle (Victoria Sex)</li>");
    CView.text("<li> Donto (Ro'gar the Orc, Polar Pete)</li>");
    CView.text("<li> Angel (Additional Amily Scenes)</li>");
    CView.text("<li> Firedragon (Additional Amily Scenes)</li>");
    CView.text("<li> Danaume (Jojo masturbation texts)</li>");
    CView.text("<li> LimitLax (Sand-Witch Bad-End)</li>");
    CView.text("<li> KLN (Equinum Bad-End)</li>");
    CView.text("<li> TheDarkTemplar11111 (Canine Pepper Bad End)</li>");
    CView.text("<li> Silmarion (Canine Pepper Bad End)</li>");
    CView.text("<li> Soretu (Original Minotaur Rape)</li>");
    CView.text("<li> NinjArt (Small Male on Goblin Rape Variant)</li>");
    CView.text("<li> DoubleRedd (\"Too Big\" Corrupt Goblin Fuck)</li>");
    CView.text("<li> Nightshade (Additional Minotaur Rape)</li>");
    CView.text("<li> JCM (Imp Night Gangbang, Addition Minotaur Loss Rape - Oral)</li>");
    CView.text("<li> Xodin (Nipplefucking paragraph of Imp GangBang, Encumbered by Big Genitals Exploration Scene, Big Bits Run Encumbrance, Player Getting Beer Tits, Sand Witch Dungeon Misc Scenes)</li>");
    CView.text("<li> Blusox6 (Original Queen Bee Rape)</li>");
    CView.text("<li> Thrext (Additional Masturbation Code, Faerie, Ivory Succubus)</li>");
    CView.text("<li> XDumort (Genderless Anal Masturbation)</li>");
    CView.text("<li> Uldego (Slime Monster)</li>");
    CView.text("<li> Noogai, Reaper, and Numbers (Nipple-Fucking Victory vs Imp Rape)</li>");
    CView.text("<li> Verse and IAMurow (Bee-Girl MultiCock Rapes)</li>");
    CView.text("<li> Sombrero (Additional Imp Lust Loss Scene (Dick insertion ahoy!)</li>");
    CView.text("<li> The Dark Master (Marble, Fetish Cultist, Fetish Zealot, Hellhound, Lumi, Some Cat Transformations, LaBova, Ceraph's Cat-Slaves, a Cum Witch Scene, Mouse Dreams, Forced Nursing:Imps&Goblins, Bee Girl Expansion)</li>");
    CView.text("<li> Mr. Fleshcage (Cat Transformation/Masturbation)</li>");
    CView.text("<li> Spy (Cat Masturbation, Forced Nursing: Minotaur, Bee, & Cultist)</li>");
    CView.text("<li> PostNuclearMan (Some Cat TF)</li>");
    CView.text("<li> MiscChaos (Forced Nursing: Slime Monster)</li>");
    CView.text("<li> Ourakun (Kelt the Centaur)</li>");
    CView.text("<li> Rika_star25 (Desert Tribe Bad End)</li>");
    CView.text("<li> Versesai (Additional Bee Rape)</li>");
    CView.text("<li> Mallowman (Additional Bee Rape)</li>");
    CView.text("<li> HypnoKitten (Additional Centaur x Imp Rape)</li>");
    CView.text("<li> Ari (Minotaur Gloryhole Scene)</li>");
    CView.text("<li> SpectralTime (Aunt Nancy)</li>");
    CView.text("<li> Foxxling (Akbal)</li>");
    CView.text("<li> Elfensyne (Phylla)</li>");
    CView.text("<li> Radar (Dominating Sand Witches, Some Phylla)</li>");
    CView.text("<li> Jokester (Sharkgirls, Izma, & Additional Amily Scenes)</li>");
    CView.text("<li> Lukadoc (Additional Izma, Ceraph Followers Corrupting Gangbang, Satyrs, Ember)</li>");
    CView.text("<li> IxFa (Dildo Scene, Virgin Scene for Deluxe Dildo, Naga Tail Masturbation)</li>");
    CView.text("<li> Bob (Additional Izma)</li>");
    CView.text("<li> lh84 (Various Typos and Code-Suggestions)</li>");
    CView.text("<li> Dextersinister (Gnoll girl in the plains)</li>");
    CView.text("<li> ElAcechador, Bandichar, TheParanoidOne, Xoeleox (All Things Naga)</li>");
    CView.text("<li> Symphonie (Dominika the Fellatrix, Ceraph RPing as Dominika, Tel'Adre Library)</li>");
    CView.text("<li> Soulsemmer (Ifris)</li>");
    CView.text("<li> WedgeSkyrocket (Zetsuko, Pure Amily Anal, Kitsunes)</li>");
    CView.text("<li> Zeikfried (Anemone, Male Milker Bad End, Kanga TF, Raccoon TF, Minotaur Chef Dialogues, Sheila, and More)</li>");
    CView.text("<li> User21 (Additional Centaur/Naga Scenes)</li>");
    CView.text("<li> ~M~ (Bimbo + Imp loss scene)</li>");
    CView.text("<li> Grype (Raping Hellhounds)</li>");
    CView.text("<li> B-Side (Fentendo Entertainment Center Silly-Mode Scene)</li>");
    CView.text("<li> Not Important (Face-fucking a defeated minotaur)</li>");
    CView.text("<li> Third (Cotton, Rubi, Nieve, Urta Pet-play)</li>");
    CView.text("<li> Gurumash (Parts of Nieve)</li>");
    CView.text("<li> Kinathis (A Nieve Scene, Sophie Daughter Incest, Minerva)</li>");
    CView.text("<li> Jibajabroar (Jasun)</li>");
    CView.text("<li> Merauder (Raphael)</li>");
    CView.text("<li> EdgeofReality (Gym fucking machine)</li>");
    CView.text("<li> Bronycray (Heckel the Hyena)</li>");
    CView.text("<li> Sablegryphon (Gnoll spear-thrower)</li>");
    CView.text("<li> Nonesuch (Basilisk, Sandtraps, assisted with Owca/Vapula, Whitney Farm Corruption)</li>");
    CView.text("<li> Anonymous Individual (Lilium, PC Birthing Driders)</li>");
    CView.text("<li> PKD (Owca, Vapula, Fap Arena, Isabella Tentacle Sex, Lottie Tentacle Sex)</li>");
    CView.text("<li> Shamblesworth (Half of Niamh, Shouldra the Ghost-Girl, Ceraph Roleplaying As Marble, Yara Sex, Shouldra Follow Expansion)</li>");
    CView.text("<li> Kirbu (Exgartuan Expansion, Yara Sex, Shambles's Handler, Shouldra Follow Expansion)</li>");
    CView.text("<li> 05095 (Shouldra Expansion, Tons of Editing)</li>");
    CView.text("<li> Smidgeums (Shouldra + Vala threesome)</li>");
    CView.text("<li> FC (Generic Shouldra talk scene)</li>");
    CView.text("<li> Oak (Bro + Bimbo TF, Isabella's ProBova Burps)</li>");
    CView.text("<li> Space (Victory Anal Sex vs Kiha)</li>");
    CView.text("<li> Venithil (LippleLock w/Scylla & Additional Urta Scenes)</li>");
    CView.text("<li> Butts McGee (Minotaur Hot-dogging PC loss, Tamani Lesbo Face-ride, Bimbo Sophie Mean/Nice Fucks)</li>");
    CView.text("<li> Savin (Hel the Salamander, Valeria, Spanking Drunk Urta, Tower of the Phoenix, Drider Anal Victory, Hel x Isabella 3Some, Centaur Sextoys, Thanksgiving Turkey, Uncorrupt Latexy Recruitment, Assert Path for Direct Feeding Latexy, Sanura the Sphinx)</li>");
    CView.text("<li> Gats (Lottie, Spirit & Soldier Xmas Event, Kiha forced masturbation, Goblin Doggystyle, Chicken Harpy Egg Vendor)</li>");
    CView.text("<li> Aeron the Demoness (Generic Goblin Anal, Disciplining the Eldest Minotaur)</li>");
    CView.text("<li> Gats, Shamblesworth, Symphonie, and Fenoxo (Corrupted Drider)</li>");
    CView.text("<li> Bagpuss (Female Thanksgiving Event, Harpy Scissoring, Drider Bondage Fuck)</li>");
    CView.text("<li> Frogapus (The Wild Hunt)</li>");
    CView.text("<li> Fenoxo (Everything Else)</li>");
    CView.text("</ul>");
    CView.text("<b>Oviposition Update Credits - Names in Order Appearance in Oviposition Document</b>");
    CView.text("<ul>");
    CView.text("<li> DCR (Idea, Drider Transformation, and Drider Impreg of: Goblins, Beegirls, Nagas, Harpies, and Basilisks)</li>");
    CView.text("<li> Fenoxo (Bee Ovipositor Transformation, Bee Oviposition of Nagas and Jojo, Drider Oviposition of Tamani)</li>");
    CView.text("<li> Smokescreen (Bee Oviposition of Basilisks)</li>");
    CView.text("<li> Radar (Oviposition of Sand Witches)</li>");
    CView.text("<li> OutlawVee (Bee Oviposition of Goo-Girls)</li>");
    CView.text("<li> Zeikfried (Editing this mess, Oviposition of Anemones)</li>");
    CView.text("<li> Woodrobin (Oviposition of Minotaurs)</li>");
    CView.text("<li> Posthuman (Oviposition of Ceraph Follower)</li>");
    CView.text("<li> Slywyn (Bee Oviposition of Gigantic PC Dick)</li>");
    CView.text("<li> Shaxarok (Drider Oviposition of Large Breasted Nipplecunts)</li>");
    CView.text("<li> Quiet Browser (Bee Oviposition of Urta)</li>");
    CView.text("<li> Bagpuss (Laying Eggs In Pure Amily)</li>");
    CView.text("<li> Eliria (Bee Laying Eggs in Bunny-Girls)</li>");
    CView.text("<li> Gardeford (Helia x Bimbo Sophie Threesomes)</li>");
    CView.text("</ul>");
    CView.text("\nIf I'm missing anyone, please contact me ASAP!  I have done a terrible job keeping the credits up to date!");
    return { next: mainMenu };
}
