import BreastRow from '../../Body/BreastRow';
import { FaceType } from '../../Body/Face';
import { SkinType } from '../../Body/Skin';
import { TongueType } from '../../Body/Tongue';
import Vagina from '../../Body/Vagina';
import { WingType } from '../../Body/Wings';
import Player from '../../Player/Player';

export default function customLeah(player: Player): void {
    player.setArmor(armors.LEATHRA);
    // 		if(!player.perks.has(PerkType.WizardsEndurance)) player.createPerk(PerkType.WizardsEndurance,30,0,0,0);
    player.setWeapon(weapons.W_STAFF);
    player.itemSlot1.setItemAndQty(consumables.B__BOOK, 1);
    player.itemSlot2.setItemAndQty(consumables.W__BOOK, 2);

    player.torso.chest.add(new BreastRow());
    player.torso.vaginas.add(new Vagina());
    player.torso.chest.get(0).rating = 4;
    player.torso.clit.length = .5;
    player.fertility = 10;
    player.gender = 2;
    player.torso.hips.rating = 8;
    player.torso.butt.rating = 8;
    player.stats.str = 15;
    player.stats.tou = 15;
    player.stats.spe = 18;
    player.stats.int = 17;
    player.stats.sens = 15;
    player.stats.lib = 15;
    player.stats.cor = 0;
    kGAMECLASS.notes = "No Notes Available.";
    player.stats.HP = kGAMECLASS.maxHP();
    player.torso.neck.head.hair.length = 13;
    player.skin.type = SkinType.PLAIN;
    player.torso.neck.head.face.type = FaceType.HUMAN;
    player.torso.neck.head.face.tongue.type = TongueType.HUMAN;
    player.femininity = 85;
    player.tone = 30;
    player.thickness = 50;
    player.skin.desc = "skin";
    player.skin.tone = "olive";
    player.torso.neck.head.hair.color = "black";
    player.torso.balls.quantity = 0;
    player.cumMultiplier = 1;
    player.torso.balls.size = 0;
    player.hoursSinceCum = 0;
    player.torso.clit.length = 0;
    player.torso.butt.looseness = 0;
    player.torso.butt.wetness = 0;
    player.torso.butt.fullness = 0;
    player.fertility = 5;
    player.stats.fatigue = 0;
    player.torso.neck.head.horns.amount = 0;
    player.tallness = 67;
    player.torso.wings.type = WingType.NONE;
    player.torso.wings.desc = "non-existant";
    player.tone = 30;
    player.thickness = 65;
}
