import { ArmType } from '../../Body/Arms';
import BreastRow from '../../Body/BreastRow';
import { EarType } from '../../Body/Ears';
import { FaceType } from '../../Body/Face';
import { HornType } from '../../Body/Horns';
import { LegType } from '../../Body/Legs';
import { SkinType } from '../../Body/Skin';
import Tail, { TailType } from '../../Body/Tail';
import { TongueType } from '../../Body/Tongue';
import Vagina, { VaginaWetness } from '../../Body/Vagina';
import { WingType } from '../../Body/Wings';
import DisplayText from '../../display/DisplayText';
import PerkFactory from '../../Effects/PerkFactory';
import { PerkType } from '../../Effects/PerkType';
import StatusAffectFactory from '../../Effects/StatusAffectFactory';
import { StatusAffectType } from '../../Effects/StatusAffectType';
import Player from '../../Player/Player';

export default function customVahdunbrii(player: Player): void {
    player.torso.chest.add(new BreastRow());
    player.torso.vaginas.add(new Vagina());
    player.torso.chest.get(0).rating = 3;
    player.torso.clit.length = .5;
    player.fertility = 10;
    player.gender = 2;
    player.torso.hips.rating = 6;
    player.torso.butt.rating = 6;
    player.stats.str = 15;
    player.stats.tou = 15;
    player.stats.spe = 18;
    player.stats.int = 17;
    player.stats.sens = 15;
    player.stats.lib = 15;
    player.stats.cor = 0;
    kGAMECLASS.notes = "No Notes Available.";
    player.stats.HP = kGAMECLASS.maxHP();
    player.torso.neck.head.hair.length = 10;
    player.skin.type = SkinType.PLAIN;
    player.torso.neck.head.face.type = FaceType.HUMAN;
    player.torso.neck.head.face.tongue.type = TongueType.HUMAN;
    player.femininity = 70;
    player.tone = 30;
    player.thickness = 50;
    player.skin.desc = "skin";
    player.skin.tone = "light";
    player.torso.neck.head.hair.color = "brown";
    player.torso.balls.quantity = 0;
    player.cumMultiplier = 1;
    player.torso.balls.size = 0;
    player.hoursSinceCum = 0;
    player.torso.clit.length = 0;
    player.torso.butt.looseness = 0;
    player.torso.butt.wetness = 0;
    player.torso.butt.fullness = 0;
    player.fertility = 5;
    player.stats.fatigue = 0;
    player.tallness = 67;
    player.torso.neck.head.ears.type = EarType.CAT;
    player.torso.hips.legs.type = LegType.CAT;
    player.torso.tails.add(new Tail(TailType.CAT));
    player.perks.add(PerkType.Incorporeality, 0, 0, 0, 0);
    player.torso.wings.type = WingType.FEATHERED_LARGE;
    player.torso.arms.type = ArmType.HARPY;
    player.torso.neck.head.horns.type = HornType.DRACONIC_X2;
    player.torso.neck.head.horns.amount = 4;
    player.torso.neck.head.face.type = FaceType.SPIDER_FANGS;
    player.torso.neck.head.hair.length = 69.2;
    player.torso.neck.head.hair.color = "dark blue";
    player.torso.neck.head.hair.type = 2;
    player.skin.adj = "smooth";
    player.skin.tone = "sanguine";
    player.tallness = 68;
    player.torso.hips.rating = 7;
    player.torso.butt.rating = 6;
    player.thickness = 4;
    player.tone = 98;
    player.torso.chest.get(0).rating = 3;
    player.torso.clit.length = 0.2;
    player.femininity = 85;
    // Beautiful Sword
    player.setWeapon(weapons.B_SWORD);
    player.setArmor(armors.SSARMOR);
    // Bow skill 100 (Sorry Kelt, I can't hear your insults over my mad Robin Hood skillz)
    player.statusAffects.add(StatusAffectType.Kelt, 100, 0, 0, 0); )
    player.createKeyItem("Bow", 0, 0, 0, 0);
    inventory.createStorage();
    inventory.createStorage();
    inventory.createStorage();
    inventory.createStorage();
    inventory.createStorage();
    inventory.createStorage();
    player.createKeyItem("Camp - Chest", 0, 0, 0, 0);
    player.createKeyItem("Equipment Rack - Weapons", 0, 0, 0, 0);
    Flags.list[FlagEnum.UNKNOWN_FLAG_NUMBER_00254] = 1;
    player.createKeyItem("Equipment Rack - Armor", 0, 0, 0, 0);
    Flags.list[FlagEnum.UNKNOWN_FLAG_NUMBER_00255] = 1;
    // (Flexibility), (Incorporeality), History: Religious, Dragonfire, Brood Mother, Magical Fertility, Wet Pussy, Tough, Strong, Fast, Smart, History: Scholar, History: Slacker, Strong Back, Strong Back 2: Stronger Harder
    player.perks.add(PerkType.Flexibility, 0, 0, 0, 0);
    player.perks.add(PerkType.HistoryReligious, 0, 0, 0, 0);
    player.perks.add(PerkType.Dragonfire, 0, 0, 0, 0);
    player.perks.add(PerkType.BroodMother, 0, 0, 0, 0);
    player.perks.add(PerkType.Fertile, 1.5, 0, 0, 0);
    player.torso.vaginas.get(0).wetness = VaginaWetness.WET;
    player.perks.add(PerkType.WetPussy, 2, 0, 0, 0);
    player.perks.add(PerkType.Tough, 0.25, 0, 0, 0);
    player.perks.add(PerkType.Strong, 0.25, 0, 0, 0);
    player.perks.add(PerkType.Fast, 0.25, 0, 0, 0);
    player.perks.add(PerkType.Smart, 0.25, 0, 0, 0);
    player.perks.add(PerkType.HistoryScholar, 0, 0, 0, 0);
    player.perks.add(PerkType.StrongBack, 0, 0, 0, 0);
    player.inventory.items.unlock();
    player.inventory.items.unlock();
    player.perks.add(PerkType.StrongBack2, 0, 0, 0, 0);
    player.perks.add(PerkType.HistorySlacker, 0, 0, 0, 0);
    player.stats.str += 4;
    player.stats.tou += 4;
    player.stats.int += 2;
    player.stats.spe += 2;
    player.inventory.gems += 300;
    DisplayText("You're something of a powerhouse, and you wager that between your odd mutations, power strong enough to threaten the village order, and talents, you're the natural choice to send through the portal.");
}
