import { CaninePepperType, CaninePepper } from './CaninePepper';
import { Consumable } from './Consumable';
import { ConsumableName } from './ConsumableName';
import { EggType, Eggs } from './Eggs';
import { HairDyeType, HairDye } from './HairDye';
import { Dictionary } from '../../../Engine/Utilities/Dictionary';
import { BeeHoney } from './BeeHoney';
import { BimboLiqueur } from './BimboLiqueur';
import { BlackCatBeer } from './BlackCatBeer';
import { BlackSpellbook } from './BlackSpellbook';
import { BroBrew } from './BroBrew';
import { CeruleanPotion } from './CeruleanPotion';
import { Coal } from './Coal';
import { DeBimbo } from './DeBimbo';
import { DragonEgg } from './DragonEgg';
import { Ectoplasm } from './Ectoplasm';
import { Equinum } from './Equinum';
import { FerretFruit } from './FerretFruit';
import { FishFillet } from './FishFillet';
import { FoxBerry } from './FoxBerry';
import { FoxJewel } from './FoxJewel';
import { GiantChocolateCupcake } from './GiantChocolateCupcake';
import { GoblinAle } from './GoblinAle';
import { GodsMead } from './GodsMead';
import { GoldenSeed } from './GoldenSeed';
import { GroPlus } from './GroPlus';
import { HairExtensionSerum } from './HairExtensionSerum';
import { HerbalContraceptive } from './HerbalContraceptive';
import { Hummus } from './Hummus';
import { ImpFood } from './ImpFood';
import { IncubusDraft } from './IncubusDraft';
import { IsabellaMilk } from './IsabellaMilk';
import { KangaFruit } from './KangaFruit';
import { KitsuneGift } from './KitsuneGift';
import { LaBova } from './LaBova';
import { Lactaid } from './Lactaid';
import { LustDraft } from './LustDraft';
import { LustStick } from './LustStick';
import { MarbleMilk } from './MarbleMilk';
import { MinotaurBlood } from './MinotaurBlood';
import { MinotaurCum } from './MinotaurCum';
import { MouseCocoa } from './MouseCocoa';
import { NeonPinkEgg } from './NeonPinkEgg';
import { NumbRock } from './NumbRock';
import { OvipositionElixir } from './OvipositionElixir';
import { PeppermintWhite } from './PeppermintWhite';
import { PhoukaWhiskey } from './PhoukaWhiskey';
import { PrincessPucker } from './PrincessPucker';
import { PurePearl } from './PurePearl';
import { PurityPeach } from './PurityPeach';
import { PurpleFruit } from './PurpleFruit';
import { Reducto } from './Reducto';
import { Reptilum } from './Reptilum';
import { RingtailFig } from './RingtailFig';
import { RizzaRoot } from './RizzaRoot';
import { ScholarsTea } from './ScholarsTea';
import { SensitivityDraft } from './SensitivityDraft';
import { SharkTooth } from './SharkTooth';
import { SheepMilk } from './SheepMilk';
import { ShriveledTentacle } from './ShriveledTentacle';
import { SnakeOil } from './SnakeOil';
import { SuccubiMilk } from './SuccubiMilk';
import { SuccubisDelight } from './SuccubisDelight';
import { SuccubisDream } from './SuccubisDream';
import { SweetGossamer } from './SweetGossamer';
import { TatteredScroll } from './TatteredScroll';
import { TrapOil } from './TrapOil';
import { VitalityTincture } from './VitalityTincture';
import { WetCloth } from './WetCloth';
import { WhiskerFruit } from './WhiskerFruit';
import { WhiteSpellbook } from './WhiteSpellbook';

export class ConsumableLib extends Dictionary<Consumable> {
    public constructor() {
        super();
        this.set(ConsumableName.BeeHoney, new BeeHoney(false, false));
        this.set(ConsumableName.BeeHoneyPure, new BeeHoney(true, false));
        this.set(ConsumableName.BeeHoneySpecial, new BeeHoney(false, true));
        this.set(ConsumableName.BimboLiqueur, new BimboLiqueur());
        this.set(ConsumableName.BlackCatBeer, new BlackCatBeer());
        this.set(ConsumableName.BlackSpellbook, new BlackSpellbook());
        this.set(ConsumableName.BroBrew, new BroBrew());
        this.set(ConsumableName.CaninePepper, new CaninePepper(CaninePepperType.Normal));
        this.set(ConsumableName.CaninePepperLarge, new CaninePepper(CaninePepperType.Oversized));
        this.set(ConsumableName.CaninePepperDouble, new CaninePepper(CaninePepperType.Double));
        this.set(ConsumableName.CaninePepperBlack, new CaninePepper(CaninePepperType.Black));
        this.set(ConsumableName.CaninePepperKnotty, new CaninePepper(CaninePepperType.Knotty));
        this.set(ConsumableName.CaninePepperBulbous, new CaninePepper(CaninePepperType.Bulbous));
        this.set(ConsumableName.CeruleanPotion, new CeruleanPotion());
        this.set(ConsumableName.Coal, new Coal());
        this.set(ConsumableName.DeBimbo, new DeBimbo());
        this.set(ConsumableName.DragonEgg, new DragonEgg());
        this.set(ConsumableName.Ectoplasm, new Ectoplasm());
        this.set(ConsumableName.EggBlack, new Eggs(EggType.Black, false));
        this.set(ConsumableName.EggBlue, new Eggs(EggType.Blue, false));
        this.set(ConsumableName.EggBrown, new Eggs(EggType.Brown, false));
        this.set(ConsumableName.EggPink, new Eggs(EggType.Pink, false));
        this.set(ConsumableName.EggPurple, new Eggs(EggType.Purple, false));
        this.set(ConsumableName.EggWhite, new Eggs(EggType.White, false));
        this.set(ConsumableName.LargeEggBlack, new Eggs(EggType.Black, true));
        this.set(ConsumableName.LargeEggBlue, new Eggs(EggType.Blue, true));
        this.set(ConsumableName.LargeEggBrown, new Eggs(EggType.Brown, true));
        this.set(ConsumableName.LargeEggPink, new Eggs(EggType.Pink, true));
        this.set(ConsumableName.LargeEggPurple, new Eggs(EggType.Purple, true));
        this.set(ConsumableName.LargeEggWhite, new Eggs(EggType.White, true));
        this.set(ConsumableName.Equinum, new Equinum());
        this.set(ConsumableName.FerretFruit, new FerretFruit());
        this.set(ConsumableName.FishFillet, new FishFillet());
        this.set(ConsumableName.FoxBerry, new FoxBerry(false));
        this.set(ConsumableName.FoxBerryEnhanced, new FoxBerry(true));
        this.set(ConsumableName.FoxJewel, new FoxJewel(false));
        this.set(ConsumableName.FoxJewelEnhanced, new FoxJewel(true));
        this.set(ConsumableName.GiantChocolateCupcake, new GiantChocolateCupcake());
        this.set(ConsumableName.GoblinAle, new GoblinAle());
        this.set(ConsumableName.GodsMead, new GodsMead());
        this.set(ConsumableName.GoldenSeed, new GoldenSeed(false));
        this.set(ConsumableName.GoldenSeedEnhanced, new GoldenSeed(true));
        this.set(ConsumableName.GroPlus, new GroPlus());
        this.set(ConsumableName.HairDyeAuburn, new HairDye(HairDyeType.Auburn));
        this.set(ConsumableName.HairDyeBlack, new HairDye(HairDyeType.Black));
        this.set(ConsumableName.HairDyeBlonde, new HairDye(HairDyeType.Blonde));
        this.set(ConsumableName.HairDyeBrightOrange, new HairDye(HairDyeType.BrightOrange));
        this.set(ConsumableName.HairDyeBrown, new HairDye(HairDyeType.Brown));
        this.set(ConsumableName.HairDyeDarkBlue, new HairDye(HairDyeType.DarkBlue));
        this.set(ConsumableName.HairDyeGray, new HairDye(HairDyeType.Gray));
        this.set(ConsumableName.HairDyeGreen, new HairDye(HairDyeType.Green));
        this.set(ConsumableName.HairDyeNeonPink, new HairDye(HairDyeType.NeonPink));
        this.set(ConsumableName.HairDyePurple, new HairDye(HairDyeType.Purple));
        this.set(ConsumableName.HairDyeRed, new HairDye(HairDyeType.Red));
        this.set(ConsumableName.HairDyeWhite, new HairDye(HairDyeType.White));
        this.set(ConsumableName.HairExtensionSerum, new HairExtensionSerum());
        this.set(ConsumableName.HerbalContraceptive, new HerbalContraceptive());
        this.set(ConsumableName.Hummus, new Hummus());
        this.set(ConsumableName.ImpFood, new ImpFood());
        this.set(ConsumableName.IncubusDraftPure, new IncubusDraft(false));
        this.set(ConsumableName.IncubusDraft, new IncubusDraft(true));
        this.set(ConsumableName.IsabellaMilk, new IsabellaMilk());
        this.set(ConsumableName.KangaFruit, new KangaFruit(false));
        this.set(ConsumableName.KangaFruitEnhanced, new KangaFruit(true));
        this.set(ConsumableName.KitsuneGift, new KitsuneGift());
        this.set(ConsumableName.LaBovaPure, new LaBova(false, false));
        this.set(ConsumableName.LaBovaEnhanced, new LaBova(true, false));
        this.set(ConsumableName.LaBova, new LaBova(false, true));
        this.set(ConsumableName.Lactaid, new Lactaid());
        this.set(ConsumableName.LustDraft, new LustDraft(false));
        this.set(ConsumableName.LustDraftEnhanced, new LustDraft(true));
        this.set(ConsumableName.LustStick, new LustStick());
        this.set(ConsumableName.MarbleMilk, new MarbleMilk());
        this.set(ConsumableName.MinotaurBlood, new MinotaurBlood());
        this.set(ConsumableName.MinotaurCum, new MinotaurCum());
        this.set(ConsumableName.MouseCocoa, new MouseCocoa());
        this.set(ConsumableName.NeonPinkEgg, new NeonPinkEgg(false));
        this.set(ConsumableName.NeonPinkEggPreg, new NeonPinkEgg(true));
        this.set(ConsumableName.NumbRock, new NumbRock());
        this.set(ConsumableName.OvipositionElixir, new OvipositionElixir());
        this.set(ConsumableName.PeppermintWhite, new PeppermintWhite());
        this.set(ConsumableName.PhoukaWhiskey, new PhoukaWhiskey());
        this.set(ConsumableName.PrincessPucker, new PrincessPucker());
        this.set(ConsumableName.PurePearl, new PurePearl());
        this.set(ConsumableName.PurityPeach, new PurityPeach());
        this.set(ConsumableName.PurpleFruit, new PurpleFruit());
        this.set(ConsumableName.Reducto, new Reducto());
        this.set(ConsumableName.Reptilum, new Reptilum());
        this.set(ConsumableName.RingtailFig, new RingtailFig());
        this.set(ConsumableName.RizzaRoot, new RizzaRoot());
        this.set(ConsumableName.ScholarsTea, new ScholarsTea());
        this.set(ConsumableName.SensitivityDraft, new SensitivityDraft());
        this.set(ConsumableName.SharkTooth, new SharkTooth(false));
        this.set(ConsumableName.SharkToothEnhanced, new SharkTooth(true));
        this.set(ConsumableName.SheepMilk, new SheepMilk());
        this.set(ConsumableName.ShriveledTentacle, new ShriveledTentacle());
        this.set(ConsumableName.SnakeOil, new SnakeOil());
        this.set(ConsumableName.SuccubiMilkPure, new SuccubiMilk(false));
        this.set(ConsumableName.SuccubiMilk, new SuccubiMilk(true));
        this.set(ConsumableName.SuccubisDelightPure, new SuccubisDelight(false));
        this.set(ConsumableName.SuccubisDelight, new SuccubisDelight(true));
        this.set(ConsumableName.SuccubisDream, new SuccubisDream());
        this.set(ConsumableName.BlackGossamer, new SweetGossamer(false));
        this.set(ConsumableName.SweetGossamer, new SweetGossamer(true));
        this.set(ConsumableName.TatteredScroll, new TatteredScroll());
        this.set(ConsumableName.TrapOil, new TrapOil());
        this.set(ConsumableName.VitalityTincture, new VitalityTincture());
        this.set(ConsumableName.WetCloth, new WetCloth());
        this.set(ConsumableName.WhiskerFruit, new WhiskerFruit());
        this.set(ConsumableName.WhiteSpellbook, new WhiteSpellbook());
        // this.set(ConsumableName.WingStick, new WingStick());
    }
}
