import { Character } from '../Character/Character';
import { Desc } from '../Descriptors/Descriptors';

// Lookup dictionary for converting any single argument brackets into it's corresponding string
// basically [armor] results in the "[armor]" segment of the string being replaced with the
// results of the corresponding anonymous function, in this case: function():* {return player.inventory.armorSlot.equipment.displayName;}
// tags not present in the singleArgConverters object return an error message.
//

const singleArgConverters =
    {
        agility: (char: Character) => "[Agility]",
        armor: (char: Character) => char.inventory.equipment.armor.displayName,
        armorname: (char: Character) => char.inventory.equipment.armor.displayName,
        ass: (char: Character) => describeButt(char),
        asshole: (char: Character) => describeButthole(char.body.butt),
        balls: (char: Character) => describeBalls(true, true, char),
        boyfriend: (char: Character) => mf(char, "boyfriend", "girlfriend"),
        butt: (char: Character) => describeButt(char),
        butthole: (char: Character) => describeButthole(char.body.butt),
        chest: (char: Character) => describeChest(char),
        clit: (char: Character) => describeClit(char),
        cock: (char: Character) => describeCock(char, char.body.cocks.get(0)),
        cockhead: (char: Character) => describeCockHead(char.body.cocks.get(0)),
        cocks: (char: Character) => describeMultiCockShort(char),
        cunt: (char: Character) => describeVagina(char, char.body.vaginas.get(0)),
        eachcock: (char: Character) => describeMultiCockSimpleOne(char),
        evade: (char: Character) => "[Evade]",
        face: (char: Character) => describeFace(char),
        feet: (char: Character) => describeFeet(char),
        foot: (char: Character) => describeFoot(char),
        fullchest: (char: Character) => describeAllBreasts(char),
        hair: (char: Character) => describeHair(char),
        hairorfur: (char: Character) => hairOrFur(char),
        he: (char: Character) => char.desc.subjectivePronoun,
        // he2: (char: Character) => char2.mf("he", "she"),
        him: (char: Character) => char.desc.objectivePronoun,
        // him2: (char: Character) => char2.mf("him", "her"),
        himself: (char: Character) => mf(char, "himself", "herself"),
        herself: (char: Character) => mf(char, "himself", "herself"),
        hips: (char: Character) => describeHips(char),
        his: (char: Character) => char.desc.possessivePronoun,
        // his2: (char: Character) => char2.mf("his", "her"),
        leg: (char: Character) => describeLeg(char),
        legs: (char: Character) => describeLegs(char),
        man: (char: Character) => mf(char, "man", "woman"),
        men: (char: Character) => mf(char, "men", "women"),
        master: (char: Character) => mf(char, "master", "mistress"),
        misdirection: (char: Character) => "[Misdirection]",
        multicock: (char: Character) => describeMultiCockShort(char),
        multicockdescriptlight: (char: Character) => describeMultiCockShort(char),
        name: (char: Character) => char.desc.short,
        nipple: (char: Character) => describeNipple(char, char.body.chest.get(0)),
        nipples: (char: Character) => describeNipple(char, char.body.chest.get(0)) + "s",
        onecock: (char: Character) => describeMultiCockSimpleOne(char),
        pg: (char: Character) => "\n\n",
        pussy: (char: Character) => describeVagina(char, char.body.vaginas.get(0)),
        race: (char: Character) => describeRace(char),
        sack: (char: Character) => describeSack(char),
        sheath: (char: Character) => describeCockSheath(char.body.cocks.get(0)),
        skin: (char: Character) => skin(char),
        skinfurscales: (char: Character) => skinFurScales(char),
        // teasetext: (char: Character) => teaseText(),
        tongue: (char: Character) => describeTongue(char.body.face.tongue.type),
        vag: (char: Character) => describeVagina(char, char.body.vaginas.get(0)),
        vagina: (char: Character) => describeVagina(char, char.body.vaginas.get(0)),
        vagorass: (char: Character) => (char.body.vaginas.length > 0 ? describeVagina(char, char.body.vaginas.get(0)) : describeButthole(char.body.butt)),
        weapon: (char: Character) => char.inventory.equipment.weapon.displayName,
        weaponname: (char: Character) => char.inventory.equipment.weapon.displayName,

        // latexyname: (char: Character) => Flags.list[FlagEnum.GOO_NAME],
        // bathgirlname: (char: Character) => Flags.list[FlagEnum.MILK_NAME],
        cockplural: (char: Character) => (char.body.cocks.length === 1) ? "cock" : "cocks",
        dickplural: (char: Character) => (char.body.cocks.length === 1) ? "dick" : "dicks",
        headplural: (char: Character) => (char.body.cocks.length === 1) ? "head" : "heads",
        prickplural: (char: Character) => (char.body.cocks.length === 1) ? "prick" : "pricks",
        boy: (char: Character) => boyGirl(char.gender),
        guy: (char: Character) => guyGirl(char.gender),
        // wings: (char: Character) => wingsDescript(),
        // tail: (char: Character) => tailDescript(),
        // onetail: (char: Character) => oneTailDescript()
    };
