import { StatusEffectDesc } from './StatusEffect';
import { StatusEffectType } from './StatusEffectType';
import { Dictionary } from '../../Engine/Utilities/Dictionary';

export const StatusEffectDescLib = new Dictionary<StatusEffectType, StatusEffectDesc>();
StatusEffectDescLib.set(StatusEffectType.AllNaturalOnaholeUsed, new StatusEffectDesc(StatusEffectType.AllNaturalOnaholeUsed, "AllNaturalOnaholeUsed", "all-natural onahole used", ""));
StatusEffectDescLib.set(StatusEffectType.AteEgg, new StatusEffectDesc(StatusEffectType.AteEgg, "AteEgg", "ateEgg", ""));
StatusEffectDescLib.set(StatusEffectType.AnemoneArousal, new StatusEffectDesc(StatusEffectType.AnemoneArousal, "AnemoneArousal", "Anemone Arousal", ""));
StatusEffectDescLib.set(StatusEffectType.BimboChampagne, new StatusEffectDesc(StatusEffectType.BimboChampagne, "BimboChampagne", "Bimbo Champagne", ""));
StatusEffectDescLib.set(StatusEffectType.Birthed, new StatusEffectDesc(StatusEffectType.Birthed, "Birthed", "Birthed", ""));
StatusEffectDescLib.set(StatusEffectType.BirthedImps, new StatusEffectDesc(StatusEffectType.BirthedImps, "BirthedImps", "Birthed Imps", ""));
StatusEffectDescLib.set(StatusEffectType.BlackCatBeer, new StatusEffectDesc(StatusEffectType.BlackCatBeer, "BlackCatBeer", "Black Cat Beer", ""));
StatusEffectDescLib.set(StatusEffectType.BlackNipples, new StatusEffectDesc(StatusEffectType.BlackNipples, "BlackNipples", "Black Nipples", ""));
StatusEffectDescLib.set(StatusEffectType.BlowjobOn, new StatusEffectDesc(StatusEffectType.BlowjobOn, "BlowjobOn", "BlowjobOn", ""));
StatusEffectDescLib.set(StatusEffectType.BoatDiscovery, new StatusEffectDesc(StatusEffectType.BoatDiscovery, "BoatDiscovery", "Boat Discovery", ""));
StatusEffectDescLib.set(StatusEffectType.BonusACapacity, new StatusEffectDesc(StatusEffectType.BonusACapacity, "BonusACapacity", "Bonus aCapacity", ""));
StatusEffectDescLib.set(StatusEffectType.BonusVCapacity, new StatusEffectDesc(StatusEffectType.BonusVCapacity, "BonusVCapacity", "Bonus vCapacity", ""));
StatusEffectDescLib.set(StatusEffectType.BottledMilk, new StatusEffectDesc(StatusEffectType.BottledMilk, "BottledMilk", "Bottled Milk", ""));
StatusEffectDescLib.set(StatusEffectType.BreastsMilked, new StatusEffectDesc(StatusEffectType.BreastsMilked, "BreastsMilked", "Breasts Milked", ""));
StatusEffectDescLib.set(StatusEffectType.BSwordBroken, new StatusEffectDesc(StatusEffectType.BSwordBroken, "BSwordBroken", "BSwordBroken", ""));
StatusEffectDescLib.set(StatusEffectType.BuiltMilker, new StatusEffectDesc(StatusEffectType.BuiltMilker, "BuiltMilker", "BUILT: Milker", ""));
StatusEffectDescLib.set(StatusEffectType.BurpChanged, new StatusEffectDesc(StatusEffectType.BurpChanged, "BurpChanged", "Burp Changed", ""));
StatusEffectDescLib.set(StatusEffectType.ButtStretched, new StatusEffectDesc(StatusEffectType.ButtStretched, "ButtStretched", "ButtStretched", ""));
StatusEffectDescLib.set(StatusEffectType.CampAnemoneTrigger, new StatusEffectDesc(StatusEffectType.CampAnemoneTrigger, "CampAnemoneTrigger", "Camp Anemone Trigger", ""));
StatusEffectDescLib.set(StatusEffectType.CampMarble, new StatusEffectDesc(StatusEffectType.CampMarble, "CampMarble", "Camp Marble", ""));
StatusEffectDescLib.set(StatusEffectType.CampRathazul, new StatusEffectDesc(StatusEffectType.CampRathazul, "CampRathazul", "Camp Rathazul", ""));
StatusEffectDescLib.set(StatusEffectType.ClaraCombatRounds, new StatusEffectDesc(StatusEffectType.ClaraCombatRounds, "ClaraCombatRounds", "Clara Combat Rounds", ""));
StatusEffectDescLib.set(StatusEffectType.ClaraFoughtInCamp, new StatusEffectDesc(StatusEffectType.ClaraFoughtInCamp, "ClaraFoughtInCamp", "Clara Fought In Camp", ""));
StatusEffectDescLib.set(StatusEffectType.CockPumped, new StatusEffectDesc(StatusEffectType.CockPumped, "CockPumped", "Cock Pumped", ""));
StatusEffectDescLib.set(StatusEffectType.Contraceptives, new StatusEffectDesc(StatusEffectType.Contraceptives, "Contraceptives", "Contraceptives", ""));
StatusEffectDescLib.set(StatusEffectType.CuntStretched, new StatusEffectDesc(StatusEffectType.CuntStretched, "CuntStretched", "CuntStretched", ""));
StatusEffectDescLib.set(StatusEffectType.DefenseCanopy, new StatusEffectDesc(StatusEffectType.DefenseCanopy, "DefenseCanopy", "Defense: Canopy", ""));
StatusEffectDescLib.set(StatusEffectType.DeluxeOnaholeUsed, new StatusEffectDesc(StatusEffectType.DeluxeOnaholeUsed, "DeluxeOnaholeUsed", "deluxe onahole used", ""));
StatusEffectDescLib.set(StatusEffectType.DogWarning, new StatusEffectDesc(StatusEffectType.DogWarning, "DogWarning", "dog warning", ""));
StatusEffectDescLib.set(StatusEffectType.DragonBreathBoost, new StatusEffectDesc(StatusEffectType.DragonBreathBoost, "DragonBreathBoost", "Dragon Breath Boost", ""));
StatusEffectDescLib.set(StatusEffectType.DragonBreathCooldown, new StatusEffectDesc(StatusEffectType.DragonBreathCooldown, "DragonBreathCooldown", "Dragon Breath Cooldown", ""));
StatusEffectDescLib.set(StatusEffectType.DungeonShutDown, new StatusEffectDesc(StatusEffectType.DungeonShutDown, "DungeonShutDown", "DungeonShutDown", ""));
StatusEffectDescLib.set(StatusEffectType.Dysfunction, new StatusEffectDesc(StatusEffectType.Dysfunction, "Dysfunction", "dysfunction", ""));
StatusEffectDescLib.set(StatusEffectType.Edryn, new StatusEffectDesc(StatusEffectType.Edryn, "Edryn", "Edryn", ""));
StatusEffectDescLib.set(StatusEffectType.Eggchest, new StatusEffectDesc(StatusEffectType.Eggchest, "Eggchest", "eggchest", ""));
StatusEffectDescLib.set(StatusEffectType.Eggs, new StatusEffectDesc(StatusEffectType.Eggs, "Eggs", "eggs", ""));
StatusEffectDescLib.set(StatusEffectType.EmberFuckCooldown, new StatusEffectDesc(StatusEffectType.EmberFuckCooldown, "EmberFuckCooldown", "ember fuck cooldown", ""));
StatusEffectDescLib.set(StatusEffectType.EmberNapping, new StatusEffectDesc(StatusEffectType.EmberNapping, "EmberNapping", "Ember Napping", ""));
StatusEffectDescLib.set(StatusEffectType.EverRapedJojo, new StatusEffectDesc(StatusEffectType.EverRapedJojo, "EverRapedJojo", "Ever Raped Jojo", ""));
StatusEffectDescLib.set(StatusEffectType.Exgartuan, new StatusEffectDesc(StatusEffectType.Exgartuan, "Exgartuan", "Exgartuan", ""));
StatusEffectDescLib.set(StatusEffectType.ExploredDeepwoods, new StatusEffectDesc(StatusEffectType.ExploredDeepwoods, "ExploredDeepwoods", "exploredDeepwoods", ""));
StatusEffectDescLib.set(StatusEffectType.FactoryOmnibusDefeated, new StatusEffectDesc(StatusEffectType.FactoryOmnibusDefeated, "FactoryOmnibusDefeated", "FactoryOmnibusDefeated", ""));
StatusEffectDescLib.set(StatusEffectType.FactoryOverload, new StatusEffectDesc(StatusEffectType.FactoryOverload, "FactoryOverload", "FactoryOverload", ""));
StatusEffectDescLib.set(StatusEffectType.FactoryIncubusDefeated, new StatusEffectDesc(StatusEffectType.FactoryIncubusDefeated, "FactoryIncubusDefeated", "FactoryIncubusDefeated", ""));
StatusEffectDescLib.set(StatusEffectType.FactorySuccubusDefeated, new StatusEffectDesc(StatusEffectType.FactorySuccubusDefeated, "FactorySuccubusDefeated", "FactorySuccubusDefeated", ""));
StatusEffectDescLib.set(StatusEffectType.FaerieFemFuck, new StatusEffectDesc(StatusEffectType.FaerieFemFuck, "FaerieFemFuck", "Faerie Fem Fuck", ""));
StatusEffectDescLib.set(StatusEffectType.FaerieFucked, new StatusEffectDesc(StatusEffectType.FaerieFucked, "FaerieFucked", "Faerie Fucked", ""));
StatusEffectDescLib.set(StatusEffectType.FappedGenderless, new StatusEffectDesc(StatusEffectType.FappedGenderless, "FappedGenderless", "fapped genderless", ""));
StatusEffectDescLib.set(StatusEffectType.Feeder, new StatusEffectDesc(StatusEffectType.Feeder, "Feeder", "Feeder", ""));
StatusEffectDescLib.set(StatusEffectType.Fertilized, new StatusEffectDesc(StatusEffectType.Fertilized, "Fertilized", "Fertilized", ""));
StatusEffectDescLib.set(StatusEffectType.FetishOn, new StatusEffectDesc(StatusEffectType.FetishOn, "FetishOn", "fetishON", ""));
StatusEffectDescLib.set(StatusEffectType.FoundFactory, new StatusEffectDesc(StatusEffectType.FoundFactory, "FoundFactory", "Found Factory", ""));
StatusEffectDescLib.set(StatusEffectType.FuckedMarble, new StatusEffectDesc(StatusEffectType.FuckedMarble, "FuckedMarble", "FuckedMarble", ""));
StatusEffectDescLib.set(StatusEffectType.Goojob, new StatusEffectDesc(StatusEffectType.Goojob, "Goojob", "GOOJOB", ""));
StatusEffectDescLib.set(StatusEffectType.GooStuffed, new StatusEffectDesc(StatusEffectType.GooStuffed, "GooStuffed", "gooStuffed", ""));
StatusEffectDescLib.set(StatusEffectType.Groundpound, new StatusEffectDesc(StatusEffectType.Groundpound, "Groundpound", "Groundpound", ""));
StatusEffectDescLib.set(StatusEffectType.HairdresserMeeting, new StatusEffectDesc(StatusEffectType.HairdresserMeeting, "HairdresserMeeting", "hairdresser meeting", ""));
StatusEffectDescLib.set(StatusEffectType.Hangover, new StatusEffectDesc(StatusEffectType.Hangover, "Hangover", "Hangover", ""));
StatusEffectDescLib.set(StatusEffectType.Heat, new StatusEffectDesc(StatusEffectType.Heat, "Heat", "heat", ""));
StatusEffectDescLib.set(StatusEffectType.HorseWarning, new StatusEffectDesc(StatusEffectType.HorseWarning, "HorseWarning", "horse warning", ""));
StatusEffectDescLib.set(StatusEffectType.ImmolationSpell, new StatusEffectDesc(StatusEffectType.ImmolationSpell, "ImmolationSpell", "Immolation Spell", ""));
StatusEffectDescLib.set(StatusEffectType.ImpGangBang, new StatusEffectDesc(StatusEffectType.ImpGangBang, "ImpGangBang", "Imp GangBang", ""));
StatusEffectDescLib.set(StatusEffectType.IncubusBribed, new StatusEffectDesc(StatusEffectType.IncubusBribed, "IncubusBribed", "IncubusBribed", ""));
StatusEffectDescLib.set(StatusEffectType.Infested, new StatusEffectDesc(StatusEffectType.Infested, "Infested", "infested", ""));
StatusEffectDescLib.set(StatusEffectType.IzmaBlowing, new StatusEffectDesc(StatusEffectType.IzmaBlowing, "IzmaBlowing", "IzmaBlowing", ""));
StatusEffectDescLib.set(StatusEffectType.IzumisPipeSmoke, new StatusEffectDesc(StatusEffectType.IzumisPipeSmoke, "IzumisPipeSmoke", "Izumis Pipe Smoke", ""));
StatusEffectDescLib.set(StatusEffectType.JerkingIzma, new StatusEffectDesc(StatusEffectType.JerkingIzma, "JerkingIzma", "JerkingIzma", ""));
StatusEffectDescLib.set(StatusEffectType.Jizzpants, new StatusEffectDesc(StatusEffectType.Jizzpants, "Jizzpants", "Jizzpants", ""));
StatusEffectDescLib.set(StatusEffectType.JojoMeditationCount, new StatusEffectDesc(StatusEffectType.JojoMeditationCount, "JojoMeditationCount", "Jojo Meditation Count", ""));
StatusEffectDescLib.set(StatusEffectType.JojoNightWatch, new StatusEffectDesc(StatusEffectType.JojoNightWatch, "JojoNightWatch", "JojoNightWatch", ""));
StatusEffectDescLib.set(StatusEffectType.JojoTFOffer, new StatusEffectDesc(StatusEffectType.JojoTFOffer, "JojoTFOffer", "JojoTFOffer", ""));
StatusEffectDescLib.set(StatusEffectType.Kelt, new StatusEffectDesc(StatusEffectType.Kelt, "Kelt", "Kelt", ""));
StatusEffectDescLib.set(StatusEffectType.KeltBJ, new StatusEffectDesc(StatusEffectType.KeltBJ, "KeltBJ", "KeltBJ", ""));
StatusEffectDescLib.set(StatusEffectType.KeltBadEndWarning, new StatusEffectDesc(StatusEffectType.KeltBadEndWarning, "KeltBadEndWarning", "Kelt Bad End Warning", ""));
StatusEffectDescLib.set(StatusEffectType.KeltOff, new StatusEffectDesc(StatusEffectType.KeltOff, "KeltOff", "KeltOff", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsArouse, new StatusEffectDesc(StatusEffectType.KnowsArouse, "KnowsArouse", "Knows Arouse", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsBlind, new StatusEffectDesc(StatusEffectType.KnowsBlind, "KnowsBlind", "Knows Blind", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsCharge, new StatusEffectDesc(StatusEffectType.KnowsCharge, "KnowsCharge", "Knows Charge", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsHeal, new StatusEffectDesc(StatusEffectType.KnowsHeal, "KnowsHeal", "Knows Heal", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsMight, new StatusEffectDesc(StatusEffectType.KnowsMight, "KnowsMight", "Knows Might", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsWhitefire, new StatusEffectDesc(StatusEffectType.KnowsWhitefire, "KnowsWhitefire", "Knows Whitefire", ""));
StatusEffectDescLib.set(StatusEffectType.LactationEndurance, new StatusEffectDesc(StatusEffectType.LactationEndurance, "LactationEndurance", "Lactation Endurance", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduction, new StatusEffectDesc(StatusEffectType.LactationReduction, "LactationReduction", "Lactation Reduction", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduc0, new StatusEffectDesc(StatusEffectType.LactationReduc0, "LactationReduc0", "Lactation Reduc0", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduc1, new StatusEffectDesc(StatusEffectType.LactationReduc1, "LactationReduc1", "Lactation Reduc1", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduc2, new StatusEffectDesc(StatusEffectType.LactationReduc2, "LactationReduc2", "Lactation Reduc2", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduc3, new StatusEffectDesc(StatusEffectType.LactationReduc3, "LactationReduc3", "Lactation Reduc3", ""));
StatusEffectDescLib.set(StatusEffectType.LootEgg, new StatusEffectDesc(StatusEffectType.LootEgg, "LootEgg", "lootEgg", ""));
StatusEffectDescLib.set(StatusEffectType.LostVillagerSpecial, new StatusEffectDesc(StatusEffectType.LostVillagerSpecial, "LostVillagerSpecial", "lostVillagerSpecial", ""));
StatusEffectDescLib.set(StatusEffectType.LustStick, new StatusEffectDesc(StatusEffectType.LustStick, "Luststick", "Luststick", ""));
StatusEffectDescLib.set(StatusEffectType.LustStickApplied, new StatusEffectDesc(StatusEffectType.LustStickApplied, "LustStickApplied", "Lust Stick Applied", ""));
StatusEffectDescLib.set(StatusEffectType.LustyTongue, new StatusEffectDesc(StatusEffectType.LustyTongue, "LustyTongue", "LustyTongue", ""));
StatusEffectDescLib.set(StatusEffectType.MalonVisitedPostAddiction, new StatusEffectDesc(StatusEffectType.MalonVisitedPostAddiction, "MalonVisitedPostAddiction", "Malon Visited Post Addiction", ""));
StatusEffectDescLib.set(StatusEffectType.MaraeComplete, new StatusEffectDesc(StatusEffectType.MaraeComplete, "MaraeComplete", "Marae Complete", ""));
StatusEffectDescLib.set(StatusEffectType.MaraesLethicite, new StatusEffectDesc(StatusEffectType.MaraesLethicite, "MaraesLethicite", "Marae's Lethicite", ""));
StatusEffectDescLib.set(StatusEffectType.MaraesQuestStart, new StatusEffectDesc(StatusEffectType.MaraesQuestStart, "MaraesQuestStart", "Marae's Quest Start", ""));
StatusEffectDescLib.set(StatusEffectType.Marble, new StatusEffectDesc(StatusEffectType.Marble, "Marble", "Marble", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleHasItem, new StatusEffectDesc(StatusEffectType.MarbleHasItem, "MarbleHasItem", "MarbleHasItem", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleItemCooldown, new StatusEffectDesc(StatusEffectType.MarbleItemCooldown, "MarbleItemCooldown", "MarbleItemCooldown", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleRapeAttempted, new StatusEffectDesc(StatusEffectType.MarbleRapeAttempted, "MarbleRapeAttempted", "Marble Rape Attempted", ""));
StatusEffectDescLib.set(StatusEffectType.MarblesMilk, new StatusEffectDesc(StatusEffectType.MarblesMilk, "MarblesMilk", "Marbles Milk", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleSpecials, new StatusEffectDesc(StatusEffectType.MarbleSpecials, "MarbleSpecials", "MarbleSpecials", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleWithdrawl, new StatusEffectDesc(StatusEffectType.MarbleWithdrawl, "MarbleWithdrawl", "MarbleWithdrawl", ""));
StatusEffectDescLib.set(StatusEffectType.Meditated, new StatusEffectDesc(StatusEffectType.Meditated, "Meditated", "Meditated", ""));
StatusEffectDescLib.set(StatusEffectType.MeanToNaga, new StatusEffectDesc(StatusEffectType.MeanToNaga, "MeanToNaga", "MeanToNaga", ""));
StatusEffectDescLib.set(StatusEffectType.MeetWanderer, new StatusEffectDesc(StatusEffectType.MeetWanderer, "MeetWanderer", "meet wanderer", ""));
StatusEffectDescLib.set(StatusEffectType.MetCorruptMarae, new StatusEffectDesc(StatusEffectType.MetCorruptMarae, "MetCorruptMarae", "Met Corrupt Marae", ""));
StatusEffectDescLib.set(StatusEffectType.MetMarae, new StatusEffectDesc(StatusEffectType.MetMarae, "MetMarae", "Met Marae", ""));
StatusEffectDescLib.set(StatusEffectType.MetRathazul, new StatusEffectDesc(StatusEffectType.MetRathazul, "MetRathazul", "metRathazul", ""));
StatusEffectDescLib.set(StatusEffectType.MetWorms, new StatusEffectDesc(StatusEffectType.MetWorms, "MetWorms", "metWorms", ""));
StatusEffectDescLib.set(StatusEffectType.MetWhitney, new StatusEffectDesc(StatusEffectType.MetWhitney, "MetWhitney", "Met Whitney", ""));
StatusEffectDescLib.set(StatusEffectType.Milked, new StatusEffectDesc(StatusEffectType.Milked, "Milked", "Milked", ""));
StatusEffectDescLib.set(StatusEffectType.MinoPlusCowgirl, new StatusEffectDesc(StatusEffectType.MinoPlusCowgirl, "MinoPlusCowgirl", "Mino + Cowgirl", ""));
StatusEffectDescLib.set(StatusEffectType.Naga, new StatusEffectDesc(StatusEffectType.Naga, "Naga", "Naga", ""));
StatusEffectDescLib.set(StatusEffectType.NakedOn, new StatusEffectDesc(StatusEffectType.NakedOn, "NakedOn", "NakedOn", ""));
StatusEffectDescLib.set(StatusEffectType.NoJojo, new StatusEffectDesc(StatusEffectType.NoJojo, "NoJojo", "noJojo", ""));
StatusEffectDescLib.set(StatusEffectType.NoMoreMarble, new StatusEffectDesc(StatusEffectType.NoMoreMarble, "NoMoreMarble", "No More Marble", ""));
StatusEffectDescLib.set(StatusEffectType.Oswald, new StatusEffectDesc(StatusEffectType.Oswald, "Oswald", "Oswald", ""));
StatusEffectDescLib.set(StatusEffectType.PlainOnaholeUsed, new StatusEffectDesc(StatusEffectType.PlainOnaholeUsed, "PlainOnaholeUsed", "plain onahole used", ""));
StatusEffectDescLib.set(StatusEffectType.PhoukaWhiskeyAffect, new StatusEffectDesc(StatusEffectType.PhoukaWhiskeyAffect, "PhoukaWhiskeyAffect", "PhoukaWhiskeyAffect", ""));
StatusEffectDescLib.set(StatusEffectType.PostAkbalSubmission, new StatusEffectDesc(StatusEffectType.PostAkbalSubmission, "PostAkbalSubmission", "Post Akbal Submission", ""));
StatusEffectDescLib.set(StatusEffectType.PostAnemoneBeatdown, new StatusEffectDesc(StatusEffectType.PostAnemoneBeatdown, "PostAnemoneBeatdown", "Post Anemone Beatdown", ""));
StatusEffectDescLib.set(StatusEffectType.PureCampJojo, new StatusEffectDesc(StatusEffectType.PureCampJojo, "PureCampJojo", "PureCampJojo", ""));
StatusEffectDescLib.set(StatusEffectType.RathazulArmor, new StatusEffectDesc(StatusEffectType.RathazulArmor, "RathazulArmor", "RathazulArmor", ""));
StatusEffectDescLib.set(StatusEffectType.RepeatSuccubi, new StatusEffectDesc(StatusEffectType.RepeatSuccubi, "RepeatSuccubi", "repeatSuccubi", ""));
StatusEffectDescLib.set(StatusEffectType.Rut, new StatusEffectDesc(StatusEffectType.Rut, "Rut", "rut", ""));
StatusEffectDescLib.set(StatusEffectType.SharkGirl, new StatusEffectDesc(StatusEffectType.SharkGirl, "SharkGirl", "Shark-Girl", ""));
StatusEffectDescLib.set(StatusEffectType.ShieldingSpell, new StatusEffectDesc(StatusEffectType.ShieldingSpell, "ShieldingSpell", "Shielding Spell", ""));
StatusEffectDescLib.set(StatusEffectType.SlimeCraving, new StatusEffectDesc(StatusEffectType.SlimeCraving, "SlimeCraving", "Slime Craving", ""));
StatusEffectDescLib.set(StatusEffectType.SlimeCravingFeed, new StatusEffectDesc(StatusEffectType.SlimeCravingFeed, "SlimeCravingFeed", "Slime Craving Feed", ""));
StatusEffectDescLib.set(StatusEffectType.SlimeCravingOutput, new StatusEffectDesc(StatusEffectType.SlimeCravingOutput, "SlimeCravingOutput", "Slime Craving Output", ""));
StatusEffectDescLib.set(StatusEffectType.SuccubiFirst, new StatusEffectDesc(StatusEffectType.SuccubiFirst, "SuccubiFirst", "SuccubiFirst", ""));
StatusEffectDescLib.set(StatusEffectType.SuccubiNight, new StatusEffectDesc(StatusEffectType.SuccubiNight, "SuccubiNight", "succubiNight", ""));
StatusEffectDescLib.set(StatusEffectType.TakenGroPlus, new StatusEffectDesc(StatusEffectType.TakenGroPlus, "TakenGroPlus", "TakenGro+", ""));
StatusEffectDescLib.set(StatusEffectType.TakenLactaid, new StatusEffectDesc(StatusEffectType.TakenLactaid, "TakenLactaid", "TakenLactaid", ""));
// Used only for compatibility with old save files, otherwise no longer in use
StatusEffectDescLib.set(StatusEffectType.Tamani, new StatusEffectDesc(StatusEffectType.Tamani, "Tamani", "Tamani", ""));
// Used only for compatibility with old save files, otherwise no longer in use
StatusEffectDescLib.set(StatusEffectType.TamaniFemaleEncounter, new StatusEffectDesc(StatusEffectType.TamaniFemaleEncounter, "TamaniFemaleEncounter", "Tamani Female Encounter", ""));
StatusEffectDescLib.set(StatusEffectType.TelAdre, new StatusEffectDesc(StatusEffectType.TelAdre, "TelAdre", "Tel'Adre", ""));
StatusEffectDescLib.set(StatusEffectType.TentacleBadEndCounter, new StatusEffectDesc(StatusEffectType.TentacleBadEndCounter, "TentacleBadEndCounter", "TentacleBadEndCounter", ""));
StatusEffectDescLib.set(StatusEffectType.TentacleJojo, new StatusEffectDesc(StatusEffectType.TentacleJojo, "TentacleJojo", "Tentacle Jojo", ""));
StatusEffectDescLib.set(StatusEffectType.TensionReleased, new StatusEffectDesc(StatusEffectType.TensionReleased, "TensionReleased", "TensionReleased", ""));
StatusEffectDescLib.set(StatusEffectType.TF2, new StatusEffectDesc(StatusEffectType.TF2, "TF2", "TF2", ""));
StatusEffectDescLib.set(StatusEffectType.TookBlessedSword, new StatusEffectDesc(StatusEffectType.TookBlessedSword, "TookBlessedSword", "Took Blessed Sword", ""));
/**
 * v1 = bonus index
 * v2 = bonus value
 * v3 = remaining time
 */
StatusEffectDescLib.set(StatusEffectType.UmasMassage, new StatusEffectDesc(StatusEffectType.UmasMassage, "UmasMassage", "Uma's Massage", ""));
StatusEffectDescLib.set(StatusEffectType.Uniball, new StatusEffectDesc(StatusEffectType.Uniball, "Uniball", "Uniball", ""));
StatusEffectDescLib.set(StatusEffectType.UsedNaturalSelfStim, new StatusEffectDesc(StatusEffectType.UsedNaturalSelfStim, "UsedNaturalSelfStim", "used natural self-stim", ""));
StatusEffectDescLib.set(StatusEffectType.used_self_dash_stim, new StatusEffectDesc(StatusEffectType.used_self_dash_stim, "used_self_dash_stim", "used self-stim", ""));
StatusEffectDescLib.set(StatusEffectType.Victoria, new StatusEffectDesc(StatusEffectType.Victoria, "Victoria", "Victoria", ""));
StatusEffectDescLib.set(StatusEffectType.VoluntaryDemonpack, new StatusEffectDesc(StatusEffectType.VoluntaryDemonpack, "VoluntaryDemonpack", "Voluntary Demonpack", ""));
StatusEffectDescLib.set(StatusEffectType.WormOffer, new StatusEffectDesc(StatusEffectType.WormOffer, "WormOffer", "WormOffer", ""));
StatusEffectDescLib.set(StatusEffectType.WormPlugged, new StatusEffectDesc(StatusEffectType.WormPlugged, "WormPlugged", "worm plugged", ""));
StatusEffectDescLib.set(StatusEffectType.WormsHalf, new StatusEffectDesc(StatusEffectType.WormsHalf, "WormsHalf", "wormsHalf", ""));
StatusEffectDescLib.set(StatusEffectType.WormsOff, new StatusEffectDesc(StatusEffectType.WormsOff, "WormsOff", "wormsOff", ""));
StatusEffectDescLib.set(StatusEffectType.WormsOn, new StatusEffectDesc(StatusEffectType.WormsOn, "WormsOn", "wormsOn", ""));
StatusEffectDescLib.set(StatusEffectType.WandererDemon, new StatusEffectDesc(StatusEffectType.WandererDemon, "WandererDemon", "wanderer demon", ""));
StatusEffectDescLib.set(StatusEffectType.WandererHuman, new StatusEffectDesc(StatusEffectType.WandererHuman, "WandererHuman", "wanderer human", ""));
StatusEffectDescLib.set(StatusEffectType.Yara, new StatusEffectDesc(StatusEffectType.Yara, "Yara", "Yara", ""));

// monster
StatusEffectDescLib.set(StatusEffectType.Attacks, new StatusEffectDesc(StatusEffectType.Attacks, "Attacks", "attacks", ""));
StatusEffectDescLib.set(StatusEffectType.BimboBrawl, new StatusEffectDesc(StatusEffectType.BimboBrawl, "BimboBrawl", "bimboBrawl", ""));
StatusEffectDescLib.set(StatusEffectType.BowCooldown, new StatusEffectDesc(StatusEffectType.BowCooldown, "BowCooldown", "Bow Cooldown", ""));
StatusEffectDescLib.set(StatusEffectType.BowDisabled, new StatusEffectDesc(StatusEffectType.BowDisabled, "BowDisabled", "Bow Disabled", ""));
StatusEffectDescLib.set(StatusEffectType.Charged, new StatusEffectDesc(StatusEffectType.Charged, "Charged", "Charged", ""));
StatusEffectDescLib.set(StatusEffectType.Climbed, new StatusEffectDesc(StatusEffectType.Climbed, "Climbed", "Climbed", ""));
StatusEffectDescLib.set(StatusEffectType.Concentration, new StatusEffectDesc(StatusEffectType.Concentration, "Concentration", "Concentration", ""));
StatusEffectDescLib.set(StatusEffectType.Constricted, new StatusEffectDesc(StatusEffectType.Constricted, "Constricted", "Constricted", ""));
StatusEffectDescLib.set(StatusEffectType.CoonWhip, new StatusEffectDesc(StatusEffectType.CoonWhip, "CoonWhip", "Coon Whip", ""));
StatusEffectDescLib.set(StatusEffectType.Counter, new StatusEffectDesc(StatusEffectType.Counter, "Counter", "Counter", ""));
StatusEffectDescLib.set(StatusEffectType.DomFight, new StatusEffectDesc(StatusEffectType.DomFight, "DomFight", "domfight", ""));
StatusEffectDescLib.set(StatusEffectType.DrankMinoCum, new StatusEffectDesc(StatusEffectType.DrankMinoCum, "DrankMinoCum", "drank mino cum", ""));
StatusEffectDescLib.set(StatusEffectType.DrankMinoCum2, new StatusEffectDesc(StatusEffectType.DrankMinoCum2, "DrankMinoCum2", "drank mino cum2", ""));
StatusEffectDescLib.set(StatusEffectType.Earthshield, new StatusEffectDesc(StatusEffectType.Earthshield, "Earthshield", "Earthshield", ""));
StatusEffectDescLib.set(StatusEffectType.Fear, new StatusEffectDesc(StatusEffectType.Fear, "Fear", "Fear", ""));
StatusEffectDescLib.set(StatusEffectType.GenericRunDisabled, new StatusEffectDesc(StatusEffectType.GenericRunDisabled, "GenericRunDisabled", "Generic Run Disabled", ""));
StatusEffectDescLib.set(StatusEffectType.Gigafire, new StatusEffectDesc(StatusEffectType.Gigafire, "Gigafire", "Gigafire", ""));
StatusEffectDescLib.set(StatusEffectType.GottaOpenGift, new StatusEffectDesc(StatusEffectType.GottaOpenGift, "GottaOpenGift", "Gotta Open Gift", ""));
StatusEffectDescLib.set(StatusEffectType.HolliBurning, new StatusEffectDesc(StatusEffectType.HolliBurning, "HolliBurning", "Holli Burning", ""));
StatusEffectDescLib.set(StatusEffectType.Illusion, new StatusEffectDesc(StatusEffectType.Illusion, "Illusion", "Illusion", ""));
StatusEffectDescLib.set(StatusEffectType.ImpSkip, new StatusEffectDesc(StatusEffectType.ImpSkip, "ImpSkip", "ImpSkip", ""));
StatusEffectDescLib.set(StatusEffectType.ImpUber, new StatusEffectDesc(StatusEffectType.ImpUber, "ImpUber", "ImpUber", ""));
StatusEffectDescLib.set(StatusEffectType.JojoIsAssisting, new StatusEffectDesc(StatusEffectType.JojoIsAssisting, "JojoIsAssisting", "Jojo Is Assisting", ""));
StatusEffectDescLib.set(StatusEffectType.JojoPyre, new StatusEffectDesc(StatusEffectType.JojoPyre, "JojoPyre", "Jojo Pyre", ""));
StatusEffectDescLib.set(StatusEffectType.Keen, new StatusEffectDesc(StatusEffectType.Keen, "Keen", "keen", ""));
StatusEffectDescLib.set(StatusEffectType.Level, new StatusEffectDesc(StatusEffectType.Level, "Level", "level", ""));
StatusEffectDescLib.set(StatusEffectType.KitsuneFight, new StatusEffectDesc(StatusEffectType.KitsuneFight, "KitsuneFight", "Kitsune Fight", ""));
StatusEffectDescLib.set(StatusEffectType.LustAura, new StatusEffectDesc(StatusEffectType.LustAura, "LustAura", "Lust Aura", ""));
StatusEffectDescLib.set(StatusEffectType.LustStick, new StatusEffectDesc(StatusEffectType.LustStick, "LustStick", "LustStick", ""));
StatusEffectDescLib.set(StatusEffectType.Milk, new StatusEffectDesc(StatusEffectType.Milk, "Milk", "milk", ""));
StatusEffectDescLib.set(StatusEffectType.MilkyUrta, new StatusEffectDesc(StatusEffectType.MilkyUrta, "MilkyUrta", "Milky Urta", ""));
StatusEffectDescLib.set(StatusEffectType.MinoMilk, new StatusEffectDesc(StatusEffectType.MinoMilk, "MinoMilk", "Mino Milk", ""));
StatusEffectDescLib.set(StatusEffectType.MinotaurEntangled, new StatusEffectDesc(StatusEffectType.MinotaurEntangled, "MinotaurEntangled", "Minotaur Entangled", ""));
StatusEffectDescLib.set(StatusEffectType.MissFirstRound, new StatusEffectDesc(StatusEffectType.MissFirstRound, "MissFirstRound", "miss first round", ""));
StatusEffectDescLib.set(StatusEffectType.NoLoot, new StatusEffectDesc(StatusEffectType.NoLoot, "NoLoot", "No Loot", ""));
StatusEffectDescLib.set(StatusEffectType.PCTailTangle, new StatusEffectDesc(StatusEffectType.PCTailTangle, "PCTailTangle", "PCTailTangle", ""));
StatusEffectDescLib.set(StatusEffectType.PeachLootLoss, new StatusEffectDesc(StatusEffectType.PeachLootLoss, "PeachLootLoss", "Peach Loot Loss", ""));
// @aimozg i don't know and do not fucking care if these two should be merged
StatusEffectDescLib.set(StatusEffectType.PhyllaFight, new StatusEffectDesc(StatusEffectType.PhyllaFight, "PhyllaFight", "PhyllaFight", ""));
StatusEffectDescLib.set(StatusEffectType.Platoon, new StatusEffectDesc(StatusEffectType.Platoon, "Platoon", "platoon", ""));
StatusEffectDescLib.set(StatusEffectType.QueenBind, new StatusEffectDesc(StatusEffectType.QueenBind, "QueenBind", "QueenBind", ""));
// @aimozg HA HA HA
StatusEffectDescLib.set(StatusEffectType.Round, new StatusEffectDesc(StatusEffectType.Round, "Round", "Round", ""));
StatusEffectDescLib.set(StatusEffectType.RunDisabled, new StatusEffectDesc(StatusEffectType.RunDisabled, "RunDisabled", "Run Disabled", ""));
StatusEffectDescLib.set(StatusEffectType.Shell, new StatusEffectDesc(StatusEffectType.Shell, "Shell", "Shell", ""));
StatusEffectDescLib.set(StatusEffectType.SirenSong, new StatusEffectDesc(StatusEffectType.SirenSong, "SirenSong", "Siren Song", ""));
StatusEffectDescLib.set(StatusEffectType.Spar, new StatusEffectDesc(StatusEffectType.Spar, "Spar", "spar", ""));
StatusEffectDescLib.set(StatusEffectType.Sparring, new StatusEffectDesc(StatusEffectType.Sparring, "Sparring", "sparring", ""));
StatusEffectDescLib.set(StatusEffectType.spiderfight, new StatusEffectDesc(StatusEffectType.spiderfight, "spiderfight", "spiderfight", ""));
StatusEffectDescLib.set(StatusEffectType.StunCooldown, new StatusEffectDesc(StatusEffectType.StunCooldown, "StunCooldown", "Stun Cooldown", ""));
StatusEffectDescLib.set(StatusEffectType.TentacleCoolDown, new StatusEffectDesc(StatusEffectType.TentacleCoolDown, "TentacleCoolDown", "TentacleCoolDown", ""));
StatusEffectDescLib.set(StatusEffectType.Timer, new StatusEffectDesc(StatusEffectType.Timer, "Timer", "Timer", ""));
StatusEffectDescLib.set(StatusEffectType.Uber, new StatusEffectDesc(StatusEffectType.Uber, "Uber", "Uber", ""));
StatusEffectDescLib.set(StatusEffectType.UrtaSecondWinded, new StatusEffectDesc(StatusEffectType.UrtaSecondWinded, "UrtaSecondWinded", "Urta Second Winded", ""));
StatusEffectDescLib.set(StatusEffectType.UsedTitsmother, new StatusEffectDesc(StatusEffectType.UsedTitsmother, "UsedTitsmother", "UsedTitsmother", ""));
StatusEffectDescLib.set(StatusEffectType.Vala, new StatusEffectDesc(StatusEffectType.Vala, "Vala", "vala", ""));
StatusEffectDescLib.set(StatusEffectType.Vapula, new StatusEffectDesc(StatusEffectType.Vapula, "Vapula", "Vapula", ""));
StatusEffectDescLib.set(StatusEffectType.WhipReady, new StatusEffectDesc(StatusEffectType.WhipReady, "WhipReady", "Whip Ready", ""));

// combat
StatusEffectDescLib.set(StatusEffectType.AcidSlap, new StatusEffectDesc(StatusEffectType.AcidSlap, "AcidSlap", "Acid Slap", ""));
StatusEffectDescLib.set(StatusEffectType.AkbalSpeed, new StatusEffectDesc(StatusEffectType.AkbalSpeed, "AkbalSpeed", "Akbal Speed", ""));
StatusEffectDescLib.set(StatusEffectType.AmilyVenom, new StatusEffectDesc(StatusEffectType.AmilyVenom, "AmilyVenom", "Amily Venom", ""));
StatusEffectDescLib.set(StatusEffectType.AnemoneVenom, new StatusEffectDesc(StatusEffectType.AnemoneVenom, "AnemoneVenom", "Anemone Venom", ""));
StatusEffectDescLib.set(StatusEffectType.AttackDisabled, new StatusEffectDesc(StatusEffectType.AttackDisabled, "AttackDisabled", "Attack Disabled", ""));
StatusEffectDescLib.set(StatusEffectType.BasiliskCompulsion, new StatusEffectDesc(StatusEffectType.BasiliskCompulsion, "BasiliskCompulsion", "Basilisk Compulsion", ""));
StatusEffectDescLib.set(StatusEffectType.BasiliskSlow, new StatusEffectDesc(StatusEffectType.BasiliskSlow, "BasiliskSlow", "BasiliskSlow", ""));
StatusEffectDescLib.set(StatusEffectType.Berzerking, new StatusEffectDesc(StatusEffectType.Berzerking, "Berzerking", "Berzerking", ""));
StatusEffectDescLib.set(StatusEffectType.Blind, new StatusEffectDesc(StatusEffectType.Blind, "Blind", "Blind", ""));
StatusEffectDescLib.set(StatusEffectType.Bound, new StatusEffectDesc(StatusEffectType.Bound, "Bound", "Bound", ""));
StatusEffectDescLib.set(StatusEffectType.CalledShot, new StatusEffectDesc(StatusEffectType.CalledShot, "CalledShot", "Called Shot", ""));
StatusEffectDescLib.set(StatusEffectType.ChargeWeapon, new StatusEffectDesc(StatusEffectType.ChargeWeapon, "ChargeWeapon", "Charge Weapon", ""));
StatusEffectDescLib.set(StatusEffectType.Chokeslam, new StatusEffectDesc(StatusEffectType.Chokeslam, "Chokeslam", "Chokeslam", ""));
StatusEffectDescLib.set(StatusEffectType.Confusion, new StatusEffectDesc(StatusEffectType.Confusion, "Confusion", "Confusion", ""));
StatusEffectDescLib.set(StatusEffectType.DemonSeed, new StatusEffectDesc(StatusEffectType.DemonSeed, "DemonSeed", "DemonSeed", ""));
StatusEffectDescLib.set(StatusEffectType.Disarmed, new StatusEffectDesc(StatusEffectType.Disarmed, "Disarmed", "Disarmed", ""));
StatusEffectDescLib.set(StatusEffectType.DriderKiss, new StatusEffectDesc(StatusEffectType.DriderKiss, "DriderKiss", "Drider Kiss", ""));
StatusEffectDescLib.set(StatusEffectType.FirstAttack, new StatusEffectDesc(StatusEffectType.FirstAttack, "FirstAttack", "FirstAttack", ""));
StatusEffectDescLib.set(StatusEffectType.GnollSpear, new StatusEffectDesc(StatusEffectType.GnollSpear, "GnollSpear", "Gnoll Spear", ""));
StatusEffectDescLib.set(StatusEffectType.GooArmorBind, new StatusEffectDesc(StatusEffectType.GooArmorBind, "GooArmorBind", "GooArmorBind", ""));
StatusEffectDescLib.set(StatusEffectType.GooArmorSilence, new StatusEffectDesc(StatusEffectType.GooArmorSilence, "GooArmorSilence", "GooArmorSilence", ""));
StatusEffectDescLib.set(StatusEffectType.GooBind, new StatusEffectDesc(StatusEffectType.GooBind, "GooBind", "GooBind", ""));
StatusEffectDescLib.set(StatusEffectType.HarpyBind, new StatusEffectDesc(StatusEffectType.HarpyBind, "HarpyBind", "HarpyBind", ""));
StatusEffectDescLib.set(StatusEffectType.HolliConstrict, new StatusEffectDesc(StatusEffectType.HolliConstrict, "HolliConstrict", "Holli Constrict", ""));
StatusEffectDescLib.set(StatusEffectType.InfestAttempted, new StatusEffectDesc(StatusEffectType.InfestAttempted, "InfestAttempted", "infestAttempted", ""));
StatusEffectDescLib.set(StatusEffectType.IsabellaStunned, new StatusEffectDesc(StatusEffectType.IsabellaStunned, "IsabellaStunned", "Isabella Stunned", ""));
StatusEffectDescLib.set(StatusEffectType.IzmaBleed, new StatusEffectDesc(StatusEffectType.IzmaBleed, "IzmaBleed", "Izma Bleed", ""));
StatusEffectDescLib.set(StatusEffectType.KissOfDeath, new StatusEffectDesc(StatusEffectType.KissOfDeath, "KissOfDeath", "Kiss of Death", ""));
StatusEffectDescLib.set(StatusEffectType.LustStones, new StatusEffectDesc(StatusEffectType.LustStones, "LustStones", "lust stones", ""));
StatusEffectDescLib.set(StatusEffectType.lustvenom, new StatusEffectDesc(StatusEffectType.lustvenom, "lustvenom", "lust venom", ""));
StatusEffectDescLib.set(StatusEffectType.Might, new StatusEffectDesc(StatusEffectType.Might, "Might", "Might", ""));
StatusEffectDescLib.set(StatusEffectType.NagaBind, new StatusEffectDesc(StatusEffectType.NagaBind, "NagaBind", "Naga Bind", ""));
StatusEffectDescLib.set(StatusEffectType.NagaVenom, new StatusEffectDesc(StatusEffectType.NagaVenom, "NagaVenom", "Naga Venom", ""));
StatusEffectDescLib.set(StatusEffectType.NoFlee, new StatusEffectDesc(StatusEffectType.NoFlee, "NoFlee", "NoFlee", ""));
StatusEffectDescLib.set(StatusEffectType.ParalyzeVenom, new StatusEffectDesc(StatusEffectType.ParalyzeVenom, "ParalyzeVenom", "paralyze venom", ""));
StatusEffectDescLib.set(StatusEffectType.PhysicalDisabled, new StatusEffectDesc(StatusEffectType.PhysicalDisabled, "PhysicalDisabled", "Physical Disabled", ""));
StatusEffectDescLib.set(StatusEffectType.Poison, new StatusEffectDesc(StatusEffectType.Poison, "Poison", "Poison", ""));
StatusEffectDescLib.set(StatusEffectType.Sandstorm, new StatusEffectDesc(StatusEffectType.Sandstorm, "Sandstorm", "sandstorm", ""));
StatusEffectDescLib.set(StatusEffectType.Sealed, new StatusEffectDesc(StatusEffectType.Sealed, "Sealed", "Sealed", ""));
StatusEffectDescLib.set(StatusEffectType.SheilaOil, new StatusEffectDesc(StatusEffectType.SheilaOil, "SheilaOil", "Sheila Oil", ""));
StatusEffectDescLib.set(StatusEffectType.Shielding, new StatusEffectDesc(StatusEffectType.Shielding, "Shielding", "Sheilding", ""));
StatusEffectDescLib.set(StatusEffectType.StoneLust, new StatusEffectDesc(StatusEffectType.StoneLust, "StoneLust", "Stone Lust", ""));
StatusEffectDescLib.set(StatusEffectType.Stunned, new StatusEffectDesc(StatusEffectType.Stunned, "Stunned", "Stunned", ""));
StatusEffectDescLib.set(StatusEffectType.TailWhip, new StatusEffectDesc(StatusEffectType.TailWhip, "TailWhip", "Tail Whip", ""));
StatusEffectDescLib.set(StatusEffectType.TemporaryHeat, new StatusEffectDesc(StatusEffectType.TemporaryHeat, "TemporaryHeat", "Temporary Heat", ""));
StatusEffectDescLib.set(StatusEffectType.TentacleBind, new StatusEffectDesc(StatusEffectType.TentacleBind, "TentacleBind", "TentacleBind", ""));
StatusEffectDescLib.set(StatusEffectType.ThroatPunch, new StatusEffectDesc(StatusEffectType.ThroatPunch, "ThroatPunch", "Throat Punch", ""));
StatusEffectDescLib.set(StatusEffectType.Titsmother, new StatusEffectDesc(StatusEffectType.Titsmother, "Titsmother", "Titsmother", ""));
StatusEffectDescLib.set(StatusEffectType.TwuWuv, new StatusEffectDesc(StatusEffectType.TwuWuv, "TwuWuv", "Twu Wuv", ""));
StatusEffectDescLib.set(StatusEffectType.UBERWEB, new StatusEffectDesc(StatusEffectType.UBERWEB, "UBERWEB", "UBERWEB", ""));
StatusEffectDescLib.set(StatusEffectType.Web, new StatusEffectDesc(StatusEffectType.Web, "Web", "Web", ""));
StatusEffectDescLib.set(StatusEffectType.WebSilence, new StatusEffectDesc(StatusEffectType.WebSilence, "WebSilence", "Web-Silence", ""));
StatusEffectDescLib.set(StatusEffectType.Whispered, new StatusEffectDesc(StatusEffectType.Whispered, "Whispered", "Whispered", ""));

StatusEffectDescLib.set(StatusEffectType.RemovedArmor, new StatusEffectDesc(StatusEffectType.RemovedArmor, "RemovedArmor", "Removed Armor", ""));
StatusEffectDescLib.set(StatusEffectType.JCLustLevel, new StatusEffectDesc(StatusEffectType.JCLustLevel, "JCLustLevel", "JC Lust Level", ""));
StatusEffectDescLib.set(StatusEffectType.MirroredAttack, new StatusEffectDesc(StatusEffectType.MirroredAttack, "MirroredAttack", "Mirrored Attack", ""));
StatusEffectDescLib.set(StatusEffectType.KnockedBack, new StatusEffectDesc(StatusEffectType.KnockedBack, "KnockedBack", "Knocked Back", ""));
StatusEffectDescLib.set(StatusEffectType.Tentagrappled, new StatusEffectDesc(StatusEffectType.Tentagrappled, "Tentagrappled", "Tentagrappled", ""));
StatusEffectDescLib.set(StatusEffectType.TentagrappleCooldown, new StatusEffectDesc(StatusEffectType.TentagrappleCooldown, "TentagrappleCooldown", "Tentagrapple Cooldown", ""));
StatusEffectDescLib.set(StatusEffectType.ShowerDotEffect, new StatusEffectDesc(StatusEffectType.ShowerDotEffect, "ShowerDotEffect", "Shower Dot Effect", ""));
StatusEffectDescLib.set(StatusEffectType.GardenerSapSpeed, new StatusEffectDesc(StatusEffectType.GardenerSapSpeed, "GardenerSapSpeed", "Sap Speed", ""));
StatusEffectDescLib.set(StatusEffectType.VineHealUsed, new StatusEffectDesc(StatusEffectType.VineHealUsed, "VineHealUsed", "Vine Heal Used", ""));
