import ImageName from './ImageName';
import Dictionary from '../../Utilities/Dictionary';
import Utils from '../../Utilities/Utils';

interface ImageLoaded {
    loaded: boolean;
}

export default class ImageLibary {
    private readonly directory: string = "img/";
    private readonly extentions: string[] = [".jpg", ".png", ".jpeg"];
    private lib: Dictionary<string[]>;
    public constructor() {
        this.lib = new Dictionary<string[]>();
        this.loadImages();
    }

    public get(name: ImageName): string {
        return Utils.randomChoice(this.lib.get(name));
    }

    private loadImage(imageName: ImageName, imagePath: string) {
        new Promise<ImageLoaded>(resolve => {
            const img = new Image();
            img.onload = () => resolve({ loaded: false });
            img.onerror = () => resolve({ loaded: true });

            img.src = imagePath;
        }).then(value => {
            if (value.loaded)
                this.lib.get(imageName).push(imagePath);
        });
    }

    private constructPath(imageName: string, imageIndex: number, extention: string): string {
        return this.directory + imageName + "_" + imageIndex + extention;
    }

    private loadImages() {
        this.lib.clear();
        for (let imageIndex = 0; imageIndex < 10; imageIndex++) {
            for (let extIndex = 0; extIndex < this.extentions.length; extIndex++) {
                this.loadImage(ImageName.akbal_deepwoods_bigbuttanaled, this.constructPath("akbal-deepwoods-bigbuttanaled", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_female_bindakbal, this.constructPath("akbal-deepwoods-female-bindakbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_female_highspeed, this.constructPath("akbal-deepwoods-female-highspeed", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_female_highstrength, this.constructPath("akbal-deepwoods-female-highstrength", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_female_naga_rapeakbal, this.constructPath("akbal-deepwoods-female-naga-rapeakbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_female_rapeakbal, this.constructPath("akbal-deepwoods-female-rapeakbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_female_taur_bindakbal, this.constructPath("akbal-deepwoods-female-taur-bindakbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_female_taur_rapeakbal, this.constructPath("akbal-deepwoods-female-taur-rapeakbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_forcedfemaleoral, this.constructPath("akbal-deepwoods-forcedfemaleoral", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_losslust_analed, this.constructPath("akbal-deepwoods-losslust-analed", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_losslust_taur_analed, this.constructPath("akbal-deepwoods-losslust-taur-analed", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_akbalonback, this.constructPath("akbal-deepwoods-male-akbalonback", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_akbalonback2, this.constructPath("akbal-deepwoods-male-akbalonback2", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_buttfuck, this.constructPath("akbal-deepwoods-male-buttfuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_buttfuck2, this.constructPath("akbal-deepwoods-male-buttfuck2", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_highspeed, this.constructPath("akbal-deepwoods-male-highspeed", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_highstrength, this.constructPath("akbal-deepwoods-male-highstrength", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_hightoughness, this.constructPath("akbal-deepwoods-male-hightoughness", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_jojosex, this.constructPath("akbal-deepwoods-male-jojosex", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_naga_rapeakbal, this.constructPath("akbal-deepwoods-male-naga-rapeakbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_rapeakbal, this.constructPath("akbal-deepwoods-male-rapeakbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_male_taur_rapeakbal, this.constructPath("akbal-deepwoods-male-taur-rapeakbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_naga_forcedfemaleoral, this.constructPath("akbal-deepwoods-naga-forcedfemaleoral", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_naga_sumbitanal, this.constructPath("akbal-deepwoods-naga-sumbitanal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_sumbitanal, this.constructPath("akbal-deepwoods-sumbitanal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_taur_forcedfemaleoral, this.constructPath("akbal-deepwoods-taur-forcedfemaleoral", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.akbal_deepwoods_taur_sumbitanal, this.constructPath("akbal-deepwoods-taur-sumbitanal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.amily_forest_fuckpreg, this.constructPath("amily-forest-fuckpreg", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.amily_forest_kissingfuck, this.constructPath("amily-forest-kissingfuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.amily_forest_plainfuck, this.constructPath("amily-forest-plainfuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.amily_forest_reverse_cowgirl, this.constructPath("amily-forest-reverse-cowgirl", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.amily_forest_takecharge, this.constructPath("amily-forest-takecharge", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_bj, this.constructPath("anemone-bj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_doggy, this.constructPath("anemone-doggy", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_egg, this.constructPath("anemone-egg", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_female_fuck, this.constructPath("anemone-female-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_getanal, this.constructPath("anemone-getanal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_kid_female_masti, this.constructPath("anemone-kid-female-masti", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_kid_female_sex, this.constructPath("anemone-kid-female-sex", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_kid_male_bj, this.constructPath("anemone-kid-male-bj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_kid_male_masti, this.constructPath("anemone-kid-male-masti", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_kid_male_vagfuck, this.constructPath("anemone-kid-male-vagfuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.anemone_male_fuck, this.constructPath("anemone-male-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ants_desert_female_firstencounter, this.constructPath("ants-desert-female-firstencounter", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ants_desert_male_firstencounter, this.constructPath("ants-desert-male-firstencounter", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_camp_dreamingArian, this.constructPath("arianfemale-camp-dreamingArian", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_docking, this.constructPath("arianfemale-home-docking", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_doublepenetrate, this.constructPath("arianfemale-home-doublepenetrate", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_getArianAnal, this.constructPath("arianfemale-home-getArianAnal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_getbj, this.constructPath("arianfemale-home-getbj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_getpenetrated, this.constructPath("arianfemale-home-getpenetrated", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_giveArianAnal, this.constructPath("arianfemale-home-giveArianAnal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_mutualmasturbation, this.constructPath("arianfemale-home-mutualmasturbation", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_penetrate, this.constructPath("arianfemale-home-penetrate", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianfemale_home_suckariandick, this.constructPath("arianfemale-home-suckariandick", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianmale_camp_dreamingArian, this.constructPath("arianmale-camp-dreamingArian", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianmale_home_docking, this.constructPath("arianmale-home-docking", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianmale_home_getArianAnal, this.constructPath("arianmale-home-getArianAnal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianmale_home_getbj, this.constructPath("arianmale-home-getbj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianmale_home_getpenetrated, this.constructPath("arianmale-home-getpenetrated", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianmale_home_giveArianAnal, this.constructPath("arianmale-home-giveArianAnal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianmale_home_mutualmasturbation, this.constructPath("arianmale-home-mutualmasturbation", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.arianmale_home_suckariandick, this.constructPath("arianmale-home-suckariandick", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_first_meeting, this.constructPath("brooke-first-meeting", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_grope_her, this.constructPath("brooke-grope-her", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_female_getLaid, this.constructPath("brooke-gym-female-getLaid", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_female_specialscene, this.constructPath("brooke-gym-female-specialscene", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_female_tribadism, this.constructPath("brooke-gym-female-tribadism", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_goDown, this.constructPath("brooke-gym-goDown", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_heckelbrooke3some, this.constructPath("brooke-gym-heckelbrooke3some", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_heckelbrookedominance, this.constructPath("brooke-gym-heckelbrookedominance", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_male_analbrooke, this.constructPath("brooke-gym-male-analbrooke", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_male_doubledicked, this.constructPath("brooke-gym-male-doubledicked", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_male_getLaid, this.constructPath("brooke-gym-male-getLaid", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_male_penetratebrooke, this.constructPath("brooke-gym-male-penetratebrooke", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.brooke_gym_male_specialscene, this.constructPath("brooke-gym-male-specialscene", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.camping, this.constructPath("camping", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_first_fuck, this.constructPath("cotton-first-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_first_time_give_her_blowjob, this.constructPath("cotton-first-time-give-her-blowjob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_fucks_you, this.constructPath("cotton-fucks-you", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_giving_birth, this.constructPath("cotton-giving-birth", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_greeting, this.constructPath("cotton-greeting", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_shower_fuck_repeat, this.constructPath("cotton-shower-fuck-repeat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_shower_fucks_you_repeat, this.constructPath("cotton-shower-fucks-you-repeat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_tantric_sex, this.constructPath("cotton-tantric-sex", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_visits_you_at_camp_drinks_all_your_milk_the_asshole, this.constructPath("cotton-visits-you-at-camp-drinks-all-your-milk-the-asshole", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_yoga, this.constructPath("cotton-yoga", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.cotton_you_got_her_preggo, this.constructPath("cotton-you-got-her-preggo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.dominika_first_meeting_at_bar, this.constructPath("dominika-first-meeting-at-bar", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.dominika_gives_you_blowjob, this.constructPath("dominika-gives-you-blowjob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.dominika_oral_sex, this.constructPath("dominika-oral-sex", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.edryn_bar_chat, this.constructPath("edryn-bar-chat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.edryn_eat_her_out, this.constructPath("edryn-eat-her-out", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.edryn_fuck_as_non_taur, this.constructPath("edryn-fuck-as-non-taur", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.edryn_fuck_as_taur, this.constructPath("edryn-fuck-as-taur", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.edryn_hel_threesome, this.constructPath("edryn-hel-threesome", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.edryn_preggo_fuck, this.constructPath("edryn-preggo-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_drink_her_milk, this.constructPath("ember-drink-her-milk", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_eat_out_her_vagoo, this.constructPath("ember-eat-out-her-vagoo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_eats_your_vagoo_out, this.constructPath("ember-eats-your-vagoo-out", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_examine_appearance, this.constructPath("ember-examine-appearance", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_fuck_her_in_her_buttz, this.constructPath("ember-fuck-her-in-her-buttz", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_fuck_her_in_the_vagoo_with_your_penor, this.constructPath("ember-fuck-her-in-the-vagoo-with-your-penor", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_fucks_your_ass, this.constructPath("ember-fucks-your-ass", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_give_her_a_blowjob, this.constructPath("ember-give-her-a-blowjob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_gives_you_a_blowjob, this.constructPath("ember-gives-you-a-blowjob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_sticks_her_penor_in_your_vagoo, this.constructPath("ember-sticks-her-penor-in-your-vagoo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.ember_visit_at_camp, this.constructPath("ember-visit-at-camp", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_loss_female_bimbodildo, this.constructPath("goblin-loss-female-bimbodildo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_loss_female_raped, this.constructPath("goblin-loss-female-raped", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_loss_male_raped, this.constructPath("goblin-loss-male-raped", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_drider_egged, this.constructPath("goblin-win-drider-egged", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_female_naga_rapedfem, this.constructPath("goblin-win-female-naga-rapedfem", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_female_rapedfem, this.constructPath("goblin-win-female-rapedfem", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_female_taur_rapedfem, this.constructPath("goblin-win-female-taur-rapedfem", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_male_buttsex, this.constructPath("goblin-win-male-buttsex", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_male_corruptedbj, this.constructPath("goblin-win-male-corruptedbj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_male_corruptedfuck, this.constructPath("goblin-win-male-corruptedfuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_male_getridden, this.constructPath("goblin-win-male-getridden", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_male_goblinboners, this.constructPath("goblin-win-male-goblinboners", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.goblin_win_male_goblincondomed, this.constructPath("goblin-win-male-goblincondomed", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.hel_chat_at_bar, this.constructPath("hel-chat-at-bar", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.imp_egg, this.constructPath("imp-egg", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.imp_loss_female_fuck, this.constructPath("imp-loss-female-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.imp_loss_male_fuck, this.constructPath("imp-loss-male-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.imp_win_female_fuck, this.constructPath("imp-win-female-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.imp_win_male_fuck, this.constructPath("imp-win-male-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.implord_loss_female, this.constructPath("implord-loss-female", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.implord_loss_male, this.constructPath("implord-loss-male", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.implord_win_female_breastfeed, this.constructPath("implord-win-female-breastfeed", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.implord_win_female_fuck, this.constructPath("implord-win-female-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.implord_win_male_bj, this.constructPath("implord-win-male-bj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.implord_win_male_fuck, this.constructPath("implord-win-male-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_double_helix_fuck, this.constructPath("katherine-double-helix-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_eats_out_your_vagoo, this.constructPath("katherine-eats-out-your-vagoo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_examine_her_appearance, this.constructPath("katherine-examine-her-appearance", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_fuck_and_suck, this.constructPath("katherine-fuck-and-suck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_fuck_her_bungholio, this.constructPath("katherine-fuck-her-bungholio", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_fuck_her_vagoo, this.constructPath("katherine-fuck-her-vagoo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_fucks_you_knottily_in_all_the_holes, this.constructPath("katherine-fucks-you-knottily-in-all-the-holes", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_fucks_you_knottily_in_the_bungholio, this.constructPath("katherine-fucks-you-knottily-in-the-bungholio", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_fucks_you_knottily_in_the_vagoo, this.constructPath("katherine-fucks-you-knottily-in-the-vagoo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_give_her_blowjobs, this.constructPath("katherine-give-her-blowjobs", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_suck_and_fucks_you, this.constructPath("katherine-suck-and-fucks-you", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_suckles_you, this.constructPath("katherine-suckles-you", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.katherine_visit_alley, this.constructPath("katherine-visit-alley", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.kelt_farm_eagerbj, this.constructPath("kelt-farm-eagerbj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.kelt_farm_female_inheat, this.constructPath("kelt-farm-female-inheat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.kelt_farm_naga_subkelt, this.constructPath("kelt-farm-naga-subkelt", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.kelt_farm_reluctantbj, this.constructPath("kelt-farm-reluctantbj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.kelt_farm_shamefulbj, this.constructPath("kelt-farm-shamefulbj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.kelt_farm_smallbarn, this.constructPath("kelt-farm-smallbarn", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.kelt_farm_subkelt, this.constructPath("kelt-farm-subkelt", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_comes_after_moar_orgasm_denial, this.constructPath("loppe-comes-after-moar-orgasm-denial", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_comes_after_orgasm_denial, this.constructPath("loppe-comes-after-orgasm-denial", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_give_her_a_titty_fuck, this.constructPath("loppe-give-her-a-titty-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_orgazm_denial, this.constructPath("loppe-orgazm-denial", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_rides_your_cock, this.constructPath("loppe-rides-your-cock", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_rides_your_cocks, this.constructPath("loppe-rides-your-cocks", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_show_at_bar, this.constructPath("loppe-show-at-bar", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_sticks_it_in_your_butt, this.constructPath("loppe-sticks-it-in-your-butt", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_sticks_it_in_your_butt_you_centaur, this.constructPath("loppe-sticks-it-in-your-butt-you-centaur", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_sticks_it_in_your_vagoo, this.constructPath("loppe-sticks-it-in-your-vagoo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_teaze_and_leave, this.constructPath("loppe-teaze-and-leave", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.loppe_worships_your_cock, this.constructPath("loppe-worships-your-cock", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_encounter, this.constructPath("lottie-encounter", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_examine_appearance, this.constructPath("lottie-examine-appearance", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_fuck_her_cowgirl_repeat, this.constructPath("lottie-fuck-her-cowgirl-repeat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_fuck_her_doggie_style_repeat, this.constructPath("lottie-fuck-her-doggie-style-repeat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_fuck_her_in_public_repeat, this.constructPath("lottie-fuck-her-in-public-repeat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_fuck_her_in_teh_butzor, this.constructPath("lottie-fuck-her-in-teh-butzor", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_fuck_her_threesome_repeat, this.constructPath("lottie-fuck-her-threesome-repeat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_fuck_her_with_tentacle_dick, this.constructPath("lottie-fuck-her-with-tentacle-dick", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_gives_you_a_blowjob, this.constructPath("lottie-gives-you-a-blowjob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.lottie_ifris_threesome, this.constructPath("lottie-ifris-threesome", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.marae_bad_end, this.constructPath("marae-bad-end", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.marae_first_encounter, this.constructPath("marae-first-encounter", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.marae_second_encounter, this.constructPath("marae-second-encounter", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.marae_second_encounter_pt_two, this.constructPath("marae-second-encounter-pt-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_akbal, this.constructPath("monster-akbal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_amily, this.constructPath("monster-amily", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_anemone, this.constructPath("monster-anemone", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_basilisk, this.constructPath("monster-basilisk", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_beegirl, this.constructPath("monster-beegirl", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_brigid, this.constructPath("monster-brigid", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_ceraph, this.constructPath("monster-ceraph", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_chameleongirl, this.constructPath("monster-chameleongirl", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_corrupteddrider, this.constructPath("monster-corrupteddrider", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_cumwitch, this.constructPath("monster-cumwitch", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_demonmob, this.constructPath("monster-demonmob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_ember, this.constructPath("monster-ember", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_farmers, this.constructPath("monster-farmers", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_femalespidermorph, this.constructPath("monster-femalespidermorph", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_fetishcultist, this.constructPath("monster-fetishcultist", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_fetishzealot, this.constructPath("monster-fetishzealot", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_gnoll, this.constructPath("monster-gnoll", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_gnollspearthrower, this.constructPath("monster-gnollspearthrower", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_goblin, this.constructPath("monster-goblin", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_goblinassassin, this.constructPath("monster-goblinassassin", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_gooarmor, this.constructPath("monster-gooarmor", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_googirl, this.constructPath("monster-googirl", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_greenslime, this.constructPath("monster-greenslime", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_harpy, this.constructPath("monster-harpy", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_harpymob, this.constructPath("monster-harpymob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_harpyqueen, this.constructPath("monster-harpyqueen", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_hel, this.constructPath("monster-hel", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_hellhound, this.constructPath("monster-hellhound", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_holli, this.constructPath("monster-holli", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_hollispawn, this.constructPath("monster-hollispawn", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_imageName, this.constructPath("monster-imageName", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_imp, this.constructPath("monster-imp", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_implord, this.constructPath("monster-implord", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_impmob, this.constructPath("monster-impmob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_incubusmechanic, this.constructPath("monster-incubusmechanic", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_infestedhellhound, this.constructPath("monster-infestedhellhound", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_isabella, this.constructPath("monster-isabella", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_izma, this.constructPath("monster-izma", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_izumi, this.constructPath("monster-izumi", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_jojo, this.constructPath("monster-jojo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_kelt, this.constructPath("monster-kelt", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_kiha, this.constructPath("monster-kiha", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_kitsune, this.constructPath("monster-kitsune", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_malespidermorph, this.constructPath("monster-malespidermorph", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_marble, this.constructPath("monster-marble", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_milkysuccubus, this.constructPath("monster-milkysuccubus", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_minerva, this.constructPath("monster-minerva", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_minotaur, this.constructPath("monster-minotaur", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_minotaurlord, this.constructPath("monster-minotaurlord", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_minotaurmob, this.constructPath("monster-minotaurmob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_naga, this.constructPath("monster-naga", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_omnibusoverseer, this.constructPath("monster-omnibusoverseer", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_phoenixmob, this.constructPath("monster-phoenixmob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_pod, this.constructPath("monster-pod", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sandmother, this.constructPath("monster-sandmother", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sandtrap, this.constructPath("monster-sandtrap", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sandwidch, this.constructPath("monster-sandwidch", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sandwitch, this.constructPath("monster-sandwitch", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sandwitchmob, this.constructPath("monster-sandwitchmob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_satyr, this.constructPath("monster-satyr", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_secretarialsuccubus, this.constructPath("monster-secretarialsuccubus", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sharkgirl, this.constructPath("monster-sharkgirl", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sheila, this.constructPath("monster-sheila", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_shouldra, this.constructPath("monster-shouldra", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sirius, this.constructPath("monster-sirius", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_sophie, this.constructPath("monster-sophie", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_spidermorphmob, this.constructPath("monster-spidermorphmob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_tamani, this.constructPath("monster-tamani", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_tamanisdaughters, this.constructPath("monster-tamanisdaughters", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_tentaclebeast, this.constructPath("monster-tentaclebeast", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_vala, this.constructPath("monster-vala", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_worms, this.constructPath("monster-worms", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.monster_zetaz, this.constructPath("monster-zetaz", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.niamh_approach_in_bar, this.constructPath("niamh-approach-in-bar", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.niamh_get_beer, this.constructPath("niamh-get-beer", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_at_cafe, this.constructPath("rubi-at-cafe", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_at_house, this.constructPath("rubi-at-house", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_dildo_fuck, this.constructPath("rubi-dildo-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_fuck, this.constructPath("rubi-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_fucks_you, this.constructPath("rubi-fucks-you", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_get_massage, this.constructPath("rubi-get-massage", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_get_ntr_ed, this.constructPath("rubi-get-ntr-ed", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_gro_plus_penis, this.constructPath("rubi-gro-plus-penis", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_gro_plus_tits, this.constructPath("rubi-gro-plus-tits", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_hotdogged, this.constructPath("rubi-hotdogged", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_inspect_appearance, this.constructPath("rubi-inspect-appearance", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_orgasm_denial_release, this.constructPath("rubi-orgasm-denial-release", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_pop_buttjob, this.constructPath("rubi-pop-buttjob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_tease, this.constructPath("rubi-tease", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.rubi_tease_buttjob, this.constructPath("rubi-tease-buttjob", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_feed_bar_intro, this.constructPath("scylla-feed-bar-intro", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_feed_jizz_solo_one, this.constructPath("scylla-feed-jizz-solo-one", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_feed_jizz_solo_three, this.constructPath("scylla-feed-jizz-solo-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_feed_jizz_solo_two, this.constructPath("scylla-feed-jizz-solo-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_first_help, this.constructPath("scylla-first-help", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_first_meeting, this.constructPath("scylla-first-meeting", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_firt_time, this.constructPath("scylla-help-round-five-firt-time", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_firt_time_pt_two, this.constructPath("scylla-help-round-five-firt-time-pt-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_jizz_pt_five, this.constructPath("scylla-help-round-five-jizz-pt-five", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_jizz_pt_four, this.constructPath("scylla-help-round-five-jizz-pt-four", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_jizz_pt_one, this.constructPath("scylla-help-round-five-jizz-pt-one", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_jizz_pt_three, this.constructPath("scylla-help-round-five-jizz-pt-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_jizz_pt_two, this.constructPath("scylla-help-round-five-jizz-pt-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_multi_cock_four, this.constructPath("scylla-help-round-five-multi-cock-four", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_multi_cock_one, this.constructPath("scylla-help-round-five-multi-cock-one", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_multi_cock_three, this.constructPath("scylla-help-round-five-multi-cock-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_multi_cock_two, this.constructPath("scylla-help-round-five-multi-cock-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_sex_pt_four, this.constructPath("scylla-help-round-five-sex-pt-four", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_sex_pt_one, this.constructPath("scylla-help-round-five-sex-pt-one", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_sex_pt_three, this.constructPath("scylla-help-round-five-sex-pt-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_sex_pt_two, this.constructPath("scylla-help-round-five-sex-pt-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_share, this.constructPath("scylla-help-round-five-share", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_take_advantage, this.constructPath("scylla-help-round-five-take-advantage", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_take_advantage_with_exgartuan_four, this.constructPath("scylla-help-round-five-take-advantage-with-exgartuan-four", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_take_advantage_with_exgartuan_one, this.constructPath("scylla-help-round-five-take-advantage-with-exgartuan-one", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_take_advantage_with_exgartuan_three, this.constructPath("scylla-help-round-five-take-advantage-with-exgartuan-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_take_advantage_with_exgartuan_two, this.constructPath("scylla-help-round-five-take-advantage-with-exgartuan-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_with_milk_five, this.constructPath("scylla-help-round-five-with-milk-five", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_with_milk_four, this.constructPath("scylla-help-round-five-with-milk-four", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_with_milk_one, this.constructPath("scylla-help-round-five-with-milk-one", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_with_milk_three, this.constructPath("scylla-help-round-five-with-milk-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_five_with_milk_two, this.constructPath("scylla-help-round-five-with-milk-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_four, this.constructPath("scylla-help-round-four", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_four_pt_three, this.constructPath("scylla-help-round-four-pt-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_four_pt_two, this.constructPath("scylla-help-round-four-pt-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_three, this.constructPath("scylla-help-round-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_two, this.constructPath("scylla-help-round-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_two_jizz, this.constructPath("scylla-help-round-two-jizz", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_two_part_three, this.constructPath("scylla-help-round-two-part-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_help_round_two_part_two, this.constructPath("scylla-help-round-two-part-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_share_tentacle_addiction_one, this.constructPath("scylla-share-tentacle-addiction-one", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_share_tentacle_addiction_three, this.constructPath("scylla-share-tentacle-addiction-three", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.scylla_share_tentacle_addiction_two, this.constructPath("scylla-share-tentacle-addiction-two", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_bar, this.constructPath("urta-bar", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_bar_bj, this.constructPath("urta-bar-bj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_bar_drunk, this.constructPath("urta-bar-drunk", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_bar_male_spank, this.constructPath("urta-bar-male-spank", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_bar_vag, this.constructPath("urta-bar-vag", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_behindbar_female_fuckurta, this.constructPath("urta-behindbar-female-fuckurta", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_behindbar_fuck, this.constructPath("urta-behindbar-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_behindbar_male_fuckurta, this.constructPath("urta-behindbar-male-fuckurta", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_behindbar_masti, this.constructPath("urta-behindbar-masti", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_behindbar_masti_dual, this.constructPath("urta-behindbar-masti-dual", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_behindbar_masti_solo, this.constructPath("urta-behindbar-masti-solo", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_bukkake, this.constructPath("urta-bukkake", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_egg_repeat, this.constructPath("urta-egg-repeat", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_fills_her_condom, this.constructPath("urta-fills-her-condom", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_goo_fuck, this.constructPath("urta-goo-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_69, this.constructPath("urta-home-69", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_anal, this.constructPath("urta-home-anal", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_anal_urta, this.constructPath("urta-home-anal-urta", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_bj, this.constructPath("urta-home-bj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_female_fuck, this.constructPath("urta-home-female-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_female_fucked, this.constructPath("urta-home-female-fucked", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_female_ride, this.constructPath("urta-home-female-ride", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_image, this.constructPath("urta-home-image", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_male_fuck, this.constructPath("urta-home-male-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_pegurta, this.constructPath("urta-home-pegurta", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_petplay_doggy, this.constructPath("urta-home-petplay-doggy", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_petplay_reward, this.constructPath("urta-home-petplay-reward", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_petplay_walkies, this.constructPath("urta-home-petplay-walkies", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_home_selfbj, this.constructPath("urta-home-selfbj", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_naga_fuck, this.constructPath("urta-naga-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_public_facial, this.constructPath("urta-public-facial", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_public_fuck, this.constructPath("urta-public-fuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_raphael_3some, this.constructPath("urta-raphael-3some", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_scylla_lapfuck, this.constructPath("urta-scylla-lapfuck", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_scylla_masti, this.constructPath("urta-scylla-masti", imageIndex, this.extentions[extIndex]));
                this.loadImage(ImageName.urta_syclla_3some, this.constructPath("urta-syclla-3some", imageIndex, this.extentions[extIndex]));                
            }
        }
    }
}
