import SpriteName from './SpriteName';
import Dictionary from '../../Utilities/Dictionary';

export default class SpriteLibrary extends Dictionary<string> {
    public constructor() {
        super();
        this.add(SpriteName.Akbal, "resource/sprites/akbal.png");
        this.add(SpriteName.Amarok, "resource/sprites/amarok.png");
        this.add(SpriteName.Amily, "resource/sprites/amily defurr.png");
        this.add(SpriteName.Amily_Defurr, "resource/sprites/amily.png");
        this.add(SpriteName.Anemone, "resource/sprites/anemone.png");
        this.add(SpriteName.Arian, "resource/sprites/arian.png");
        this.add(SpriteName.Basilisk, "resource/sprites/basilisk.png");
        this.add(SpriteName.Bee_Girl, "resource/sprites/bee girl.png");
        this.add(SpriteName.Ceraph, "resource/sprites/ceraph clothed.png");
        this.add(SpriteName.Ceraph_Clothed, "resource/sprites/ceraph goblin.png");
        this.add(SpriteName.Ceraph_Goblin, "resource/sprites/ceraph.png");
        this.add(SpriteName.Cerulean_Succubus, "resource/sprites/cerulean succubus.png");
        this.add(SpriteName.Chameleon, "resource/sprites/chameleon.png");
        this.add(SpriteName.Chicken_Harpy, "resource/sprites/chicken harpy.png");
        this.add(SpriteName.Chilly_Smith, "resource/sprites/chilly smith.png");
        this.add(SpriteName.Christmas_Elf, "resource/sprites/christmas elf.png");
        this.add(SpriteName.Cinnabar, "resource/sprites/cinnabar.png");
        this.add(SpriteName.Corrupted_Glade, "resource/sprites/corrupted glade.png");
        this.add(SpriteName.Cotton, "resource/sprites/cotton.png");
        this.add(SpriteName.Cumwitch, "resource/sprites/cumwitch.png");
        this.add(SpriteName.Dickworms, "resource/sprites/dickworms.png");
        this.add(SpriteName.Dominika_Cloaked, "resource/sprites/dominika cloaked.png");
        this.add(SpriteName.Dominika_Uncloaked, "resource/sprites/dominika uncloaked.png");
        this.add(SpriteName.Drider, "resource/sprites/drider.png");
        this.add(SpriteName.Easter_Bunny, "resource/sprites/easter bunny.png");
        this.add(SpriteName.Edryn, "resource/sprites/edryn.png");
        this.add(SpriteName.Exgartuan, "resource/sprites/exgartuan.png");
        this.add(SpriteName.Factory_Omnibus, "resource/sprites/factory omnibus.png");
        this.add(SpriteName.Faerie, "resource/sprites/faerie.png");
        this.add(SpriteName.Fen_Imp, "resource/sprites/fenimp.png");
        this.add(SpriteName.Fetish_Cultist, "resource/sprites/fetish cultist.png");
        this.add(SpriteName.Fetish_Zealot, "resource/sprites/fetish zealot.png");
        this.add(SpriteName.Giacomo, "resource/sprites/giacomo.png");
        this.add(SpriteName.Goblin, "resource/sprites/goblin elder.png");
        this.add(SpriteName.Goblin_Elder, "resource/sprites/goblin shaman.png");
        this.add(SpriteName.Goblin_Shaman, "resource/sprites/goblin warrior.png");
        this.add(SpriteName.Goblin_Warrior, "resource/sprites/goblin.png");
        this.add(SpriteName.Goo_Girl, "resource/sprites/goo girl.png");
        this.add(SpriteName.Gnoll_Club, "resource/sprites/club gnoll.png");
        this.add(SpriteName.Gnoll_Spear, "resource/sprites/spear gnoll.png");
        this.add(SpriteName.Greenslime, "resource/sprites/green slime.png");
        this.add(SpriteName.Harpy, "resource/sprites/harpy.png");
        this.add(SpriteName.Hel, "resource/sprites/hel.png");
        this.add(SpriteName.Hel_BB, "resource/sprites/hel BB.png");
        this.add(SpriteName.Hel_BB_PF, "resource/sprites/hel BB PF.png");
        this.add(SpriteName.Hel_PF, "resource/sprites/hel PF.png");
        this.add(SpriteName.Hel2, "resource/sprites/hel2.png");
        this.add(SpriteName.Hellhound, "resource/sprites/hellhound.png");
        this.add(SpriteName.Ifris, "resource/sprites/ifris.png");
        this.add(SpriteName.Imp, "resource/sprites/imp.png");
        this.add(SpriteName.Imp_Overlord, "resource/sprites/imp overlord.png");
        this.add(SpriteName.Imp_Warlord, "resource/sprites/imp warlord.png");
        this.add(SpriteName.Incubus_Mechanic, "resource/sprites/incubus mechanic.png");
        this.add(SpriteName.Isabella, "resource/sprites/isabella.png");
        this.add(SpriteName.Izma, "resource/sprites/izma.png");
        this.add(SpriteName.Jasun, "resource/sprites/jasun.png");
        this.add(SpriteName.Jojo, "resource/sprites/jojo tentacle.png");
        this.add(SpriteName.Jojo_Tentacle, "resource/sprites/jojo.png");
        this.add(SpriteName.Katherine, "resource/sprites/katherine.png");
        this.add(SpriteName.Kelt, "resource/sprites/kelt.png");
        this.add(SpriteName.Kida, "resource/sprites/kida.png");
        this.add(SpriteName.Kiha, "resource/sprites/kiha.png");
        this.add(SpriteName.Kitsune_Black, "resource/sprites/kitsune black.png");
        this.add(SpriteName.Kitsune_Blonde, "resource/sprites/kitsune blonde.png");
        this.add(SpriteName.Kitsune_Red, "resource/sprites/kitsune red.png");
        this.add(SpriteName.Lilium, "resource/sprites/lilium.png");
        this.add(SpriteName.Lottie, "resource/sprites/lottie.png");
        this.add(SpriteName.Lumi, "resource/sprites/lumi.png");
        this.add(SpriteName.Lynette, "resource/sprites/lynette.png");
        this.add(SpriteName.Maddie, "resource/sprites/maddie.png");
        this.add(SpriteName.Marae, "resource/sprites/marae.png");
        this.add(SpriteName.Marble, "resource/sprites/marble.png");
        this.add(SpriteName.Markus_and_Lucia, "resource/sprites/markus and lucia.png");
        this.add(SpriteName.Minerva_Corrupt, "resource/sprites/minerva corrupt.png");
        this.add(SpriteName.Minerva_Pure, "resource/sprites/minerva pure.png");
        this.add(SpriteName.Minerva, "resource/sprites/minerva.png");
        this.add(SpriteName.Minotaur, "resource/sprites/minotaur sons.png");
        this.add(SpriteName.Minotaur_Sons, "resource/sprites/minotaur.png");
        this.add(SpriteName.Mrs_Coffee, "resource/sprites/mrs coffee.png");
        this.add(SpriteName.Naga, "resource/sprites/naga.png");
        this.add(SpriteName.Oasis_Demons, "resource/sprites/oasis demons.png");
        this.add(SpriteName.Oswald, "resource/sprites/oswald.png");
        this.add(SpriteName.Poisontail, "resource/sprites/poisontail.png");
        this.add(SpriteName.Priscilla, "resource/sprites/priscilla.png");
        this.add(SpriteName.Rathazul, "resource/sprites/rathazul.png");
        this.add(SpriteName.Rogar, "resource/sprites/rogar.png");
        this.add(SpriteName.Rubi_Hornless, "resource/sprites/rubi hornless.png");
        this.add(SpriteName.Rubi_Horns, "resource/sprites/rubi horns.png");
        this.add(SpriteName.Sandtrap, "resource/sprites/sandtrap.png");
        this.add(SpriteName.Sandwich, "resource/sprites/sandwich.png");
        this.add(SpriteName.Satyr, "resource/sprites/satyr.png");
        this.add(SpriteName.Scylla, "resource/sprites/scylla and bear.png");
        this.add(SpriteName.Scylla_And_Bear, "resource/sprites/scylla.png");
        this.add(SpriteName.Sean, "resource/sprites/sean.png");
        this.add(SpriteName.Sharkgirl, "resource/sprites/sharkgirl.png");
        this.add(SpriteName.Sophie, "resource/sprites/sophie.png");
        this.add(SpriteName.Sophie_Bimbo, "resource/sprites/sophie bimbo.png");
        this.add(SpriteName.Spidergirl, "resource/sprites/spidergirl.png");
        this.add(SpriteName.Spiderguy, "resource/sprites/spiderguy.png");
        this.add(SpriteName.Stuck_Satyr, "resource/sprites/stuck satyr.png");
        this.add(SpriteName.Succubus_Secretary, "resource/sprites/succubus secretary.png");
        this.add(SpriteName.Tamani_Daughters, "resource/sprites/tamani daughters.png");
        this.add(SpriteName.Tamani, "resource/sprites/tamani.png");
        this.add(SpriteName.Tentacle_Monster, "resource/sprites/tentacle monster.png");
        this.add(SpriteName.Urta, "resource/sprites/urta drunk.png");
        this.add(SpriteName.Urta_Drunk, "resource/sprites/urta.png");
        this.add(SpriteName.Vagrant_Cats, "resource/sprites/vagrant cats.png");
        this.add(SpriteName.Vala, "resource/sprites/vala slave.png");
        this.add(SpriteName.Vala_Slave, "resource/sprites/vala.png");
        this.add(SpriteName.Valeria, "resource/sprites/valeria.png");
        this.add(SpriteName.Venus, "resource/sprites/venus.png");
        this.add(SpriteName.Victoria, "resource/sprites/victoria.png");
        this.add(SpriteName.Weaponsmith, "resource/sprites/weaponsmith.png");
        this.add(SpriteName.Yara, "resource/sprites/yara.png");
        this.add(SpriteName.Yvonne, "resource/sprites/yvonne.png");
    }
}
